# Alfheim Reclaimed -- bind the world spawn to the baked anchor
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# The success path. The anchor is a marker standing on the gate-chamber floor inside greatbole/base.nbt, so it lands wherever the structure lands and cannot drift from the tree the way a summoned marker at the origin did.
#
# One block up: the marker sits ON the floor, so ~ ~ ~ would spawn a player inside it.

# A summoned fallback anchor from an earlier attempt would make @e[limit=1] pick between
# two markers arbitrarily. The baked one is authoritative, so the other goes.
execute in mythicbotany:alfheim run kill @e[type=minecraft:marker,tag=alfheim_hub,tag=!alfheim_hub_baked]

execute in mythicbotany:alfheim at @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run setworldspawn ~ ~1 ~

# Release the generation force-load and keep only the hub itself loaded. Without this the
# server pays for 441 permanently loaded chunks for the life of the world.
execute in mythicbotany:alfheim run forceload remove all
execute in mythicbotany:alfheim run forceload add -6 -6 6 6


# COLLECT THE PLAYERS WHO ARRIVED FIRST. Anyone placed provisionally while the Greatbole
# was still generating carries the await tag; now that the anchor exists, bring them in.
# This is what makes a fast join self-healing instead of permanent -- the player joined at
# 31 seconds and the hub resolved minutes later, and nothing moved them.
execute in mythicbotany:alfheim as @a[tag=alfheim_awaiting_hub] at @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run tp @s ~ ~1 ~
execute in mythicbotany:alfheim as @a[tag=alfheim_awaiting_hub] at @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run spawnpoint @s ~ ~1 ~
execute as @a[tag=alfheim_awaiting_hub] run tellraw @s {"text":"[Alfheim] The Greatbole has finished generating. Welcome to the Hollow Court.","color":"green"}
tag @a[tag=alfheim_awaiting_hub] remove alfheim_awaiting_hub

scoreboard players set #created alfheim.hub 1
# #final is what stops hub/resolve. Only a real, structure-carried anchor sets it, so a
# provisional fallback never ends the search for the tree.
scoreboard players set #final alfheim.hub 1
tellraw @a[tag=!alfheim_quiet] {"text":"[Alfheim] World hub anchored to the Greatbole.","color":"green"}
say [Alfheim] world hub anchored to the Greatbole gate chamber.
