# Alfheim Reclaimed -- assemble the Greatbole at the current surface position
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# Called only by hub/place after the candidate footprint is loaded and its surface is known to be solid. The base is last because its baked anchor is the commit marker.

scoreboard players set #base_result alfheim.hub 0
scoreboard players set #trunk_result alfheim.hub 0
scoreboard players set #crown_result alfheim.hub 0
scoreboard players set #court_result alfheim.hub 0
execute store success score #trunk_result alfheim.hub run place template alfheim:greatbole/trunk ~-16 ~40 ~-16 none none 1 0
execute store success score #crown_result alfheim.hub run place template alfheim:greatbole/crown ~-24 ~64 ~-24 none none 1 0
execute store success score #court_result alfheim.hub run place template alfheim:court/amphitheatre ~-24 ~-3 ~-72 none none 1 0
execute store success score #base_result alfheim.hub run place template alfheim:greatbole/base ~-24 ~-8 ~-24 none none 1 0
# /place template deliberately preserves jigsaw blocks; retire the six authored sockets.
setblock ~ ~39 ~ air
setblock ~ ~1 ~-24 air
setblock ~ ~40 ~ air
setblock ~ ~63 ~ air
setblock ~ ~64 ~ air
setblock ~ ~1 ~-25 air
execute if score #base_result alfheim.hub matches 1 if score #trunk_result alfheim.hub matches 1 if score #crown_result alfheim.hub matches 1 if score #court_result alfheim.hub matches 1 run scoreboard players set #place_result alfheim.hub 1
execute if score #place_result alfheim.hub matches 0 run kill @e[type=minecraft:marker,tag=alfheim_hub_baked]
execute if score #place_result alfheim.hub matches 0 run kill @e[type=minecraft:marker,tag=alfheim_crown_probe]
execute if score #place_result alfheim.hub matches 0 run kill @e[type=richs_races_wood_elves:wood_elf,tag=alfheim_hub_court]
