# Alfheim Reclaimed -- create the world hub
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# Idempotent. Safe to run repeatedly and safe to run from #minecraft:load, which fires on every world load AND every /reload.
#
# Creation assembles the templates explicitly, stores the result, then verifies the structure-carried anchor. It never depends on incidental chunk generation.

scoreboard objectives add alfheim.hub dummy
scoreboard players set #attempts alfheim.hub 0
scoreboard players set #place_result alfheim.hub -1

function alfheim:hub/place

function alfheim:hub/resolve
