# Alfheim Reclaimed -- place exactly one Greatbole at the world origin
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# Idempotent and bounded. Loads the origin footprint and vertically adapts the complete royal complex to MOTION_BLOCKING_NO_LEAVES at X=0, Z=0.
#
# All seven templates must succeed before #place_result becomes 1; no entity is used to carry coordinates across unloaded chunks.

scoreboard players set #already alfheim.hub 0
execute in mythicbotany:alfheim if entity @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run scoreboard players set #already alfheim.hub 1
scoreboard players set #place_result alfheim.hub 0
execute if score #already alfheim.hub matches 1 run scoreboard players set #place_result alfheim.hub 1
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 run kill @e[type=minecraft:marker,tag=alfheim_crown_probe]
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 run kill @e[type=richs_races_wood_elves:wood_elf,tag=alfheim_hub_court]

# candidate 0 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -80 -128 80 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 0 positioned over motion_blocking_no_leaves run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

execute if score #place_result alfheim.hub matches 1 run say [Alfheim] deterministic Greatbole and royal complex assembly succeeded at X=0 Z=0; verifying its baked anchor.
execute if score #place_result alfheim.hub matches 0 run say [Alfheim] deterministic Greatbole template assembly failed at the origin; one retry remains.
