# Alfheim Reclaimed -- tear the hub down so it can be rebuilt
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# For an operator who has moved the structure or wants a fresh anchor. Does not touch the world, only the anchor and the flag.
#
# Kills only the SUMMONED fallback anchor. The baked anchor is part of greatbole/base.nbt and is written into the world exactly once, when its chunk first generates -- killing it would be unrecoverable without deleting the region file, so reset must leave it alone.

execute in mythicbotany:alfheim run kill @e[type=minecraft:marker,tag=alfheim_hub,tag=!alfheim_hub_baked]
scoreboard players reset #created alfheim.hub
scoreboard players set #attempts alfheim.hub 0
scoreboard players reset #final alfheim.hub
tellraw @s {"text":"[Alfheim] Hub reset. Run /function alfheim:hub/create.","color":"yellow"}
