# Alfheim Reclaimed -- wait for the Greatbole to generate, then anchor to it
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# The retry half of create. Reschedules itself every 5s until the baked anchor appears, then hands to hub/anchor. After ~2 minutes it establishes a provisional spawn, then keeps the bounded placement retry alive for roughly five minutes.
#
# Bounded on purpose: an unbounded self-schedule, in a world where the structure genuinely cannot generate, would reschedule for the life of the server.

scoreboard players add #attempts alfheim.hub 1

# Retry only when the command itself reported failure. A successful placement whose entity
# tick is delayed is left untouched, preventing a duplicate structure.
execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches 6 if score #place_result alfheim.hub matches ..0 run function alfheim:hub/place

# Success, and the only thing that ends the loop: the structure generated and brought its
# anchor with it. Runs even after a provisional fallback, which is the point -- the hub
# upgrades itself to the real tree the moment the chunk finishes.
execute in mythicbotany:alfheim unless score #final alfheim.hub matches 1 if entity @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run function alfheim:hub/anchor

# Provisional spawn at ~2 minutes so the world is never left without one. Does NOT stop
# the loop.
execute unless score #created alfheim.hub matches 1 if score #attempts alfheim.hub matches 24.. run function alfheim:hub/fallback

# Keep waiting for the real thing.
execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches ..60 run schedule function alfheim:hub/resolve 100t

execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches 61.. run say [Alfheim] gave up waiting for the Greatbole after 300s; the provisional origin spawn stands. Run /function alfheim:hub/reset then /function alfheim:hub/create to retry.
