# Alfheim Reclaimed -- put the running player in Alfheim, at the hub if there is one
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# The delivery half. Vanilla has no cross-dimension world spawn, so SOMETHING has to move a player into Alfheim; this is that something.
#
# CROSSING INTO ALFHEIM DOES NOT DEPEND ON THE HUB. Runtime-reported 2026-09-04: a player joined 31 seconds after world load, the Greatbole had not finished generating, and they were left standing in Midgard for the whole session. The old body was two commands, both anchored on `at @e[...marker...]` -- with no marker, both did nothing and the player never moved at all. Getting into the right WORLD is the part that must always work; landing on the tree is a refinement on top of it.
#
# So: cross first, unconditionally, then refine. A player is in Alfheim from the first second either way.
#
# Sets the respawn point too, so dying bedless returns them here rather than to Midgard.

# 1. CROSS. Unconditional, and safe to run on a player already in Alfheim. y=256 is above
#    any terrain, so this never suffocates; the next lines put them on the ground.
execute in mythicbotany:alfheim run tp @s 0 256 0

# 2. REFINE, if the hub has resolved: stand them in the gate chamber.
execute in mythicbotany:alfheim at @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run tp @s ~ ~1 ~
execute in mythicbotany:alfheim at @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run spawnpoint @s ~ ~1 ~
execute in mythicbotany:alfheim if entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run tag @s remove alfheim_awaiting_hub

# 3. NO HUB YET: land them on legal ground near the origin and mark them as owed a hub.
#    The range is deliberately small -- this is the hub neighbourhood, not the 2000-block
#    scatter the pre-2026-09-04 script used, which put every player somewhere different.
execute in mythicbotany:alfheim unless entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run spreadplayers 0 0 1 160 false @s
execute in mythicbotany:alfheim unless entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run spawnpoint @s ~ ~ ~
execute in mythicbotany:alfheim unless entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run tag @s add alfheim_awaiting_hub
execute in mythicbotany:alfheim unless entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] run tellraw @s {"text":"[Alfheim] The Greatbole is still generating. You have been placed nearby and will be moved to the gate chamber as soon as it finishes.","color":"yellow"}
