# Alfheim Reclaimed -- report hub state to the operator
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# READ-ONLY. An earlier draft set the caller's spawnpoint here, which is a surprising mutation in a command called status; a status command must be safe to run at any time.
#
# Written for the CONSOLE as much as for a player: the server has no @s, so this reports through `say` and `data get`, both of which print to the console log. That matters -- an operator setting up a headless server is exactly who needs this.

say [Alfheim] --- world hub status ---
execute unless score #created alfheim.hub matches 1 run say [Alfheim] hub: NOT CREATED -- run /function alfheim:hub/create
execute if score #created alfheim.hub matches 1 run say [Alfheim] hub: created

# Prints the anchor position straight into the console log.
execute in mythicbotany:alfheim run data get entity @e[type=minecraft:marker,tag=alfheim_hub,limit=1] Pos

execute in mythicbotany:alfheim unless entity @e[type=minecraft:marker,tag=alfheim_hub] run say [Alfheim] WARNING: no anchor entity in mythicbotany:alfheim -- the hub flag is set but the anchor is gone
