# Alfheim Reclaimed -- run on every world load
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# Wired to #minecraft:load. This is the line that makes hub creation independent of any player: the tag fires on server start with nobody connected.
#
# Creates the hub only once per world; #created survives in the scoreboard.

scoreboard objectives add alfheim.hub dummy
execute unless score #created alfheim.hub matches 1 run function alfheim:hub/create

# Re-assert the force-load every load: forceload state is per-world and an operator may
# legitimately have cleared it.
execute if score #created alfheim.hub matches 1 in mythicbotany:alfheim run forceload add -6 -6 6 6
