# Alfheim Reclaimed -- place exactly one Greatbole on safe ground
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# Idempotent and bounded. Checks a fixed lattice, loads one footprint at a time and calls hub/assemble at the first solid non-liquid WORLD_SURFACE position.
#
# All four templates must succeed before #place_result becomes 1; no entity is used to carry coordinates across unloaded chunks.

scoreboard players set #already alfheim.hub 0
execute in mythicbotany:alfheim if entity @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run scoreboard players set #already alfheim.hub 1
scoreboard players set #place_result alfheim.hub 0
execute if score #already alfheim.hub matches 1 run scoreboard players set #place_result alfheim.hub 1
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 run kill @e[type=minecraft:marker,tag=alfheim_crown_probe]
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 run kill @e[type=richs_races_wood_elves:wood_elf,tag=alfheim_hub_court]

# candidate 0 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -32 -80 32 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 0 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 192 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 160 -80 224 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 192 0 0 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -192 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -224 -80 -160 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -192 0 0 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 0 192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -32 112 32 224
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 0 -192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -32 -272 32 -160
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 -192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 192 192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 160 112 224 224
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 192 0 192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -192 192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -224 112 -160 224
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -192 0 192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 192 -192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 160 -272 224 -160
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 192 0 -192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -192 -192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -224 -272 -160 -160
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -192 0 -192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 384 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 352 -80 416 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 384 0 0 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -384 0
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -416 -80 -352 32
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -384 0 0 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 0 384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -32 304 32 416
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 0 -384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -32 -464 32 -352
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 0 0 -384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 384 192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 352 112 416 224
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 384 0 192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -384 192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -416 112 -352 224
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -384 0 192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 384 -192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 352 -272 416 -160
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 384 0 -192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -384 -192
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -416 -272 -352 -160
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -384 0 -192 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 192 384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 160 304 224 416
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 192 0 384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -192 384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -224 304 -160 416
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -192 0 384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate 192 -384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add 160 -464 224 -352
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned 192 0 -384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

# candidate -192 -384
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload add -224 -464 -160 -352
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 positioned -192 0 -384 positioned over world_surface unless block ~ ~-1 ~ minecraft:air unless block ~ ~-1 ~ minecraft:void_air unless block ~ ~-1 ~ minecraft:water unless block ~ ~-1 ~ minecraft:lava run function alfheim:hub/assemble
execute in mythicbotany:alfheim unless score #already alfheim.hub matches 1 if score #place_result alfheim.hub matches 0 run forceload remove all

execute if score #place_result alfheim.hub matches 1 run say [Alfheim] deterministic Greatbole template assembly succeeded; verifying its baked anchor.
execute if score #place_result alfheim.hub matches 0 run say [Alfheim] deterministic Greatbole template assembly found no valid site across 21 bounded candidates; one retry remains.
