# Alfheim Reclaimed -- wait for the Greatbole to generate, then anchor to it
#
# GENERATED by tools/gen_world_hub.py -- do not hand-edit.
#
# The retry half of create. Reschedules itself every 5s until the baked anchor appears, then hands to hub/anchor. After ~2 minutes it gives up and takes the fallback.
#
# Bounded on purpose: an unbounded self-schedule, in a world where the structure genuinely cannot generate, would reschedule for the life of the server.

scoreboard players add #attempts alfheim.hub 1

# Widen once if the near disc did not contain the tree -- the origin was void or lake and
# the biome search relocated it. Costs the bigger generation pass only when it is needed.
execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches 6 in mythicbotany:alfheim run forceload add -10 -10 10 10
execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches 6 run say [Alfheim] no Greatbole within 64 blocks of the origin; widening the search to 160.

# Success, and the only thing that ends the loop: the structure generated and brought its
# anchor with it. Runs even after a provisional fallback, which is the point -- the hub
# upgrades itself to the real tree the moment the chunk finishes.
execute in mythicbotany:alfheim unless score #final alfheim.hub matches 1 if entity @e[type=minecraft:marker,tag=alfheim_hub_baked,limit=1] run function alfheim:hub/anchor

# Provisional spawn at ~2 minutes so the world is never left without one. Does NOT stop
# the loop.
execute unless score #created alfheim.hub matches 1 if score #attempts alfheim.hub matches 24.. run function alfheim:hub/fallback

# Keep waiting for the real thing.
execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches ..240 run schedule function alfheim:hub/resolve 100t

execute unless score #final alfheim.hub matches 1 if score #attempts alfheim.hub matches 241.. run say [Alfheim] gave up waiting for the Greatbole after 1200s; the provisional origin spawn stands. Run /function alfheim:hub/reset then /function alfheim:hub/create to retry.
