package com.continuityworks.leyworks;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Alfheim Leyworks: the Ley Conduit Node.
 *
 * <p>Why this mod exists at all. LEY_LINE_CHANNEL_CORRIDORS.md specifies a block that reads a
 * beacon pyramid beneath it, projects that payload along all six cardinal axes through air and
 * approved glass, retransmits at full tier from every relay it reaches, and applies an aura to
 * players standing in the field. None of that is expressible in a datapack: it needs a block
 * entity with a tick. The corridors that carry these nodes are still generated by the datapack
 * (tools/gen_leyline_corridors.py) and nothing here touches worldgen.
 *
 * <p>Two blocks rather than one blockstate. The dormant node is inert and has no block entity at
 * all, so an undiscovered network costs nothing to have in the world; the active node is a
 * separate block that ticks. Converting between them is a crafting operation that consumes
 * {@code alfheim:elementium_core}, an Era 5 component, so lighting a network is a real
 * mid-game investment rather than a right-click.
 */
@Mod(Leyworks.MOD_ID)
public final class Leyworks {
    public static final String MOD_ID = "alfheim_leyworks";

    public static final DeferredRegister<Block> BLOCKS =
            DeferredRegister.create(ForgeRegistries.BLOCKS, MOD_ID);
    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, MOD_ID);
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES =
            DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, MOD_ID);

    /** Inert. What worldgen places, and what the player finds. */
    public static final RegistryObject<Block> DORMANT_NODE = BLOCKS.register(
            "ley_conduit_node_dormant",
            () -> new Block(BlockBehaviour.Properties.of()
                    .mapColor(MapColor.COLOR_LIGHT_BLUE)
                    .strength(3.0F, 9.0F)
                    .requiresCorrectToolForDrops()
                    .lightLevel(state -> 3)));

    /** Live. Reads a pyramid, projects, retransmits, applies the aura. */
    public static final RegistryObject<Block> ACTIVE_NODE = BLOCKS.register(
            "ley_conduit_node",
            () -> new LeyConduitNodeBlock(BlockBehaviour.Properties.of()
                    .mapColor(MapColor.COLOR_LIGHT_BLUE)
                    .strength(3.0F, 9.0F)
                    .requiresCorrectToolForDrops()
                    .lightLevel(state -> 12)));

    public static final RegistryObject<Item> DORMANT_NODE_ITEM = ITEMS.register(
            "ley_conduit_node_dormant",
            () -> new BlockItem(DORMANT_NODE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ACTIVE_NODE_ITEM = ITEMS.register(
            "ley_conduit_node",
            () -> new BlockItem(ACTIVE_NODE.get(), new Item.Properties()));

    public static final RegistryObject<BlockEntityType<LeyConduitNodeBlockEntity>> NODE_ENTITY =
            BLOCK_ENTITIES.register("ley_conduit_node",
                    () -> BlockEntityType.Builder
                            .of(LeyConduitNodeBlockEntity::new, ACTIVE_NODE.get())
                            .build(null));

    public Leyworks() {
        IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();
        BLOCKS.register(bus);
        ITEMS.register(bus);
        BLOCK_ENTITIES.register(bus);
        bus.addListener(this::addCreativeTabItems);
    }

    private void addCreativeTabItems(BuildCreativeModeTabContentsEvent event) {
        if (event.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
            event.accept(DORMANT_NODE_ITEM.get());
            event.accept(ACTIVE_NODE_ITEM.get());
        }
    }
}
