// Alfheim Reclaimed — the Twelve Blooms
//
// GENERATED by tools/gen_blooms.py from tools/blooms_manifest.json — do not hand-edit.
// Design: alfheim_reclaimed_design/ORE_SUPPLEMENTATION.md
//
// A bloom is not a metal. It is the pattern of one, left in the stone when the
// ley-lines died. Mining it gives you a raw bloom, which is inert until a Rite
// completes the pattern with living matter. See 12_rites.js.

StartupEvents.registry('block', event => {
    event.create('alfheim:cinderbloom_ore').displayName('Cinderbloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_stone_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/cinderbloom_ore')
    event.create('alfheim:verdigris_ore').displayName('Verdigris Bloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_stone_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/verdigris_ore')
    event.create('alfheim:palebloom_ore').displayName('Palebloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_stone_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/palebloom_ore')
    event.create('alfheim:sparkroot_ore').displayName('Sparkroot Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/sparkroot_ore')
    event.create('alfheim:duskbloom_ore').displayName('Duskbloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/duskbloom_ore')
    event.create('alfheim:sunbloom_ore').displayName('Sunbloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/sunbloom_ore')
    event.create('alfheim:cloudglass_ore').displayName('Cloudglass Bloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/cloudglass_ore')
    event.create('alfheim:silverthorn_ore').displayName('Silverthorn Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/silverthorn_ore')
    event.create('alfheim:grievebloom_ore').displayName('Grievebloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/grievebloom_ore')
    event.create('alfheim:rimebloom_ore').displayName('Rimebloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/rimebloom_ore')
    event.create('alfheim:emberwake_ore').displayName('Emberwake Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/emberwake_ore')
    event.create('alfheim:farbloom_ore').displayName('Farbloom Ore').soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').tagBlock('forge:ores').tagBlock('alfheim:blooms').textureAll('alfheim:block/farbloom_ore')
})

StartupEvents.registry('item', event => {
    event.create('alfheim:raw_cinderbloom').displayName('Raw Cinderbloom').tooltip('Burnt through, and still warm where you break it.').tag('forge:raw_materials')
    event.create('alfheim:quickened_cinderbloom').displayName('Quickened Cinderbloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_verdigris').displayName('Raw Verdigris Bloom').tooltip('Green as a drowned coin. It was copper once.').tag('forge:raw_materials')
    event.create('alfheim:quickened_verdigris').displayName('Quickened Verdigris Bloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_palebloom').displayName('Raw Palebloom').tooltip('The plainest of them, and the one you will want most.').tag('forge:raw_materials')
    event.create('alfheim:quickened_palebloom').displayName('Quickened Palebloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_sparkroot').displayName('Raw Sparkroot').tooltip('It runs a current through the stone it grew in.').tag('forge:raw_materials')
    event.create('alfheim:quickened_sparkroot').displayName('Quickened Sparkroot').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_duskbloom').displayName('Raw Duskbloom').tooltip('The colour of the hour the lights went out.').tag('forge:raw_materials')
    event.create('alfheim:quickened_duskbloom').displayName('Quickened Duskbloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_sunbloom').displayName('Raw Sunbloom').tooltip('It grew toward a sun that stopped reaching it.').tag('forge:raw_materials')
    event.create('alfheim:quickened_sunbloom').displayName('Quickened Sunbloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_cloudglass').displayName('Raw Cloudglass Bloom').tooltip('Clear all the way through, and cold to hold.').tag('forge:raw_materials')
    event.create('alfheim:quickened_cloudglass').displayName('Quickened Cloudglass Bloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_silverthorn').displayName('Raw Silverthorn').tooltip('Handle it by the flat. The edges are not decorative.').tag('forge:raw_materials')
    event.create('alfheim:quickened_silverthorn').displayName('Quickened Silverthorn').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_grievebloom').displayName('Raw Grievebloom').tooltip('It only grows where something finished dying.').tag('forge:raw_materials')
    event.create('alfheim:quickened_grievebloom').displayName('Quickened Grievebloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_rimebloom').displayName('Raw Rimebloom').tooltip('Frost that never learned to melt.').tag('forge:raw_materials')
    event.create('alfheim:quickened_rimebloom').displayName('Quickened Rimebloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_emberwake').displayName('Raw Emberwake').tooltip('Something in it is still burning, and has been for an age.').tag('forge:raw_materials')
    event.create('alfheim:quickened_emberwake').displayName('Quickened Emberwake').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
    event.create('alfheim:raw_farbloom').displayName('Raw Farbloom').tooltip('It is not entirely here, and it never has been.').tag('forge:raw_materials')
    event.create('alfheim:quickened_farbloom').displayName('Quickened Farbloom').tooltip('The pattern is closed. It will take heat now.').rarity('uncommon')
})
