// Alfheim Reclaimed — the Archive Groves
//
// GENERATED by tools/gen_groves.py from tools/groves_manifest.json — do not hand-edit.
//
// Three trees that carry other forests' seeds. No vanilla tree generates in Alfheim,
// so their leaves are the only source of oak, birch, spruce, acacia, jungle, dark oak
// and cherry saplings — and with them apples, plank variety and a normal wood economy.
//
// Their leaves drop plantable vanilla saplings, and more rarely their own — grown
// by growGrove() below, since KubeJS exposes no TreeGrower to hand the job to.

StartupEvents.registry('block', event => {
    event.create('alfheim:emberbark_log').displayName('Emberbark Log').soundType('wood').hardness(2.0).resistance(2.0).tagBlock('minecraft:mineable/axe').tagBlock('minecraft:logs').tagBlock('minecraft:logs_that_burn').tagBlock('alfheim:grove_logs').textureAll('alfheim:block/emberbark_log').texture('up', 'alfheim:block/emberbark_log_top').texture('down', 'alfheim:block/emberbark_log_top')
    event.create('alfheim:emberbark_leaves').displayName('Emberbark Leaves').soundType('grass').hardness(0.2).resistance(0.2).defaultCutout().notSolid().tagBlock('minecraft:mineable/hoe').tagBlock('minecraft:leaves').tagBlock('alfheim:grove_leaves').textureAll('alfheim:block/emberbark_leaves')
    event.create('alfheim:emberbark_sapling').displayName('Emberbark Sapling').soundType('grass').hardness(0.0).resistance(0.0).defaultCutout().notSolid().fullBlock(false).box(4, 0, 4, 12, 12, 12).tagBlock('minecraft:mineable/axe').tagBlock('alfheim:grove_saplings').textureAll('alfheim:block/emberbark_sapling').randomTick(ctx => growGrove(ctx, 'alfheim:emberbark_log', 'alfheim:emberbark_leaves', 5, 2, 2))
    event.create('alfheim:gloambark_log').displayName('Gloambark Log').soundType('wood').hardness(2.0).resistance(2.0).tagBlock('minecraft:mineable/axe').tagBlock('minecraft:logs').tagBlock('minecraft:logs_that_burn').tagBlock('alfheim:grove_logs').textureAll('alfheim:block/gloambark_log').texture('up', 'alfheim:block/gloambark_log_top').texture('down', 'alfheim:block/gloambark_log_top')
    event.create('alfheim:gloambark_leaves').displayName('Gloambark Leaves').soundType('grass').hardness(0.2).resistance(0.2).defaultCutout().notSolid().tagBlock('minecraft:mineable/hoe').tagBlock('minecraft:leaves').tagBlock('alfheim:grove_leaves').textureAll('alfheim:block/gloambark_leaves')
    event.create('alfheim:gloambark_sapling').displayName('Gloambark Sapling').soundType('grass').hardness(0.0).resistance(0.0).defaultCutout().notSolid().fullBlock(false).box(4, 0, 4, 12, 12, 12).tagBlock('minecraft:mineable/axe').tagBlock('alfheim:grove_saplings').textureAll('alfheim:block/gloambark_sapling').randomTick(ctx => growGrove(ctx, 'alfheim:gloambark_log', 'alfheim:gloambark_leaves', 6, 3, 3))
    event.create('alfheim:hushbark_log').displayName('Hushbark Log').soundType('wood').hardness(2.0).resistance(2.0).tagBlock('minecraft:mineable/axe').tagBlock('minecraft:logs').tagBlock('minecraft:logs_that_burn').tagBlock('alfheim:grove_logs').textureAll('alfheim:block/hushbark_log').texture('up', 'alfheim:block/hushbark_log_top').texture('down', 'alfheim:block/hushbark_log_top')
    event.create('alfheim:hushbark_leaves').displayName('Hushbark Leaves').soundType('grass').hardness(0.2).resistance(0.2).defaultCutout().notSolid().tagBlock('minecraft:mineable/hoe').tagBlock('minecraft:leaves').tagBlock('alfheim:grove_leaves').textureAll('alfheim:block/hushbark_leaves')
    event.create('alfheim:hushbark_sapling').displayName('Hushbark Sapling').soundType('grass').hardness(0.0).resistance(0.0).defaultCutout().notSolid().fullBlock(false).box(4, 0, 4, 12, 12, 12).tagBlock('minecraft:mineable/axe').tagBlock('alfheim:grove_saplings').textureAll('alfheim:block/hushbark_sapling').randomTick(ctx => growGrove(ctx, 'alfheim:hushbark_log', 'alfheim:hushbark_leaves', 5, 3, 2))
})

// Grow a grove tree from its sapling.
//
// Vanilla would do this with a TreeGrower placing the configured feature. KubeJS
// 2001.6.5 exposes neither, so the trunk and canopy are placed directly. Only
// offset(Direction, int) is confirmed present on BlockContainerJS, so horizontal
// offsets are reached by chaining it rather than by an offset(x, y, z) that may
// not exist.
//
// Headroom is checked before anything is written, so a sapling under a ceiling
// stays a sapling instead of growing a trunk into the floor above.
function growGrove(ctx, logId, leafId, baseH, randH, radius) {
    if (ctx.random.nextFloat() > 0.15) return
    const root = ctx.block
    const h = baseH + ctx.random.nextInt(randH + 1)

    for (let y = 1; y <= h + 1; y++) {
        const id = root.offset('up', y).id
        if (id !== 'minecraft:air' && id !== leafId) return
    }

    for (let y = 0; y < h; y++) root.offset('up', y).set(logId)

    for (let dy = -1; dy <= 2; dy++) {
        const r = dy >= 2 ? radius - 1 : radius
        if (r < 0) continue
        const layer = root.offset('up', h + dy - 1)
        for (let dx = -r; dx <= r; dx++) {
            for (let dz = -r; dz <= r; dz++) {
                if (Math.abs(dx) + Math.abs(dz) > r + 1) continue
                if (dx === 0 && dz === 0 && dy < 1) continue
                let t = layer
                if (dx !== 0) t = t.offset(dx > 0 ? 'east' : 'west', Math.abs(dx))
                if (dz !== 0) t = t.offset(dz > 0 ? 'south' : 'north', Math.abs(dz))
                if (t.id === 'minecraft:air') t.set(leafId)
            }
        }
    }
}
