// Alfheim Reclaimed — the sealed gate
//
// GENERATED by tools/gen_hollow_court.py — do not hand-edit.
//
// Scenery, deliberately. B-36 asks for a gate the player can SEE from Era I and cannot FINISH
// until Era IV, so this block is the seeing half and nothing else: no teleport, no state, no
// recipe. The traversal already exists (botania:alfheim_portal outward,
// mythicbotany:return_portal home) and gating it is B-36's job, not this block's.
//
// It is not in any mineable tag and has a high hardness on purpose: the point of the gate in
// Era I is that it does not open, and a player who can quietly pickaxe it has been told the
// wrong story about the pack.

StartupEvents.registry('block', event => {
    event.create('alfheim:sealed_gate')
        .displayName('Sealed Gate')
        .soundType('amethyst')
        .hardness(-1.0)
        .resistance(3600000.0)
        .lightLevel(0.6)
        .defaultTranslucent()
        .notSolid()
        .fullBlock(false)
        .textureAll('alfheim:block/sealed_gate')
})
