// Alfheim Reclaimed — Liquid Bifrost, the fluid
//
// GENERATED by tools/gen_liquid_bifrost.py — do not hand-edit.
//
// A real flowing fluid: KubeJS builds the source, the flowing variant, the fluid BLOCK that
// worldgen places, and the bucket, from this one call.
//
// COLOUR. Botania's bifrost cycles the rainbow per frame. A fluid tint is one ARGB value and
// cannot cycle, so this takes bifrost's character instead of its animation — a bright pale
// cyan that reads violet where it flows, which is bifrost at any single instant.
//
// luminosity 12 rather than 15: bright enough to light its own pool and to be visible across a
// lake at night, dim enough that a player cannot use it as free full-brightness lighting.
// Lower density than water so it layers on top rather than sinking, and low viscosity so the
// pools actually spread into a pool shape instead of sitting in a one-block dimple.

StartupEvents.registry('fluid', event => {
    // NAMESPACED on purpose. KubeJS registers a bare `event.create('liquid_bifrost')` under
    // its OWN namespace, giving kubejs:liquid_bifrost and kubejs:liquid_bifrost_bucket — and
    // every recipe below names alfheim:*, so the whole chain would have failed to resolve.
    // Every other startup script in this pack qualifies its ids for the same reason.
    event.create('alfheim:liquid_bifrost')
        .displayName('Liquid Bifrost')
        .thinTexture(0x9FE8FF)
        .color(0xB4F0FF)
        .bucketColor(0xB4F0FF)
        .luminosity(12)
        .density(900)
        .viscosity(900)
        .temperature(300)
        .translucent()
        .tag('alfheim:liquid_bifrost')
})
