// Alfheim Reclaimed — the Liquid Bifrost refinement chain
//
// GENERATED by tools/gen_liquid_bifrost.py — do not hand-edit.
//
// Four tiers, in the order the user specified: crystallized → condensed → refined → distilled.
// The items are declared here and the recipes that connect them live in
// server_scripts/17_liquid_bifrost.js, because a startup script cannot write recipes.

StartupEvents.registry('item', event => {
    event.create('alfheim:crystallized_bifrost').displayName('Crystallized Bifrost').tooltip('The pool, given a shape. It still hums.').rarity('common')
    event.create('alfheim:condensed_bifrost').displayName('Condensed Bifrost').tooltip('Four crystals pressed into one. The hum is lower now.').rarity('uncommon')
    event.create('alfheim:refined_bifrost').displayName('Refined Bifrost').tooltip('The impurities are gone. What is left is only the bridge.').rarity('uncommon')
    event.create('alfheim:distilled_bifrost').displayName('Distilled Bifrost').tooltip('The final form. It will become whatever magic you ask it to.').rarity('rare')
})
