# GENERATED by tools/gen_exotic_elven_home_pilot.py
say [Alfheim] placing exotic home pilot
setblock ~0 ~ ~0 alfheim:starbell_chandelier[facing=north]
setblock ~3 ~ ~0 alfheim:moonpool_lamp[facing=north]
setblock ~6 ~ ~0 alfheim:whisper_harp[facing=north]
setblock ~9 ~ ~0 alfheim:moonmirror[facing=north]
setblock ~12 ~ ~0 alfheim:levitating_planter[facing=north]
setblock ~15 ~ ~0 alfheim:nectar_fountain[facing=north]
setblock ~18 ~ ~0 alfheim:bottled_aurora[facing=north]
setblock ~21 ~ ~0 alfheim:miniature_ley_garden[facing=north]
say [Alfheim] exotic home pilot placed
