// Alfheim Reclaimed — the protected spawn hub
//
// GENERATED by tools/gen_spawn_hub.py — do not hand-edit.
// Design: alfheim_reclaimed_design/SPAWN_HUB.md §4.
//
// The hub is a destination the player returns to for the whole campaign, so it has to survive
// the whole campaign. A creeper crater in the amphitheatre on day 40 is not a war story, it is
// a broken quest hub.
//
// FTB Chunks is not installed, so this is not an FTB claim — it is the behaviour a claim would
// have given, done directly. If ftbchunks is added later, the map/team layer goes on top of
// this rather than replacing it.

const HUB_DIMENSION = 'mythicbotany:alfheim'
// The claim is centred on the ORIGIN, not on the tree, because no coordinate for the tree is
// knowable from a script: concentric_rings snaps ring 0 to a preferred_biomes match up to 112
// blocks away. HUB_RADIUS is sized to cover that whole search disc plus the structure, so the
// claim contains the tree no matter which way the search went. The spawn point does not rely
// on this box at all -- it is a marker baked into the base piece (see build_base).
const HUB_X = 0
const HUB_Z = 0
const HUB_RADIUS = 192

// Players may still build inside the hub by default. Flip this to lock it to operators, which
// is what "claimed by admins" implies if the hub is ever opened to other people.
const PROTECT_FROM_PLAYERS = false

function inHub(level, x, z) {
    if (!level) return false
    try {
        if (String(level.dimension) !== HUB_DIMENSION) return false
    } catch (e) {
        return false
    }
    return Math.abs(x - HUB_X) <= HUB_RADIUS && Math.abs(z - HUB_Z) <= HUB_RADIUS
}

const armed = []

// ---------------------------------------------------------------- no hostile spawns
try {
    EntityEvents.checkSpawn(event => {
        const e = event.entity
        if (!e || !inHub(e.level, e.x, e.z)) return
        // Our own court is summoned/placed, not spawned, so this never touches it — but the
        // name check is cheap insurance against a future spawn-based placement.
        if (e.type === 'richs_races_wood_elves:wood_elf') return
        if (e.living && e.monster) event.cancel()
    })
    armed.push('no-hostile-spawns')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm spawn suppression: ' + e)
}

// ---------------------------------------------------------------- no blast damage
try {
    LevelEvents.beforeExplosion(event => {
        if (inHub(event.level, event.x, event.z)) event.cancel()
    })
    armed.push('no-explosions')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm explosion protection: ' + e)
}

// ---------------------------------------------------------------- no mob griefing
try {
    BlockEvents.broken(event => {
        if (!inHub(event.level, event.block.x, event.block.z)) return
        const p = event.player
        if (!p) { event.cancel(); return }            // no player == a mob or a mechanism
        if (PROTECT_FROM_PLAYERS && !p.op) {
            event.cancel()
            p.tell('The court is under the protection of the Royal Elven Guard.')
        }
    })
    armed.push(PROTECT_FROM_PLAYERS ? 'blocks-locked-to-ops' : 'no-mob-block-breaking')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm block protection: ' + e)
}

ServerEvents.loaded(event => {
    console.info(`[Alfheim Reclaimed] spawn hub protected: ${HUB_RADIUS}-block radius at ` +
                 `${HUB_X},${HUB_Z} in ${HUB_DIMENSION} — armed: ${armed.join(', ')}` +
                 (armed.length < 3 ? '  ** SOME PROTECTIONS DID NOT ARM, see warnings above **'
                                   : ''))
})
