// Alfheim Reclaimed — the protected spawn hub
//
// GENERATED by tools/gen_spawn_hub.py — do not hand-edit.
// Design: alfheim_reclaimed_design/SPAWN_HUB_PROTECTION.md.
//
// The hub is a persistent campaign location. Two independent layers are intentional:
// FTB Chunks supplies visible server-team ownership; KubeJS suppresses hazards and provides
// an explicit non-op edit backstop even if claim state is ever lost or stale.

const HUB_DIMENSION = 'mythicbotany:alfheim'
const HUB_X = 0
const HUB_Z = 0
const HUB_RADIUS = 192
const HUB_FTB_TEAM = 'alfheim_hub'
const PROTECT_FROM_PLAYERS = true

function inHub(level, x, z) {
    if (!level) return false
    try {
        if (String(level.dimension) !== HUB_DIMENSION) return false
    } catch (e) {
        return false
    }
    return Math.abs(x - HUB_X) <= HUB_RADIUS && Math.abs(z - HUB_Z) <= HUB_RADIUS
}

function rejectHubEdit(event) {
    if (!inHub(event.level, event.block.x, event.block.z)) return
    const p = event.player
    if (!p) { event.cancel(); return }
    if (PROTECT_FROM_PLAYERS && !p.op) {
        event.cancel()
        p.tell('The court is under the protection of the Royal Elven Guard.')
    }
}

const armed = []

// ---------------------------------------------------------------- no hostile spawns
try {
    EntityEvents.checkSpawn(event => {
        const e = event.entity
        if (!e || !inHub(e.level, e.x, e.z)) return
        if (e.type === 'richs_races_wood_elves:wood_elf') return
        if (e.living && e.monster) event.cancel()
    })
    armed.push('no-hostile-spawns')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm spawn suppression: ' + e)
}

// ---------------------------------------------------------------- no blast damage
try {
    LevelEvents.beforeExplosion(event => {
        if (inHub(event.level, event.x, event.z)) event.cancel()
    })
    armed.push('no-explosions')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm explosion protection: ' + e)
}

// ---------------------------------------------------------------- no block breaking
try {
    BlockEvents.broken(rejectHubEdit)
    armed.push('break-locked-to-ops')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm block-break protection: ' + e)
}

// ---------------------------------------------------------------- no block placement
try {
    BlockEvents.placed(rejectHubEdit)
    armed.push('place-locked-to-ops')
} catch (e) {
    console.warn('[Alfheim Reclaimed] hub: could not arm block-place protection: ' + e)
}

ServerEvents.loaded(event => {
    const teamCreate = event.server.runCommandSilent(`ftbteams server create ${HUB_FTB_TEAM}`)
    const claimChanged = event.server.runCommandSilent(
        `execute in ${HUB_DIMENSION} run ftbchunks admin claim_as ${HUB_FTB_TEAM} ` +
        `${HUB_RADIUS} ${HUB_X} ${HUB_Z}`
    )
    console.info(`[Alfheim Reclaimed] spawn hub protection armed: ${armed.join(', ')}; ` +
                 `FTB team-create result=${teamCreate}, newly-claimed chunks=${claimChanged}. ` +
                 `Claim ownership still requires FTB read-back before runtime acceptance.`)
})
