// Alfheim Reclaimed — bloom drops
//
// GENERATED by tools/gen_blooms.py — do not hand-edit.
// addSimpleBlock(block, item) gives the standard ore contract: the raw item on a
// normal break, the block itself under Silk Touch, and explosion survival.

ServerEvents.blockLootTables(event => {
    event.addSimpleBlock('alfheim:cinderbloom_ore', 'alfheim:raw_cinderbloom')
    event.addSimpleBlock('alfheim:verdigris_ore', 'alfheim:raw_verdigris')
    event.addSimpleBlock('alfheim:palebloom_ore', 'alfheim:raw_palebloom')
    event.addSimpleBlock('alfheim:sparkroot_ore', 'alfheim:raw_sparkroot')
    event.addSimpleBlock('alfheim:duskbloom_ore', 'alfheim:raw_duskbloom')
    event.addSimpleBlock('alfheim:sunbloom_ore', 'alfheim:raw_sunbloom')
    event.addSimpleBlock('alfheim:cloudglass_ore', 'alfheim:raw_cloudglass')
    event.addSimpleBlock('alfheim:silverthorn_ore', 'alfheim:raw_silverthorn')
    event.addSimpleBlock('alfheim:grievebloom_ore', 'alfheim:raw_grievebloom')
    event.addSimpleBlock('alfheim:rimebloom_ore', 'alfheim:raw_rimebloom')
    event.addSimpleBlock('alfheim:emberwake_ore', 'alfheim:raw_emberwake')
    event.addSimpleBlock('alfheim:farbloom_ore', 'alfheim:raw_farbloom')

    console.info('[Alfheim Reclaimed] 12 bloom loot tables registered.')
})
