// Alfheim Reclaimed — the Four Rites
//
// GENERATED by tools/gen_blooms.py from tools/blooms_manifest.json — do not hand-edit.
// Design: alfheim_reclaimed_design/ORE_SUPPLEMENTATION.md §4
//
// A raw bloom holds the pattern of a metal but not the metal. A Rite completes that
// pattern with living matter — petals, grain, seed, sapling — and yields a Quickened
// bloom, which is the first form that will accept heat.
//
// The same raw bloom is valid input to every Rite the player has unlocked. Later Rites
// do not obsolete earlier ones; they pay better. That is the ladder.
//
// Every recipe type below was read from the shipping jar before it was emitted
// (B-41: a schema that parses is not a schema the game accepts).

ServerEvents.recipes(event => {
    const id = s => `alfheim:rites/${s}`

    // ---------------------------------------------------------- Cinderbloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_cinderbloom' }, { tag: 'botania:petals/black' }, { tag: 'botania:petals/black' }, { tag: 'minecraft:saplings' }],
        output: { item: 'alfheim:quickened_cinderbloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('cinderbloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_cinderbloom' }, mana: 3000,
        output: { item: 'alfheim:quickened_cinderbloom', count: 2 } })
        .id(id('cinderbloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_cinderbloom' }, { item: 'alfheim:raw_cinderbloom' }, { tag: 'botania:petals/black' }, { tag: 'minecraft:saplings' }], mana: 8000,
        output: { item: 'alfheim:quickened_cinderbloom', count: 6 } })
        .id(id('cinderbloom_grafting'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_cinderbloom' }, { item: 'alfheim:raw_cinderbloom' }, { item: 'alfheim:raw_cinderbloom' }, { item: 'alfheim:raw_cinderbloom' }],
        mana: 60000,
        fromColor: 10052940,
        toColor: 16733184,
        output: { item: 'alfheim:quickened_cinderbloom', count: 16 } })
        .id(id('cinderbloom_deepening'))

    event.smelting('minecraft:coal', 'alfheim:quickened_cinderbloom').id(id('cinderbloom_render'))
    event.blasting('minecraft:coal', 'alfheim:quickened_cinderbloom').id(id('cinderbloom_render_fast'))

    // ---------------------------------------------------------- Verdigris Bloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_verdigris' }, { tag: 'botania:petals/green' }, { tag: 'botania:petals/green' }, { item: 'minecraft:wheat' }],
        output: { item: 'alfheim:quickened_verdigris' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('verdigris_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_verdigris' }, mana: 3000,
        output: { item: 'alfheim:quickened_verdigris', count: 2 } })
        .id(id('verdigris_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_verdigris' }, { item: 'alfheim:raw_verdigris' }, { tag: 'botania:petals/green' }, { item: 'minecraft:wheat' }], mana: 8000,
        output: { item: 'alfheim:quickened_verdigris', count: 6 } })
        .id(id('verdigris_grafting'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_verdigris' }, { item: 'alfheim:raw_verdigris' }, { item: 'alfheim:raw_verdigris' }, { item: 'alfheim:raw_verdigris' }],
        mana: 60000,
        fromColor: 5020037,
        toColor: 65471,
        output: { item: 'alfheim:quickened_verdigris', count: 16 } })
        .id(id('verdigris_deepening'))

    event.smelting('minecraft:copper_ingot', 'alfheim:quickened_verdigris').id(id('verdigris_render'))
    event.blasting('minecraft:copper_ingot', 'alfheim:quickened_verdigris').id(id('verdigris_render_fast'))

    // ---------------------------------------------------------- Palebloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_palebloom' }, { tag: 'botania:petals/white' }, { tag: 'botania:petals/white' }, { item: 'minecraft:wheat' }],
        output: { item: 'alfheim:quickened_palebloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('palebloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_palebloom' }, mana: 3000,
        output: { item: 'alfheim:quickened_palebloom', count: 2 } })
        .id(id('palebloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_palebloom' }, { item: 'alfheim:raw_palebloom' }, { tag: 'botania:petals/white' }, { item: 'minecraft:wheat' }], mana: 8000,
        output: { item: 'alfheim:quickened_palebloom', count: 6 } })
        .id(id('palebloom_grafting'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_palebloom' }, { item: 'alfheim:raw_palebloom' }, { item: 'alfheim:raw_palebloom' }, { item: 'alfheim:raw_palebloom' }],
        mana: 60000,
        fromColor: 5013401,
        toColor: 43519,
        output: { item: 'alfheim:quickened_palebloom', count: 16 } })
        .id(id('palebloom_deepening'))

    event.smelting('minecraft:iron_ingot', 'alfheim:quickened_palebloom').id(id('palebloom_render'))
    event.blasting('minecraft:iron_ingot', 'alfheim:quickened_palebloom').id(id('palebloom_render_fast'))

    // ---------------------------------------------------------- Sparkroot
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_sparkroot' }, { tag: 'botania:petals/red' }, { tag: 'botania:petals/red' }, { item: 'minecraft:wheat_seeds' }],
        output: { item: 'alfheim:quickened_sparkroot' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('sparkroot_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_sparkroot' }, mana: 6000,
        output: { item: 'alfheim:quickened_sparkroot', count: 2 } })
        .id(id('sparkroot_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }, { tag: 'botania:petals/red' }, { item: 'minecraft:wheat_seeds' }], mana: 16000,
        output: { item: 'alfheim:quickened_sparkroot', count: 6 } })
        .id(id('sparkroot_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }, { tag: 'botania:petals/red' }], mana: 32000,
        output: { item: 'minecraft:glowstone_dust', count: 1 } })
        .id(id('sparkroot_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }, { item: 'alfheim:raw_sparkroot' }],
        mana: 120000,
        fromColor: 10046546,
        toColor: 16711701,
        output: { item: 'alfheim:quickened_sparkroot', count: 16 } })
        .id(id('sparkroot_deepening'))

    event.shapeless(Item.of('minecraft:redstone', 2), ['alfheim:quickened_sparkroot']).id(id('sparkroot_render'))

    // ---------------------------------------------------------- Duskbloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_duskbloom' }, { tag: 'botania:petals/blue' }, { tag: 'botania:petals/blue' }, { tag: 'minecraft:saplings' }],
        output: { item: 'alfheim:quickened_duskbloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('duskbloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_duskbloom' }, mana: 6000,
        output: { item: 'alfheim:quickened_duskbloom', count: 2 } })
        .id(id('duskbloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }, { tag: 'botania:petals/blue' }, { tag: 'minecraft:saplings' }], mana: 16000,
        output: { item: 'alfheim:quickened_duskbloom', count: 6 } })
        .id(id('duskbloom_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }, { tag: 'botania:petals/blue' }], mana: 32000,
        output: { item: 'ars_nouveau:source_gem', count: 1 } })
        .id(id('duskbloom_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }, { item: 'alfheim:raw_duskbloom' }],
        mana: 120000,
        fromColor: 5005209,
        toColor: 16383,
        output: { item: 'alfheim:quickened_duskbloom', count: 16 } })
        .id(id('duskbloom_deepening'))

    event.shapeless(Item.of('minecraft:lapis_lazuli', 2), ['alfheim:quickened_duskbloom']).id(id('duskbloom_render'))

    // ---------------------------------------------------------- Sunbloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_sunbloom' }, { tag: 'botania:petals/yellow' }, { tag: 'botania:petals/yellow' }, { item: 'minecraft:wheat' }],
        output: { item: 'alfheim:quickened_sunbloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('sunbloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_sunbloom' }, mana: 9000,
        output: { item: 'alfheim:quickened_sunbloom', count: 2 } })
        .id(id('sunbloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }, { tag: 'botania:petals/yellow' }, { item: 'minecraft:wheat' }], mana: 24000,
        output: { item: 'alfheim:quickened_sunbloom', count: 6 } })
        .id(id('sunbloom_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }, { tag: 'botania:petals/yellow' }], mana: 48000,
        output: { item: 'naturesaura:gold_leaf', count: 2 } })
        .id(id('sunbloom_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }, { item: 'alfheim:raw_sunbloom' }],
        mana: 180000,
        fromColor: 10061132,
        toColor: 16760576,
        output: { item: 'alfheim:quickened_sunbloom', count: 16 } })
        .id(id('sunbloom_deepening'))

    event.smelting('minecraft:gold_ingot', 'alfheim:quickened_sunbloom').id(id('sunbloom_render'))
    event.blasting('minecraft:gold_ingot', 'alfheim:quickened_sunbloom').id(id('sunbloom_render_fast'))

    // ---------------------------------------------------------- Cloudglass Bloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_cloudglass' }, { tag: 'botania:petals/light_blue' }, { tag: 'botania:petals/light_blue' }, { item: 'minecraft:bone_meal' }],
        output: { item: 'alfheim:quickened_cloudglass' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('cloudglass_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_cloudglass' }, mana: 9000,
        output: { item: 'alfheim:quickened_cloudglass', count: 2 } })
        .id(id('cloudglass_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }, { tag: 'botania:petals/light_blue' }, { item: 'minecraft:bone_meal' }], mana: 24000,
        output: { item: 'alfheim:quickened_cloudglass', count: 6 } })
        .id(id('cloudglass_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }, { tag: 'botania:petals/light_blue' }], mana: 48000,
        output: { item: 'minecraft:amethyst_shard', count: 1 } })
        .id(id('cloudglass_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }, { item: 'alfheim:raw_cloudglass' }],
        mana: 180000,
        fromColor: 5016729,
        toColor: 54527,
        output: { item: 'alfheim:quickened_cloudglass', count: 16 } })
        .id(id('cloudglass_deepening'))

    event.shapeless(Item.of('minecraft:quartz', 2), ['alfheim:quickened_cloudglass']).id(id('cloudglass_render'))

    // ---------------------------------------------------------- Silverthorn
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_silverthorn' }, { tag: 'botania:petals/light_gray' }, { tag: 'botania:petals/light_gray' }, { tag: 'minecraft:saplings' }],
        output: { item: 'alfheim:quickened_silverthorn' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('silverthorn_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_silverthorn' }, mana: 12000,
        output: { item: 'alfheim:quickened_silverthorn', count: 2 } })
        .id(id('silverthorn_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_silverthorn' }, { item: 'alfheim:raw_silverthorn' }, { tag: 'botania:petals/light_gray' }, { tag: 'minecraft:saplings' }], mana: 32000,
        output: { item: 'alfheim:quickened_silverthorn', count: 6 } })
        .id(id('silverthorn_grafting'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_silverthorn' }, { item: 'alfheim:raw_silverthorn' }, { item: 'alfheim:raw_silverthorn' }, { item: 'alfheim:raw_silverthorn' }],
        mana: 240000,
        fromColor: 5011865,
        toColor: 38143,
        output: { item: 'alfheim:quickened_silverthorn', count: 16 } })
        .id(id('silverthorn_deepening'))

    event.shapeless(Item.of('occultism:raw_silver', 1), ['alfheim:quickened_silverthorn']).id(id('silverthorn_render'))

    // ---------------------------------------------------------- Grievebloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_grievebloom' }, { tag: 'botania:petals/black' }, { tag: 'botania:petals/black' }, { item: 'minecraft:wheat_seeds' }],
        output: { item: 'alfheim:quickened_grievebloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('grievebloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_grievebloom' }, mana: 12000,
        output: { item: 'alfheim:quickened_grievebloom', count: 2 } })
        .id(id('grievebloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }, { tag: 'botania:petals/black' }, { item: 'minecraft:wheat_seeds' }], mana: 32000,
        output: { item: 'alfheim:quickened_grievebloom', count: 6 } })
        .id(id('grievebloom_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }, { tag: 'botania:petals/black' }], mana: 64000,
        output: { item: 'minecraft:ghast_tear', count: 1 } })
        .id(id('grievebloom_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }, { item: 'alfheim:raw_grievebloom' }],
        mana: 240000,
        fromColor: 8735897,
        toColor: 12517631,
        output: { item: 'alfheim:quickened_grievebloom', count: 16 } })
        .id(id('grievebloom_deepening'))

    event.shapeless(Item.of('minecraft:gunpowder', 2), ['alfheim:quickened_grievebloom']).id(id('grievebloom_render'))

    // ---------------------------------------------------------- Rimebloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_rimebloom' }, { tag: 'botania:petals/white' }, { tag: 'botania:petals/cyan' }, { tag: 'minecraft:saplings' }],
        output: { item: 'alfheim:quickened_rimebloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('rimebloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_rimebloom' }, mana: 15000,
        output: { item: 'alfheim:quickened_rimebloom', count: 2 } })
        .id(id('rimebloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_rimebloom' }, { item: 'alfheim:raw_rimebloom' }, { tag: 'botania:petals/white' }, { tag: 'minecraft:saplings' }], mana: 40000,
        output: { item: 'alfheim:quickened_rimebloom', count: 6 } })
        .id(id('rimebloom_grafting'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_rimebloom' }, { item: 'alfheim:raw_rimebloom' }, { item: 'alfheim:raw_rimebloom' }, { item: 'alfheim:raw_rimebloom' }],
        mana: 300000,
        fromColor: 5020057,
        toColor: 65535,
        output: { item: 'alfheim:quickened_rimebloom', count: 16 } })
        .id(id('rimebloom_deepening'))

    event.shapeless(Item.of('minecraft:diamond', 1), ['alfheim:quickened_rimebloom']).id(id('rimebloom_render'))

    // ---------------------------------------------------------- Emberwake
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_emberwake' }, { tag: 'botania:petals/orange' }, { tag: 'botania:petals/orange' }, { tag: 'minecraft:saplings' }],
        output: { item: 'alfheim:quickened_emberwake' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('emberwake_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_emberwake' }, mana: 21000,
        output: { item: 'alfheim:quickened_emberwake', count: 2 } })
        .id(id('emberwake_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }, { tag: 'botania:petals/orange' }, { tag: 'minecraft:saplings' }], mana: 56000,
        output: { item: 'alfheim:quickened_emberwake', count: 6 } })
        .id(id('emberwake_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }, { tag: 'botania:petals/orange' }], mana: 112000,
        output: { item: 'minecraft:magma_cream', count: 1 } })
        .id(id('emberwake_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }, { item: 'alfheim:raw_emberwake' }],
        mana: 420000,
        fromColor: 10053708,
        toColor: 16735488,
        output: { item: 'alfheim:quickened_emberwake', count: 16 } })
        .id(id('emberwake_deepening'))

    event.shapeless(Item.of('minecraft:blaze_powder', 2), ['alfheim:quickened_emberwake']).id(id('emberwake_render'))

    // ---------------------------------------------------------- Farbloom
    event.custom({ type: 'botania:petal_apothecary',
        ingredients: [{ item: 'alfheim:raw_farbloom' }, { tag: 'botania:petals/purple' }, { tag: 'botania:petals/purple' }, { item: 'minecraft:bone_meal' }],
        output: { item: 'alfheim:quickened_farbloom' },
        reagent: { tag: 'botania:seed_apothecary_reagent' } })
        .id(id('farbloom_steeping'))

    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:raw_farbloom' }, mana: 24000,
        output: { item: 'alfheim:quickened_farbloom', count: 2 } })
        .id(id('farbloom_quickening'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }, { tag: 'botania:petals/purple' }, { item: 'minecraft:bone_meal' }], mana: 64000,
        output: { item: 'alfheim:quickened_farbloom', count: 6 } })
        .id(id('farbloom_grafting'))

    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }, { tag: 'botania:petals/purple' }], mana: 128000,
        output: { item: 'minecraft:chorus_fruit', count: 1 } })
        .id(id('farbloom_grafting_bonus'))

    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_rites',
        ingredients: [{ item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }, { item: 'alfheim:raw_farbloom' }],
        mana: 480000,
        fromColor: 7490713,
        toColor: 8323327,
        output: { item: 'alfheim:quickened_farbloom', count: 16 } })
        .id(id('farbloom_deepening'))

    event.shapeless(Item.of('minecraft:ender_pearl', 1), ['alfheim:quickened_farbloom']).id(id('farbloom_render'))

    console.info('[Alfheim Reclaimed] Rites I-IV loaded for 12 blooms.')
})
