// Alfheim Reclaimed — Liquid Bifrost, Era 2
//
// GENERATED by tools/gen_liquid_bifrost.py — do not hand-edit.
//
// Tiers 1 and 2: the pool given a shape, then pressed.
//
// ERA-SCOPED FILENAME, ON PURPOSE. check_coverage.py reads a recipe's era from `_era<N>_` in
// its filename and can check nothing without it — the chain shipped as one un-scoped
// 17_liquid_bifrost.js and the coverage report said so directly: "24 contributive step(s)
// belong to no era ... they cannot be checked until they are era-scoped". Splitting the chain
// at its own era boundary is also honest about what it is: two tiers before the gate, two
// after.

// THE CHAIN, PART ONE. Both steps use a station Era II has already taught, which is the
// ordering rule: a recipe may only require a method some preceding quest unlocked.
//
//   bucket of liquid bifrost  --petal apothecary-->  crystallized
//   crystallized              --mana infusion---->   condensed

ServerEvents.recipes(event => {

    // ---- tier 1: the pool, given a shape --------------------------------------------------
    // Botania's petal apothecary is the first station the pack teaches, so the entry point to
    // a whole new material costs nothing the player has not already built.
    event.custom({
        type: 'botania:petal_apothecary',
        ingredients: [
            { item: 'botania:livingrock' },
            { item: 'minecraft:amethyst_shard' },
            { item: 'minecraft:amethyst_shard' },
            { item: 'minecraft:glowstone_dust' },
            { item: 'minecraft:prismarine_crystals' },
        ],
        // The apothecary CONSUMES its reagent, bucket and all, so the yield pays for the
        // iron. Pouring the pool in is also simply what the recipe should look like.
        reagent: { item: 'alfheim:liquid_bifrost_bucket' },
        output: { item: 'alfheim:crystallized_bifrost', count: 4 },
    }).id('alfheim:crystallized_bifrost')

    // ---- tier 2: four into one -------------------------------------------------------------
    event.custom({
        type: 'botania:mana_infusion',
        input: { item: 'alfheim:crystallized_bifrost' },
        output: { item: 'alfheim:condensed_bifrost' },
        mana: 4000,
    }).id('alfheim:condensed_bifrost')
})
