// Alfheim Reclaimed — Liquid Bifrost, Era 7
//
// GENERATED by tools/gen_liquid_bifrost.py — do not hand-edit.
//
// The renewable route: make the pools instead of finding them.
//
// ERA-SCOPED FILENAME, ON PURPOSE. check_coverage.py reads a recipe's era from `_era<N>_` in
// its filename and can check nothing without it — the chain shipped as one un-scoped
// 17_liquid_bifrost.js and the coverage report said so directly: "24 contributive step(s)
// belong to no era ... they cannot be checked until they are era-scoped". Splitting the chain
// at its own era boundary is also honest about what it is: two tiers before the gate, two
// after.

// WHY THIS EXISTS. Asked for by the user 2026-09-04: "we also need a high level renewable
// bifrost recipe, one would think using the mixer, with say water and a renewable crystal
// based ingredient."
//
// Until now Liquid Bifrost was strictly FINITE. The pools generate at 1-in-24 chunks and do not
// come back, so the bridge between thirteen magic systems was a consumable that ran out — and a
// player who spent their last bucket on the wrong conversion had permanently lost access to a
// system. That is a worse failure than the exchange rate being poor, because it is invisible
// until it has already happened.
//
// ERA VII, and that is not arbitrary: `cr_mix` (create:basin) is first taught by the Era VII
// ladder, so this is the earliest era that can require a mixer without violating the ordering
// rule. It is also the right POWER level — by Era VII a player has a working Create setup, and
// the renewable route should be a reward for that infrastructure rather than a way around the
// pools in the early game.
//
// WHAT MAKES IT RENEWABLE. `#alfheim:crystal_shards` holds exactly the six crystals that have a
// budding block, so every shard in the tag regrows. frost_shard is deliberately NOT in that tag
// — it has no budding form — which means the tag is already precisely "renewable crystal", and
// this recipe inherits that guarantee instead of restating it. Water is water. Mana powder is
// Botania's, and renewable by definition.
//
// The mana powder is the third ingredient for a reason. Crystal and water alone make a slurry;
// what makes bifrost is the charge. It is also what keeps this honest as a HIGH-level recipe:
// it costs a mana economy, not just two rocks.

ServerEvents.recipes(event => {

    // 250 mB per mix — four mixes to the bucket, at 8 shards and 2 mana powder per bucket.
    // Deliberately not cheaper than finding a pool: this is insurance against running out,
    // not a reason to stop looking.
    event.custom({
        type: 'create:mixing',
        heatRequirement: 'heated',
        ingredients: [
            { tag: 'alfheim:crystal_shards' },
            { tag: 'alfheim:crystal_shards' },
            { item: 'botania:mana_powder' },
            { amount: 500, fluid: 'minecraft:water', nbt: {} },
        ],
        results: [
            { amount: 250, fluid: 'alfheim:liquid_bifrost' },
        ],
    }).id('alfheim:liquid_bifrost_mixing')
})
