// Alfheim Reclaimed — Era 6: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 9 steps (2n-3). Chain consumes the Era 5 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era6/${s}`

    // step 1/9 — fey_altar
    {
        event.custom({ type: 'feywild:fey_altar',
            ingredients: [{ item: 'alfheim:elementium_core' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }, { item: 'minecraft:gold_ingot' }, { item: 'botania:livingrock' }],
            output: { item: 'alfheim:march_hide', count: 1 } })
            .id(id('march_hide'))
    }

    // step 2/9 — na_altar
    {
        event.custom({ type: 'naturesaura:altar',
            input: { item: 'alfheim:march_hide' },
            output: { item: 'alfheim:fey_bound_cord' },
            aura: 30000, time: 200 })
            .id(id('fey_bound_cord'))
    }

    // step 3/9 — apothecary
    {
        event.custom({ type: 'botania:petal_apothecary',
            ingredients: [{ item: 'alfheim:fey_bound_cord' }, { item: 'botania:livingrock' }],
            output: { item: 'alfheim:sinew_braid', count: 1 },
            reagent: { tag: 'botania:seed_apothecary_reagent' } })
            .id(id('sinew_braid'))
    }

    // step 4/9 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:sinew_braid' }],
            output: [{ item: 'alfheim:warded_sinew' }] })
            .id(id('warded_sinew'))
    }

    // step 5/9 — crush
    {
        event.custom({ type: 'ars_nouveau:crush',
            input: { item: 'alfheim:warded_sinew' },
            output: [{ item: 'alfheim:wildmarch_drawn', count: 1, chance: 1.0, maxRange: 1 }],
            skip_block_place: false })
            .id(id('wildmarch_drawn'))
    }

    // step 6/9 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:wildmarch_drawn' }, mana: 12000,
            output: { item: 'alfheim:wildmarch_folded' } })
            .id(id('wildmarch_folded'))
    }

    // step 7/9 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:wildmarch_folded' }],
            pedestalItems: [{ item: 'alfheim:wildmarch_folded' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:wildmarch_stilled' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('wildmarch_stilled'))
    }

    // step 8/9 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:wildmarch_stilled' }, { item: 'botania:dreamwood' }], mana: 18000,
            output: { item: 'alfheim:wildmarch_rebound', count: 1 } })
            .id(id('wildmarch_rebound'))
    }

    // step 9/9 — craft
    {
        event.shaped('alfheim:wildmarch_sinew', ['AB', 'BA'], { A: 'alfheim:wildmarch_rebound', B: 'botania:livingrock' })
            .id(id('wildmarch_sinew'))
    }

    console.info('[Alfheim Reclaimed] Era 6 tier ladder loaded.')
})
