// Alfheim Reclaimed — Era 8: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 13 steps (2n-3). Chain consumes the Era 7 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era8/${s}`

    // step 1/13 — cr_press
    {
        event.custom({ type: 'create:pressing',
            ingredients: [{ item: 'alfheim:emberbound_weave' }],
            results: [{ item: 'alfheim:frost_shard', count: 1 }] })
            .id(id('frost_shard'))
    }

    // step 2/13 — crush
    {
        event.custom({ type: 'ars_nouveau:crush',
            input: { item: 'alfheim:frost_shard' },
            output: [{ item: 'alfheim:silvered_flake', count: 1, chance: 1.0, maxRange: 1 }],
            skip_block_place: false })
            .id(id('silvered_flake'))
    }

    // step 3/13 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:silvered_flake' }, mana: 12000,
            output: { item: 'alfheim:archive_leaf' } })
            .id(id('archive_leaf'))
    }

    // step 4/13 — imbuement
    {
        event.custom({ type: 'ars_nouveau:imbuement',
            input: { item: 'alfheim:archive_leaf' }, count: 1,
            output: 'alfheim:rime_cord', source: 3000,
            pedestalItems: [] })
            .id(id('rime_cord'))
    }

    // step 5/13 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:rime_cord' }],
            pedestalItems: [{ item: 'alfheim:rime_cord' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:lattice_blank' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('lattice_blank'))
    }

    // step 6/13 — na_altar
    {
        event.custom({ type: 'naturesaura:altar',
            input: { item: 'alfheim:lattice_blank' },
            output: { item: 'alfheim:sealed_lattice' },
            aura: 30000, time: 200 })
            .id(id('sealed_lattice'))
    }

    // step 7/13 — occ_crush
    {
        event.custom({ type: 'occultism:crushing',
            ingredient: { item: 'alfheim:sealed_lattice' },
            result: { item: 'alfheim:rimebound_drawn', count: 1 },
            ignore_crushing_multiplier: false,
            crushing_time: 200 })
            .id(id('rimebound_drawn'))
    }

    // step 8/13 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:rimebound_drawn' }],
            output: [{ item: 'alfheim:rimebound_folded' }] })
            .id(id('rimebound_folded'))
    }

    // step 9/13 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:rimebound_folded' }, { item: 'botania:livingrock' }], mana: 18000,
            output: { item: 'alfheim:rimebound_stilled', count: 1 } })
            .id(id('rimebound_stilled'))
    }

    // step 10/13 — cr_seq
    {
        event.custom({ type: 'create:sequenced_assembly',
            ingredient: { item: 'alfheim:rimebound_stilled' },
            transitionalItem: { item: 'alfheim:incomplete_rimebound_rebound' },
            loops: 2,
            results: [{ item: 'alfheim:rimebound_rebound', count: 1 }],
            sequence: [
                { type: 'create:deploying',
                    ingredients: [{ item: 'alfheim:incomplete_rimebound_rebound' }, { item: 'botania:dreamwood' }],
                    keepHeldItem: false,
                    results: [{ item: 'alfheim:incomplete_rimebound_rebound' }] },
                { type: 'create:pressing',
                    ingredients: [{ item: 'alfheim:incomplete_rimebound_rebound' }],
                    results: [{ item: 'alfheim:incomplete_rimebound_rebound' }] }
            ] })
            .id(id('rimebound_rebound'))
    }

    // step 11/13 — infuser
    {
        event.custom({ type: 'mythicbotany:infuser',
            group: 'alfheim_ladder',
            ingredients: [{ item: 'alfheim:rimebound_rebound' }], mana: 400000,
            fromColor: 3367538, toColor: 2475257,
            output: { item: 'alfheim:rimebound_quenched' } })
            .id(id('rimebound_quenched'))
    }

    // step 12/13 — terra_plate
    {
        event.custom({ type: 'botania:terra_plate',
            ingredients: [{ item: 'alfheim:rimebound_quenched' }, { item: 'botania:dreamwood' }], mana: 250000,
            result: { item: 'alfheim:rimebound_layered' } })
            .id(id('rimebound_layered'))
    }

    // step 13/13 — craft
    {
        event.shaped('alfheim:rimebound_lattice', ['AB', 'BA'], { A: 'alfheim:rimebound_layered', B: 'botania:livingrock' })
            .id(id('rimebound_lattice'))
    }

    console.info('[Alfheim Reclaimed] Era 8 tier ladder loaded.')
})
