// Alfheim Reclaimed — Era 9: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 15 steps (2n-3). Chain consumes the Era 8 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era9/${s}`

    // step 1/15 — occ_fire
    {
        event.custom({ type: 'occultism:spirit_fire',
            ingredient: { item: 'alfheim:rimebound_lattice' },
            result: { item: 'alfheim:ash_of_names' } })
            .id(id('ash_of_names'))
    }

    // step 2/15 — occ_crush
    {
        event.custom({ type: 'occultism:crushing',
            ingredient: { item: 'alfheim:ash_of_names' },
            result: { item: 'alfheim:mourning_dust', count: 1 },
            ignore_crushing_multiplier: false,
            crushing_time: 200 })
            .id(id('mourning_dust'))
    }

    // step 3/15 — na_altar
    {
        event.custom({ type: 'naturesaura:altar',
            input: { item: 'alfheim:mourning_dust' },
            output: { item: 'alfheim:gilded_ash' },
            aura: 30000, time: 200 })
            .id(id('gilded_ash'))
    }

    // step 4/15 — brew
    {
        event.shapeless('alfheim:debt_cord', ['alfheim:gilded_ash', 'botania:dreamwood'])
            .id(id('debt_cord'))
    }

    // step 5/15 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:debt_cord' }, mana: 12000,
            output: { item: 'alfheim:reckoned_thread' } })
            .id(id('reckoned_thread'))
    }

    // step 6/15 — apothecary
    {
        event.custom({ type: 'botania:petal_apothecary',
            ingredients: [{ item: 'alfheim:reckoned_thread' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:grave_braid', count: 1 },
            reagent: { tag: 'botania:seed_apothecary_reagent' } })
            .id(id('grave_braid'))
    }

    // step 7/15 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:grave_braid' }],
            pedestalItems: [{ item: 'alfheim:grave_braid' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:settled_thread' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('settled_thread'))
    }

    // step 8/15 — imbuement
    {
        event.custom({ type: 'ars_nouveau:imbuement',
            input: { item: 'alfheim:settled_thread' }, count: 1,
            output: 'alfheim:gravegilt_drawn', source: 3000,
            pedestalItems: [] })
            .id(id('gravegilt_drawn'))
    }

    // step 9/15 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:gravegilt_drawn' }],
            output: [{ item: 'alfheim:gravegilt_folded' }] })
            .id(id('gravegilt_folded'))
    }

    // step 10/15 — cr_seq
    {
        event.custom({ type: 'create:sequenced_assembly',
            ingredient: { item: 'alfheim:gravegilt_folded' },
            transitionalItem: { item: 'alfheim:incomplete_gravegilt_stilled' },
            loops: 2,
            results: [{ item: 'alfheim:gravegilt_stilled', count: 1 }],
            sequence: [
                { type: 'create:deploying',
                    ingredients: [{ item: 'alfheim:incomplete_gravegilt_stilled' }, { item: 'botania:dreamwood' }],
                    keepHeldItem: false,
                    results: [{ item: 'alfheim:incomplete_gravegilt_stilled' }] },
                { type: 'create:pressing',
                    ingredients: [{ item: 'alfheim:incomplete_gravegilt_stilled' }],
                    results: [{ item: 'alfheim:incomplete_gravegilt_stilled' }] }
            ] })
            .id(id('gravegilt_stilled'))
    }

    // step 11/15 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:gravegilt_stilled' }, { item: 'botania:livingrock' }], mana: 18000,
            output: { item: 'alfheim:gravegilt_rebound', count: 1 } })
            .id(id('gravegilt_rebound'))
    }

    // step 12/15 — infuser
    {
        event.custom({ type: 'mythicbotany:infuser',
            group: 'alfheim_ladder',
            ingredients: [{ item: 'alfheim:gravegilt_rebound' }], mana: 400000,
            fromColor: 6108018, toColor: 11740665,
            output: { item: 'alfheim:gravegilt_quenched' } })
            .id(id('gravegilt_quenched'))
    }

    // step 13/15 — terra_plate
    {
        event.custom({ type: 'botania:terra_plate',
            ingredients: [{ item: 'alfheim:gravegilt_quenched' }, { item: 'botania:livingrock' }], mana: 250000,
            result: { item: 'alfheim:gravegilt_layered' } })
            .id(id('gravegilt_layered'))
    }

    // step 14/15 — na_tree
    {
        event.custom({ type: 'naturesaura:tree_ritual',
            sapling: { item: 'minecraft:oak_sapling' },
            ingredients: [{ item: 'alfheim:gravegilt_layered' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }, { item: 'naturesaura:gold_leaf' }],
            output: { item: 'alfheim:gravegilt_proofed' }, time: 400 })
            .id(id('gravegilt_proofed'))
    }

    // step 15/15 — craft
    {
        event.shaped('alfheim:gravegilt_thread', ['AB', 'BA'], { A: 'alfheim:gravegilt_proofed', B: 'botania:livingrock' })
            .id(id('gravegilt_thread'))
    }

    console.info('[Alfheim Reclaimed] Era 9 tier ladder loaded.')
})
