// Alfheim Reclaimed — uses for the custom materials
//
// GENERATED by tools/gen_item_uses.py — do not hand-edit.
//
// Every ladder intermediate gets 2-6 uses beyond feeding the next step, so materials
// are worth keeping rather than being single-purpose tokens. Outputs are existing
// items only; this adds no new registrations.

ServerEvents.recipes(event => {
    const id = s => `alfheim:uses/${s}`

    // ---------------------------------------------- Era 3
    // Living Fibre — 4 uses: shortcut, multiplier, edible, restorative
    event.shapeless('alfheim:charged_fibre', ['4x alfheim:living_fibre', 'botania:mana_powder']).id(id('living_fibre_shortcut'))
    event.shapeless('2x minecraft:iron_ingot', ['alfheim:quickened_palebloom', 'alfheim:living_fibre']).id(id('living_fibre_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:living_fibre' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('living_fibre_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:living_fibre' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('living_fibre_heal'))

    // Charged Fibre — 2 uses: multiplier, edible
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_verdigris' }, catalyst: { item: 'alfheim:charged_fibre' }, output: { item: 'minecraft:copper_ingot', count: 3 }, aura: 12000, time: 120 }).id(id('charged_fibre_mult'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:charged_fibre', 'minecraft:apple']).id(id('charged_fibre_food'))

    // Verdant Filament — 2 uses: multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:verdant_filament' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('verdant_filament_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:verdant_filament' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('verdant_filament_food'))

    // ---------------------------------------------- Era 4
    // Sunbleached Floss — 2 uses: enhancer, reagent
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:sunbleached_floss' }], results: [{ item: 'botania:mana_powder', count: 4 }], processingTime: 150 }).id(id('sunbleached_floss_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:sunbleached_floss' }, catalyst: { item: 'alfheim:emberglass_shard' }, output: { item: 'minecraft:blaze_powder', count: 2 }, aura: 12000, time: 120 }).id(id('sunbleached_floss_reagent'))

    // Traded Skein — 2 uses: multiplier, edible
    event.shapeless('2x occultism:silver_ingot', ['alfheim:quickened_silverthorn', 'alfheim:traded_skein']).id(id('traded_skein_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:traded_skein' }, { item: 'farmersdelight:pumpkin_slice' }], results: [{ item: 'minecraft:golden_carrot', count: 2 }] }).id(id('traded_skein_food'))

    // Gatewrought Drawn — 2 uses: multiplier, edible
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_rimebloom' }, { item: 'alfheim:gatewrought_drawn' }], results: [{ item: 'minecraft:diamond', count: 2 }] }).id(id('gatewrought_drawn_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gatewrought_drawn' }, catalyst: { item: 'minecraft:bread' }, output: { item: 'minecraft:golden_carrot', count: 1 }, aura: 12000, time: 120 }).id(id('gatewrought_drawn_food'))

    // Gatewrought Folded — 4 uses: restorative, enhancer, reagent, shortcut
    event.shapeless('1x minecraft:golden_apple', ['alfheim:gatewrought_folded', 'alfheim:quickened_grievebloom']).id(id('gatewrought_folded_heal'))
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:gatewrought_folded' }], results: [{ item: 'ars_nouveau:source_gem', count: 3 }], processingTime: 150 }).id(id('gatewrought_folded_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:gatewrought_folded' }, { item: 'alfheim:duskglass_shard' }], results: [{ item: 'minecraft:gunpowder', count: 3 }] }).id(id('gatewrought_folded_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gatewrought_folded' }, { item: 'alfheim:gatewrought_folded' }, { item: 'alfheim:gatewrought_folded' }, { item: 'alfheim:gatewrought_folded' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:gatewrought_cord', count: 1 }] }).id(id('gatewrought_folded_shortcut'))

    // Gatewrought Cord — 2 uses: multiplier, edible
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:gatewrought_cord' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('gatewrought_cord_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gatewrought_cord' }, catalyst: { item: 'minecraft:apple' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('gatewrought_cord_food'))

    // ---------------------------------------------- Era 5
    // Raw Alloy Grit — 3 uses: reagent, shortcut, multiplier
    event.shapeless('4x minecraft:redstone', ['alfheim:raw_alloy_grit', 'alfheim:tidewake_shard']).id(id('raw_alloy_grit_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:raw_alloy_grit' }, { item: 'alfheim:raw_alloy_grit' }, { item: 'alfheim:raw_alloy_grit' }, { item: 'alfheim:raw_alloy_grit' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:annealed_plate', count: 1 } }).id(id('raw_alloy_grit_shortcut'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_palebloom' }, { item: 'alfheim:raw_alloy_grit' }], results: [{ item: 'minecraft:iron_ingot', count: 2 }] }).id(id('raw_alloy_grit_mult'))

    // Annealed Plate — 4 uses: shortcut, multiplier, edible, restorative
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:annealed_plate' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:core_blank', count: 1 }, aura: 30000, time: 200 }).id(id('annealed_plate_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:annealed_plate' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('annealed_plate_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:annealed_plate' }, catalyst: { item: 'minecraft:melon_slice' }, output: { item: 'minecraft:glistering_melon_slice', count: 3 }, aura: 12000, time: 120 }).id(id('annealed_plate_food'))
    event.shapeless('4x minecraft:golden_carrot', ['alfheim:annealed_plate', 'botania:mana_powder']).id(id('annealed_plate_heal'))

    // Core Blank — 3 uses: edible, restorative, enhancer
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:core_blank' }, { item: 'farmersdelight:pumpkin_slice' }], results: [{ item: 'minecraft:golden_carrot', count: 2 }] }).id(id('core_blank_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:core_blank' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('core_blank_heal'))
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:core_blank' }], results: [{ item: 'naturesaura:aura_cache', count: 1 }] }).id(id('core_blank_enhance'))

    // Elementium Drawn — 2 uses: enhancer, reagent
    event.custom({ type: 'create:haunting', ingredients: [{ item: 'alfheim:elementium_drawn' }], results: [{ item: 'botania:white_petal', count: 6 }] }).id(id('elementium_drawn_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:elementium_drawn' }, catalyst: { item: 'alfheim:rootglass_shard' }, output: { item: 'minecraft:glowstone_dust', count: 2 }, aura: 12000, time: 120 }).id(id('elementium_drawn_reagent'))

    // Elementium Folded — 2 uses: enhancer, reagent
    event.custom({ type: 'create:splashing', ingredients: [{ item: 'alfheim:elementium_folded' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }] }).id(id('elementium_folded_enhance'))
    event.shapeless('8x minecraft:torch', ['alfheim:elementium_folded', 'alfheim:quickened_cinderbloom']).id(id('elementium_folded_reagent'))

    // Elementium Stilled — 2 uses: multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:elementium_stilled' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('elementium_stilled_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:elementium_stilled' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('elementium_stilled_food'))

    // Elementium Core — 4 uses: restorative, enhancer, reagent, shortcut
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:elementium_core' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('elementium_core_heal'))
    event.custom({ type: 'create:cutting', ingredients: [{ item: 'alfheim:elementium_core' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }], processingTime: 150 }).id(id('elementium_core_enhance'))
    event.shapeless('2x ars_nouveau:source_gem', ['alfheim:elementium_core', 'alfheim:quickened_duskbloom']).id(id('elementium_core_reagent'))

    // ---------------------------------------------- Era 6
    // March Hide — 4 uses: restorative, enhancer, reagent, shortcut
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:march_hide' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('march_hide_heal'))
    event.custom({ type: 'create:sandpaper_polishing', ingredients: [{ item: 'alfheim:march_hide' }], results: [{ item: 'botania:mana_powder', count: 4 }] }).id(id('march_hide_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:march_hide' }, { item: 'alfheim:quickened_cloudglass' }], results: [{ item: 'minecraft:glass', count: 4 }] }).id(id('march_hide_reagent'))
    event.shapeless('alfheim:fey_bound_cord', ['4x alfheim:march_hide', 'botania:mana_powder']).id(id('march_hide_shortcut'))

    // Fey Bound Cord — 4 uses: shortcut, multiplier, edible, restorative
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:fey_bound_cord' }, { item: 'alfheim:fey_bound_cord' }, { item: 'alfheim:fey_bound_cord' }, { item: 'alfheim:fey_bound_cord' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:sinew_braid', count: 1 }] }).id(id('fey_bound_cord_shortcut'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_silverthorn' }, catalyst: { item: 'alfheim:fey_bound_cord' }, output: { item: 'occultism:silver_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('fey_bound_cord_mult'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:fey_bound_cord', 'minecraft:apple']).id(id('fey_bound_cord_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:fey_bound_cord' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('fey_bound_cord_heal'))

    // Sinew Braid — 2 uses: enhancer, reagent
    event.custom({ type: 'ars_nouveau:crush', input: { item: 'alfheim:sinew_braid' }, output: [{ item: 'ars_nouveau:source_gem', count: 3, chance: 1.0, maxRange: 1 }], skip_block_place: false }).id(id('sinew_braid_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:sinew_braid' }, { item: 'alfheim:quickened_emberwake' }], results: [{ item: 'minecraft:magma_cream', count: 2 }] }).id(id('sinew_braid_reagent'))

    // Warded Sinew — 3 uses: reagent, shortcut, multiplier
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:warded_sinew' }, catalyst: { item: 'alfheim:quickened_farbloom' }, output: { item: 'minecraft:ender_eye', count: 1 }, aura: 12000, time: 120 }).id(id('warded_sinew_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:warded_sinew' }, { item: 'alfheim:warded_sinew' }, { item: 'alfheim:warded_sinew' }, { item: 'alfheim:warded_sinew' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:wildmarch_drawn', count: 1 } }).id(id('warded_sinew_shortcut'))
    event.shapeless('2x minecraft:diamond', ['alfheim:quickened_rimebloom', 'alfheim:warded_sinew']).id(id('warded_sinew_mult'))

    // Wildmarch Drawn — 3 uses: reagent, shortcut, multiplier
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:wildmarch_drawn' }, { item: 'alfheim:emberglass_shard' }], results: [{ item: 'minecraft:blaze_powder', count: 2 }] }).id(id('wildmarch_drawn_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:wildmarch_drawn' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:wildmarch_folded', count: 1 }, aura: 30000, time: 200 }).id(id('wildmarch_drawn_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:wildmarch_drawn' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('wildmarch_drawn_mult'))

    // Wildmarch Folded — 3 uses: reagent, shortcut, multiplier
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:wildmarch_folded' }, catalyst: { item: 'alfheim:duskglass_shard' }, output: { item: 'minecraft:gunpowder', count: 3 }, aura: 12000, time: 120 }).id(id('wildmarch_folded_reagent'))
    event.shapeless('alfheim:wildmarch_stilled', ['4x alfheim:wildmarch_folded', 'botania:mana_powder']).id(id('wildmarch_folded_shortcut'))
    event.shapeless('2x minecraft:iron_ingot', ['alfheim:quickened_palebloom', 'alfheim:wildmarch_folded']).id(id('wildmarch_folded_mult'))

    // Wildmarch Stilled — 2 uses: multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:wildmarch_stilled' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('wildmarch_stilled_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:wildmarch_stilled' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('wildmarch_stilled_food'))

    // Wildmarch Rebound — 2 uses: enhancer, reagent
    event.custom({ type: 'botania:mana_infusion', input: { item: 'alfheim:wildmarch_rebound' }, mana: 1200, output: { item: 'naturesaura:aura_cache', count: 1 } }).id(id('wildmarch_rebound_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:wildmarch_rebound' }, catalyst: { item: 'alfheim:tidewake_shard' }, output: { item: 'minecraft:redstone', count: 4 }, aura: 12000, time: 120 }).id(id('wildmarch_rebound_reagent'))

    // Wildmarch Sinew — 3 uses: reagent, shortcut, multiplier
    event.shapeless('2x minecraft:glowstone_dust', ['alfheim:wildmarch_sinew', 'alfheim:rootglass_shard']).id(id('wildmarch_sinew_reagent'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:wildmarch_sinew' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('wildmarch_sinew_mult'))

    // ---------------------------------------------- Era 7
    // Scorched Filament — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:scorched_filament' }], results: [{ item: 'botania:white_petal', count: 6 }], processingTime: 150 }).id(id('scorched_filament_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:scorched_filament' }, { item: 'alfheim:quickened_cinderbloom' }], results: [{ item: 'minecraft:torch', count: 8 }] }).id(id('scorched_filament_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:scorched_filament' }, { item: 'alfheim:scorched_filament' }, { item: 'alfheim:scorched_filament' }, { item: 'alfheim:scorched_filament' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:quenched_thread', count: 1 }] }).id(id('scorched_filament_shortcut'))

    // Quenched Thread — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quenched_thread' }, catalyst: { item: 'alfheim:quickened_duskbloom' }, output: { item: 'ars_nouveau:source_gem', count: 2 }, aura: 12000, time: 120 }).id(id('quenched_thread_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:quenched_thread' }, { item: 'alfheim:quenched_thread' }, { item: 'alfheim:quenched_thread' }, { item: 'alfheim:quenched_thread' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:ember_lattice', count: 1 } }).id(id('quenched_thread_shortcut'))
    event.shapeless('2x occultism:silver_ingot', ['alfheim:quickened_silverthorn', 'alfheim:quenched_thread']).id(id('quenched_thread_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quenched_thread' }, { item: 'farmersdelight:pumpkin_slice' }], results: [{ item: 'minecraft:golden_carrot', count: 2 }] }).id(id('quenched_thread_food'))

    // Ember Lattice — 4 uses: edible, restorative, enhancer, reagent
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:ember_lattice' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('ember_lattice_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:ember_lattice' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('ember_lattice_heal'))
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:ember_lattice' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }], processingTime: 150 }).id(id('ember_lattice_enhance'))
    event.shapeless('4x minecraft:glass', ['alfheim:ember_lattice', 'alfheim:quickened_cloudglass']).id(id('ember_lattice_reagent'))

    // Bound Weave — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:bound_weave' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }] }).id(id('bound_weave_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:bound_weave' }, { item: 'alfheim:quickened_emberwake' }], results: [{ item: 'minecraft:magma_cream', count: 2 }] }).id(id('bound_weave_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:bound_weave' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:tempered_weave', count: 1 }, aura: 30000, time: 200 }).id(id('bound_weave_shortcut'))

    // Tempered Weave — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:tempered_weave' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('tempered_weave_heal'))
    event.custom({ type: 'create:haunting', ingredients: [{ item: 'alfheim:tempered_weave' }], results: [{ item: 'botania:mana_powder', count: 4 }] }).id(id('tempered_weave_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:tempered_weave' }, catalyst: { item: 'alfheim:quickened_farbloom' }, output: { item: 'minecraft:ender_eye', count: 1 }, aura: 12000, time: 120 }).id(id('tempered_weave_reagent'))
    event.shapeless('alfheim:emberbound_drawn', ['4x alfheim:tempered_weave', 'botania:mana_powder']).id(id('tempered_weave_shortcut'))
    event.shapeless('2x minecraft:diamond', ['alfheim:quickened_rimebloom', 'alfheim:tempered_weave']).id(id('tempered_weave_mult'))

    // Emberbound Drawn — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:emberbound_drawn' }, { item: 'alfheim:emberbound_drawn' }, { item: 'alfheim:emberbound_drawn' }, { item: 'alfheim:emberbound_drawn' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:emberbound_folded', count: 1 }] }).id(id('emberbound_drawn_shortcut'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:emberbound_drawn' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('emberbound_drawn_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:emberbound_drawn' }, { item: 'minecraft:apple' }], results: [{ item: 'minecraft:golden_apple', count: 1 }] }).id(id('emberbound_drawn_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:emberbound_drawn' }, catalyst: { item: 'alfheim:quickened_sparkroot' }, output: { item: 'minecraft:glistering_melon_slice', count: 2 }, aura: 12000, time: 120 }).id(id('emberbound_drawn_heal'))
    event.custom({ type: 'create:splashing', ingredients: [{ item: 'alfheim:emberbound_drawn' }], results: [{ item: 'ars_nouveau:source_gem', count: 3 }] }).id(id('emberbound_drawn_enhance'))

    // Emberbound Folded — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.shapeless('1x minecraft:golden_apple', ['alfheim:emberbound_folded', 'alfheim:quickened_grievebloom']).id(id('emberbound_folded_heal'))
    event.custom({ type: 'create:cutting', ingredients: [{ item: 'alfheim:emberbound_folded' }], results: [{ item: 'naturesaura:aura_cache', count: 1 }], processingTime: 150 }).id(id('emberbound_folded_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:emberbound_folded' }, { item: 'alfheim:emberglass_shard' }], results: [{ item: 'minecraft:blaze_powder', count: 2 }] }).id(id('emberbound_folded_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:emberbound_folded' }, { item: 'alfheim:emberbound_folded' }, { item: 'alfheim:emberbound_folded' }, { item: 'alfheim:emberbound_folded' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:emberbound_stilled', count: 1 } }).id(id('emberbound_folded_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_palebloom' }, { item: 'alfheim:emberbound_folded' }], results: [{ item: 'minecraft:iron_ingot', count: 2 }] }).id(id('emberbound_folded_mult'))

    // Emberbound Stilled — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_verdigris' }, catalyst: { item: 'alfheim:emberbound_stilled' }, output: { item: 'minecraft:copper_ingot', count: 3 }, aura: 12000, time: 120 }).id(id('emberbound_stilled_mult'))
    event.shapeless('3x minecraft:glistering_melon_slice', ['alfheim:emberbound_stilled', 'minecraft:melon_slice']).id(id('emberbound_stilled_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:emberbound_stilled' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('emberbound_stilled_heal'))

    // Emberbound Rebound — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:emberbound_rebound' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:emberbound_quenched', count: 1 }, aura: 30000, time: 200 }).id(id('emberbound_rebound_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:emberbound_rebound' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('emberbound_rebound_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:emberbound_rebound' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('emberbound_rebound_food'))
    event.shapeless('2x minecraft:glistering_melon_slice', ['alfheim:emberbound_rebound', 'alfheim:quickened_sparkroot']).id(id('emberbound_rebound_heal'))
    event.custom({ type: 'create:sandpaper_polishing', ingredients: [{ item: 'alfheim:emberbound_rebound' }], results: [{ item: 'botania:white_petal', count: 6 }] }).id(id('emberbound_rebound_enhance'))

    // Emberbound Quenched — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_silverthorn' }, { item: 'alfheim:emberbound_quenched' }], results: [{ item: 'occultism:silver_ingot', count: 2 }] }).id(id('emberbound_quenched_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:emberbound_quenched' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('emberbound_quenched_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:emberbound_quenched' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('emberbound_quenched_heal'))

    // Emberbound Weave — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.shapeless('2x minecraft:diamond', ['alfheim:quickened_rimebloom', 'alfheim:emberbound_weave']).id(id('emberbound_weave_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:emberbound_weave' }, { item: 'minecraft:apple' }], results: [{ item: 'minecraft:golden_apple', count: 1 }] }).id(id('emberbound_weave_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:emberbound_weave' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('emberbound_weave_heal'))
    event.custom({ type: 'ars_nouveau:crush', input: { item: 'alfheim:emberbound_weave' }, output: [{ item: 'alfheim:dawnglass_shard', count: 2, chance: 1.0, maxRange: 1 }], skip_block_place: false }).id(id('emberbound_weave_enhance'))

    // ---------------------------------------------- Era 8
    // Frost Shard — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:frost_shard' }, catalyst: { item: 'alfheim:duskglass_shard' }, output: { item: 'minecraft:gunpowder', count: 3 }, aura: 12000, time: 120 }).id(id('frost_shard_reagent'))
    event.shapeless('alfheim:silvered_flake', ['4x alfheim:frost_shard', 'botania:mana_powder']).id(id('frost_shard_shortcut'))
    event.shapeless('2x botania:elementium_ingot', ['mythicbotany:raw_elementium', 'alfheim:frost_shard']).id(id('frost_shard_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:frost_shard' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('frost_shard_food'))

    // Silvered Flake — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'botania:mana_infusion', input: { item: 'alfheim:silvered_flake' }, mana: 1200, output: { item: 'alfheim:galeglass_shard', count: 2 } }).id(id('silvered_flake_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:silvered_flake' }, { item: 'alfheim:tidewake_shard' }], results: [{ item: 'minecraft:redstone', count: 4 }] }).id(id('silvered_flake_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:silvered_flake' }, { item: 'alfheim:silvered_flake' }, { item: 'alfheim:silvered_flake' }, { item: 'alfheim:silvered_flake' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:archive_leaf', count: 1 }] }).id(id('silvered_flake_shortcut'))

    // Archive Leaf — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_palebloom' }, catalyst: { item: 'alfheim:archive_leaf' }, output: { item: 'minecraft:iron_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('archive_leaf_mult'))
    event.shapeless('2x minecraft:golden_carrot', ['alfheim:archive_leaf', 'farmersdelight:pumpkin_slice']).id(id('archive_leaf_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:archive_leaf' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('archive_leaf_heal'))

    // Rime Cord — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:rime_cord' }, { item: 'alfheim:rime_cord' }, { item: 'alfheim:rime_cord' }, { item: 'alfheim:rime_cord' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:lattice_blank', count: 1 } }).id(id('rime_cord_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:rime_cord' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('rime_cord_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rime_cord' }, catalyst: { item: 'minecraft:bread' }, output: { item: 'minecraft:golden_carrot', count: 1 }, aura: 12000, time: 120 }).id(id('rime_cord_food'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:rime_cord', 'alfheim:quickened_grievebloom']).id(id('rime_cord_heal'))
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:rime_cord' }], results: [{ item: 'botania:mana_powder', count: 4 }], processingTime: 150 }).id(id('rime_cord_enhance'))

    // Lattice Blank — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:lattice_blank' }, { item: 'alfheim:rootglass_shard' }], results: [{ item: 'minecraft:glowstone_dust', count: 2 }] }).id(id('lattice_blank_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:lattice_blank' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:sealed_lattice', count: 1 }, aura: 30000, time: 200 }).id(id('lattice_blank_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:lattice_blank' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('lattice_blank_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:lattice_blank' }, catalyst: { item: 'minecraft:apple' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('lattice_blank_food'))

    // Sealed Lattice — 4 uses: edible, restorative, enhancer, reagent
    event.shapeless('3x minecraft:glistering_melon_slice', ['alfheim:sealed_lattice', 'minecraft:melon_slice']).id(id('sealed_lattice_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:sealed_lattice' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('sealed_lattice_heal'))
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:sealed_lattice' }], results: [{ item: 'ars_nouveau:source_gem', count: 3 }], processingTime: 150 }).id(id('sealed_lattice_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:sealed_lattice' }, { item: 'alfheim:quickened_cinderbloom' }], results: [{ item: 'minecraft:torch', count: 8 }] }).id(id('sealed_lattice_reagent'))

    // Rimebound Drawn — 4 uses: edible, restorative, enhancer, reagent
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_drawn' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('rimebound_drawn_food'))
    event.shapeless('2x minecraft:glistering_melon_slice', ['alfheim:rimebound_drawn', 'alfheim:quickened_sparkroot']).id(id('rimebound_drawn_heal'))
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:rimebound_drawn' }], results: [{ item: 'naturesaura:aura_cache', count: 1 }] }).id(id('rimebound_drawn_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:rimebound_drawn' }, { item: 'alfheim:quickened_duskbloom' }], results: [{ item: 'ars_nouveau:source_gem', count: 2 }] }).id(id('rimebound_drawn_reagent'))

    // Rimebound Folded — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.shapeless('alfheim:rimebound_stilled', ['4x alfheim:rimebound_folded', 'botania:mana_powder']).id(id('rimebound_folded_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_silverthorn' }, { item: 'alfheim:rimebound_folded' }], results: [{ item: 'occultism:silver_ingot', count: 2 }] }).id(id('rimebound_folded_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_folded' }, catalyst: { item: 'minecraft:bread' }, output: { item: 'minecraft:golden_carrot', count: 1 }, aura: 12000, time: 120 }).id(id('rimebound_folded_food'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:rimebound_folded', 'alfheim:quickened_grievebloom']).id(id('rimebound_folded_heal'))
    event.custom({ type: 'create:haunting', ingredients: [{ item: 'alfheim:rimebound_folded' }], results: [{ item: 'botania:white_petal', count: 6 }] }).id(id('rimebound_folded_enhance'))

    // Rimebound Stilled — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:rimebound_stilled' }, { item: 'alfheim:quickened_cloudglass' }], results: [{ item: 'minecraft:glass', count: 4 }] }).id(id('rimebound_stilled_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:rimebound_stilled' }, { item: 'alfheim:rimebound_stilled' }, { item: 'alfheim:rimebound_stilled' }, { item: 'alfheim:rimebound_stilled' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:rimebound_rebound', count: 1 }] }).id(id('rimebound_stilled_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_rimebloom' }, { item: 'alfheim:rimebound_stilled' }], results: [{ item: 'minecraft:diamond', count: 2 }] }).id(id('rimebound_stilled_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_stilled' }, catalyst: { item: 'minecraft:apple' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('rimebound_stilled_food'))

    // Rimebound Rebound — 4 uses: edible, restorative, enhancer, reagent
    event.shapeless('3x minecraft:glistering_melon_slice', ['alfheim:rimebound_rebound', 'minecraft:melon_slice']).id(id('rimebound_rebound_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:rimebound_rebound' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('rimebound_rebound_heal'))
    event.custom({ type: 'create:splashing', ingredients: [{ item: 'alfheim:rimebound_rebound' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }] }).id(id('rimebound_rebound_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:rimebound_rebound' }, { item: 'alfheim:quickened_emberwake' }], results: [{ item: 'minecraft:magma_cream', count: 2 }] }).id(id('rimebound_rebound_reagent'))

    // Rimebound Quenched — 4 uses: edible, restorative, enhancer, reagent
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_quenched' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('rimebound_quenched_food'))
    event.shapeless('2x minecraft:glistering_melon_slice', ['alfheim:rimebound_quenched', 'alfheim:quickened_sparkroot']).id(id('rimebound_quenched_heal'))
    event.custom({ type: 'create:cutting', ingredients: [{ item: 'alfheim:rimebound_quenched' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }], processingTime: 150 }).id(id('rimebound_quenched_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:rimebound_quenched' }, { item: 'alfheim:quickened_farbloom' }], results: [{ item: 'minecraft:ender_eye', count: 1 }] }).id(id('rimebound_quenched_reagent'))

    // Rimebound Layered — 4 uses: edible, restorative, enhancer, reagent
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:rimebound_layered' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('rimebound_layered_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_layered' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('rimebound_layered_heal'))
    event.custom({ type: 'create:sandpaper_polishing', ingredients: [{ item: 'alfheim:rimebound_layered' }], results: [{ item: 'botania:mana_powder', count: 4 }] }).id(id('rimebound_layered_enhance'))
    event.shapeless('2x minecraft:blaze_powder', ['alfheim:rimebound_layered', 'alfheim:emberglass_shard']).id(id('rimebound_layered_reagent'))

    // Rimebound Lattice — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:rimebound_lattice' }, { item: 'alfheim:duskglass_shard' }], results: [{ item: 'minecraft:gunpowder', count: 3 }] }).id(id('rimebound_lattice_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:rimebound_lattice' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('rimebound_lattice_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:rimebound_lattice' }, catalyst: { item: 'minecraft:apple' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('rimebound_lattice_food'))

    // ---------------------------------------------- Era 9
    // Ash Of Names — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:ash_of_names' }, { item: 'alfheim:ash_of_names' }, { item: 'alfheim:ash_of_names' }, { item: 'alfheim:ash_of_names' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:mourning_dust', count: 1 } }).id(id('ash_of_names_shortcut'))
    event.shapeless('2x minecraft:iron_ingot', ['alfheim:quickened_palebloom', 'alfheim:ash_of_names']).id(id('ash_of_names_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:ash_of_names' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('ash_of_names_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:ash_of_names' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('ash_of_names_heal'))
    event.custom({ type: 'ars_nouveau:crush', input: { item: 'alfheim:ash_of_names' }, output: [{ item: 'ars_nouveau:source_gem', count: 3, chance: 1.0, maxRange: 1 }], skip_block_place: false }).id(id('ash_of_names_enhance'))

    // Mourning Dust — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:mourning_dust' }, catalyst: { item: 'alfheim:quickened_sparkroot' }, output: { item: 'minecraft:glistering_melon_slice', count: 2 }, aura: 12000, time: 120 }).id(id('mourning_dust_heal'))
    event.custom({ type: 'botania:mana_infusion', input: { item: 'alfheim:mourning_dust' }, mana: 1200, output: { item: 'naturesaura:aura_cache', count: 1 } }).id(id('mourning_dust_enhance'))
    event.shapeless('4x minecraft:redstone', ['alfheim:mourning_dust', 'alfheim:tidewake_shard']).id(id('mourning_dust_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:mourning_dust' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:gilded_ash', count: 1 }, aura: 30000, time: 200 }).id(id('mourning_dust_shortcut'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:mourning_dust' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('mourning_dust_mult'))

    // Gilded Ash — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:gilded_ash' }], results: [{ item: 'botania:white_petal', count: 6 }], processingTime: 150 }).id(id('gilded_ash_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gilded_ash' }, { item: 'alfheim:rootglass_shard' }], results: [{ item: 'minecraft:glowstone_dust', count: 2 }] }).id(id('gilded_ash_reagent'))
    event.shapeless('alfheim:debt_cord', ['4x alfheim:gilded_ash', 'botania:mana_powder']).id(id('gilded_ash_shortcut'))

    // Debt Cord — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:debt_cord' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('debt_cord_heal'))
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:debt_cord' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }], processingTime: 150 }).id(id('debt_cord_enhance'))
    event.shapeless('8x minecraft:torch', ['alfheim:debt_cord', 'alfheim:quickened_cinderbloom']).id(id('debt_cord_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:debt_cord' }, { item: 'alfheim:debt_cord' }, { item: 'alfheim:debt_cord' }, { item: 'alfheim:debt_cord' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:reckoned_thread', count: 1 }] }).id(id('debt_cord_shortcut'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:debt_cord' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('debt_cord_mult'))

    // Reckoned Thread — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_silverthorn' }, { item: 'alfheim:reckoned_thread' }], results: [{ item: 'occultism:silver_ingot', count: 2 }] }).id(id('reckoned_thread_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:reckoned_thread' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('reckoned_thread_food'))
    event.shapeless('4x minecraft:golden_carrot', ['alfheim:reckoned_thread', 'botania:mana_powder']).id(id('reckoned_thread_heal'))

    // Grave Braid — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:grave_braid' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }] }).id(id('grave_braid_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:grave_braid' }, { item: 'alfheim:quickened_duskbloom' }], results: [{ item: 'ars_nouveau:source_gem', count: 2 }] }).id(id('grave_braid_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:grave_braid' }, { item: 'alfheim:grave_braid' }, { item: 'alfheim:grave_braid' }, { item: 'alfheim:grave_braid' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:settled_thread', count: 1 } }).id(id('grave_braid_shortcut'))

    // Settled Thread — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:settled_thread' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:gravegilt_drawn', count: 1 }, aura: 30000, time: 200 }).id(id('settled_thread_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_rimebloom' }, { item: 'alfheim:settled_thread' }], results: [{ item: 'minecraft:diamond', count: 2 }] }).id(id('settled_thread_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:settled_thread' }, catalyst: { item: 'minecraft:bread' }, output: { item: 'minecraft:golden_carrot', count: 1 }, aura: 12000, time: 120 }).id(id('settled_thread_food'))
    event.shapeless('2x minecraft:glistering_melon_slice', ['alfheim:settled_thread', 'alfheim:quickened_sparkroot']).id(id('settled_thread_heal'))
    event.custom({ type: 'create:haunting', ingredients: [{ item: 'alfheim:settled_thread' }], results: [{ item: 'botania:mana_powder', count: 4 }] }).id(id('settled_thread_enhance'))

    // Gravegilt Drawn — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:gravegilt_drawn' }, { item: 'alfheim:quickened_cloudglass' }], results: [{ item: 'minecraft:glass', count: 4 }] }).id(id('gravegilt_drawn_reagent'))
    event.shapeless('alfheim:gravegilt_folded', ['4x alfheim:gravegilt_drawn', 'botania:mana_powder']).id(id('gravegilt_drawn_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:gravegilt_drawn' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('gravegilt_drawn_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gravegilt_drawn' }, catalyst: { item: 'minecraft:apple' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('gravegilt_drawn_food'))

    // Gravegilt Folded — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.shapeless('1x minecraft:golden_apple', ['alfheim:gravegilt_folded', 'alfheim:quickened_grievebloom']).id(id('gravegilt_folded_heal'))
    event.custom({ type: 'create:splashing', ingredients: [{ item: 'alfheim:gravegilt_folded' }], results: [{ item: 'ars_nouveau:source_gem', count: 3 }] }).id(id('gravegilt_folded_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:gravegilt_folded' }, { item: 'alfheim:quickened_emberwake' }], results: [{ item: 'minecraft:magma_cream', count: 2 }] }).id(id('gravegilt_folded_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gravegilt_folded' }, { item: 'alfheim:gravegilt_folded' }, { item: 'alfheim:gravegilt_folded' }, { item: 'alfheim:gravegilt_folded' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:gravegilt_stilled', count: 1 }] }).id(id('gravegilt_folded_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_palebloom' }, { item: 'alfheim:gravegilt_folded' }], results: [{ item: 'minecraft:iron_ingot', count: 2 }] }).id(id('gravegilt_folded_mult'))

    // Gravegilt Stilled — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:gravegilt_stilled' }, { item: 'alfheim:gravegilt_stilled' }, { item: 'alfheim:gravegilt_stilled' }, { item: 'alfheim:gravegilt_stilled' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:gravegilt_rebound', count: 1 } }).id(id('gravegilt_stilled_shortcut'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_verdigris' }, catalyst: { item: 'alfheim:gravegilt_stilled' }, output: { item: 'minecraft:copper_ingot', count: 3 }, aura: 12000, time: 120 }).id(id('gravegilt_stilled_mult'))
    event.shapeless('3x minecraft:glistering_melon_slice', ['alfheim:gravegilt_stilled', 'minecraft:melon_slice']).id(id('gravegilt_stilled_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:gravegilt_stilled' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('gravegilt_stilled_heal'))
    event.custom({ type: 'create:cutting', ingredients: [{ item: 'alfheim:gravegilt_stilled' }], results: [{ item: 'naturesaura:aura_cache', count: 1 }], processingTime: 150 }).id(id('gravegilt_stilled_enhance'))

    // Gravegilt Rebound — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gravegilt_rebound' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:gravegilt_quenched', count: 1 }, aura: 30000, time: 200 }).id(id('gravegilt_rebound_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:gravegilt_rebound' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('gravegilt_rebound_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gravegilt_rebound' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('gravegilt_rebound_food'))
    event.shapeless('2x minecraft:glistering_melon_slice', ['alfheim:gravegilt_rebound', 'alfheim:quickened_sparkroot']).id(id('gravegilt_rebound_heal'))
    event.custom({ type: 'create:sandpaper_polishing', ingredients: [{ item: 'alfheim:gravegilt_rebound' }], results: [{ item: 'botania:white_petal', count: 6 }] }).id(id('gravegilt_rebound_enhance'))

    // Gravegilt Quenched — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_silverthorn' }, { item: 'alfheim:gravegilt_quenched' }], results: [{ item: 'occultism:silver_ingot', count: 2 }] }).id(id('gravegilt_quenched_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gravegilt_quenched' }, { item: 'minecraft:bread' }], results: [{ item: 'minecraft:golden_carrot', count: 1 }] }).id(id('gravegilt_quenched_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gravegilt_quenched' }, catalyst: { item: 'alfheim:quickened_grievebloom' }, output: { item: 'minecraft:golden_apple', count: 1 }, aura: 12000, time: 120 }).id(id('gravegilt_quenched_heal'))

    // Gravegilt Layered — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'ars_nouveau:crush', input: { item: 'alfheim:gravegilt_layered' }, output: [{ item: 'alfheim:dawnglass_shard', count: 2, chance: 1.0, maxRange: 1 }], skip_block_place: false }).id(id('gravegilt_layered_enhance'))
    event.shapeless('1x minecraft:ender_eye', ['alfheim:gravegilt_layered', 'alfheim:quickened_farbloom']).id(id('gravegilt_layered_reagent'))
    event.shapeless('alfheim:gravegilt_proofed', ['4x alfheim:gravegilt_layered', 'botania:mana_powder']).id(id('gravegilt_layered_shortcut'))

    // Gravegilt Proofed — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gravegilt_proofed' }, { item: 'alfheim:gravegilt_proofed' }, { item: 'alfheim:gravegilt_proofed' }, { item: 'alfheim:gravegilt_proofed' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:gravegilt_thread', count: 1 }] }).id(id('gravegilt_proofed_shortcut'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:quickened_rimebloom' }, { item: 'alfheim:gravegilt_proofed' }], results: [{ item: 'minecraft:diamond', count: 2 }] }).id(id('gravegilt_proofed_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gravegilt_proofed' }, { item: 'minecraft:apple' }], results: [{ item: 'minecraft:golden_apple', count: 1 }] }).id(id('gravegilt_proofed_food'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:gravegilt_proofed' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'minecraft:golden_carrot', count: 4 }, aura: 12000, time: 120 }).id(id('gravegilt_proofed_heal'))
    event.custom({ type: 'botania:mana_infusion', input: { item: 'alfheim:gravegilt_proofed' }, mana: 1200, output: { item: 'alfheim:galeglass_shard', count: 2 } }).id(id('gravegilt_proofed_enhance'))

    // Grave-Gilt Thread — 4 uses: reagent, shortcut, multiplier, edible
    event.shapeless('2x minecraft:blaze_powder', ['alfheim:gravegilt_thread', 'alfheim:emberglass_shard']).id(id('gravegilt_thread_reagent'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'mythicbotany:raw_elementium' }, { item: 'alfheim:gravegilt_thread' }], results: [{ item: 'botania:elementium_ingot', count: 2 }] }).id(id('gravegilt_thread_mult'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:gravegilt_thread' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('gravegilt_thread_food'))

    // ---------------------------------------------- Era 10
    // Heartwood Strand — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:heartwood_strand' }], results: [{ item: 'botania:mana_powder', count: 4 }], processingTime: 150 }).id(id('heartwood_strand_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:heartwood_strand' }, catalyst: { item: 'alfheim:duskglass_shard' }, output: { item: 'minecraft:gunpowder', count: 3 }, aura: 12000, time: 120 }).id(id('heartwood_strand_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:heartwood_strand' }, { item: 'alfheim:heartwood_strand' }, { item: 'alfheim:heartwood_strand' }, { item: 'alfheim:heartwood_strand' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:crowned_fibre', count: 1 } }).id(id('heartwood_strand_shortcut'))

    // Crowned Fibre — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:crowned_fibre' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:yggdrasil_floss', count: 1 }, aura: 30000, time: 200 }).id(id('crowned_fibre_shortcut'))
    event.shapeless('2x minecraft:iron_ingot', ['alfheim:quickened_palebloom', 'alfheim:crowned_fibre']).id(id('crowned_fibre_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crowned_fibre' }, { item: 'farmersdelight:pumpkin_slice' }], results: [{ item: 'minecraft:golden_carrot', count: 2 }] }).id(id('crowned_fibre_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crowned_fibre' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('crowned_fibre_heal'))
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:crowned_fibre' }], results: [{ item: 'ars_nouveau:source_gem', count: 3 }], processingTime: 150 }).id(id('crowned_fibre_enhance'))

    // Yggdrasil Floss — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:yggdrasil_floss' }], results: [{ item: 'naturesaura:aura_cache', count: 1 }] }).id(id('yggdrasil_floss_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:yggdrasil_floss' }, catalyst: { item: 'alfheim:tidewake_shard' }, output: { item: 'minecraft:redstone', count: 4 }, aura: 12000, time: 120 }).id(id('yggdrasil_floss_reagent'))
    event.shapeless('alfheim:branch_cord', ['4x alfheim:yggdrasil_floss', 'botania:mana_powder']).id(id('yggdrasil_floss_shortcut'))

    // Branch Cord — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.shapeless('1x minecraft:golden_apple', ['alfheim:branch_cord', 'alfheim:quickened_grievebloom']).id(id('branch_cord_heal'))
    event.custom({ type: 'create:haunting', ingredients: [{ item: 'alfheim:branch_cord' }], results: [{ item: 'botania:white_petal', count: 6 }] }).id(id('branch_cord_enhance'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:branch_cord' }, { item: 'alfheim:rootglass_shard' }], results: [{ item: 'minecraft:glowstone_dust', count: 2 }] }).id(id('branch_cord_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:branch_cord' }, { item: 'alfheim:branch_cord' }, { item: 'alfheim:branch_cord' }, { item: 'alfheim:branch_cord' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:living_crown', count: 1 }] }).id(id('branch_cord_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:branch_cord' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('branch_cord_mult'))

    // Living Crown — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:living_crown' }, { item: 'alfheim:living_crown' }, { item: 'alfheim:living_crown' }, { item: 'alfheim:living_crown' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:woven_crown', count: 1 } }).id(id('living_crown_shortcut'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_sunbloom' }, catalyst: { item: 'alfheim:living_crown' }, output: { item: 'minecraft:gold_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('living_crown_mult'))
    event.shapeless('1x minecraft:golden_carrot', ['alfheim:living_crown', 'minecraft:bread']).id(id('living_crown_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:living_crown' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('living_crown_heal'))
    event.custom({ type: 'create:splashing', ingredients: [{ item: 'alfheim:living_crown' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }] }).id(id('living_crown_enhance'))

    // Woven Crown — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:woven_crown' }, { item: 'alfheim:quickened_cinderbloom' }], results: [{ item: 'minecraft:torch', count: 8 }] }).id(id('woven_crown_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:woven_crown' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:ninefold_thread', count: 1 }, aura: 30000, time: 200 }).id(id('woven_crown_shortcut'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_silverthorn' }, catalyst: { item: 'alfheim:woven_crown' }, output: { item: 'occultism:silver_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('woven_crown_mult'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:woven_crown', 'minecraft:apple']).id(id('woven_crown_food'))

    // Ninefold Thread — 4 uses: edible, restorative, enhancer, reagent
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:ninefold_thread' }, { item: 'minecraft:melon_slice' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 3 }] }).id(id('ninefold_thread_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:ninefold_thread' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('ninefold_thread_heal'))
    event.custom({ type: 'create:cutting', ingredients: [{ item: 'alfheim:ninefold_thread' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }], processingTime: 150 }).id(id('ninefold_thread_enhance'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:ninefold_thread' }, catalyst: { item: 'alfheim:quickened_duskbloom' }, output: { item: 'ars_nouveau:source_gem', count: 2 }, aura: 12000, time: 120 }).id(id('ninefold_thread_reagent'))

    // Crown Blank — 5 uses: shortcut, multiplier, edible, restorative, enhancer
    event.shapeless('alfheim:crown_drawn', ['4x alfheim:crown_blank', 'botania:mana_powder']).id(id('crown_blank_shortcut'))
    event.shapeless('2x minecraft:diamond', ['alfheim:quickened_rimebloom', 'alfheim:crown_blank']).id(id('crown_blank_mult'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_blank' }, { item: 'farmersdelight:pumpkin_slice' }], results: [{ item: 'minecraft:golden_carrot', count: 2 }] }).id(id('crown_blank_food'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_blank' }, { item: 'alfheim:quickened_grievebloom' }], results: [{ item: 'minecraft:golden_apple', count: 1 }] }).id(id('crown_blank_heal'))
    event.custom({ type: 'create:sandpaper_polishing', ingredients: [{ item: 'alfheim:crown_blank' }], results: [{ item: 'botania:mana_powder', count: 4 }] }).id(id('crown_blank_enhance'))

    // Crown Drawn — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'naturesaura:altar', input: { item: 'mythicbotany:raw_elementium' }, catalyst: { item: 'alfheim:crown_drawn' }, output: { item: 'botania:elementium_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('crown_drawn_mult'))
    event.shapeless('1x minecraft:golden_carrot', ['alfheim:crown_drawn', 'minecraft:bread']).id(id('crown_drawn_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_drawn' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('crown_drawn_heal'))

    // Crown Folded — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'ars_nouveau:crush', input: { item: 'alfheim:crown_folded' }, output: [{ item: 'ars_nouveau:source_gem', count: 3, chance: 1.0, maxRange: 1 }], skip_block_place: false }).id(id('crown_folded_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_folded' }, { item: 'alfheim:quickened_cloudglass' }], results: [{ item: 'minecraft:glass', count: 4 }] }).id(id('crown_folded_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_folded' }, { item: 'alfheim:crown_folded' }, { item: 'alfheim:crown_folded' }, { item: 'alfheim:crown_folded' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:crown_stilled', count: 1 }] }).id(id('crown_folded_shortcut'))

    // Crown Stilled — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_palebloom' }, catalyst: { item: 'alfheim:crown_stilled' }, output: { item: 'minecraft:iron_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('crown_stilled_mult'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:crown_stilled', 'minecraft:apple']).id(id('crown_stilled_food'))
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_stilled' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('crown_stilled_heal'))

    // Crown Rebound — 3 uses: multiplier, edible, restorative
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_verdigris' }, { item: 'alfheim:crown_rebound' }], results: [{ item: 'minecraft:copper_ingot', count: 3 }] }).id(id('crown_rebound_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:crown_rebound' }, catalyst: { item: 'minecraft:melon_slice' }, output: { item: 'minecraft:glistering_melon_slice', count: 3 }, aura: 12000, time: 120 }).id(id('crown_rebound_food'))
    event.shapeless('1x minecraft:golden_apple', ['alfheim:crown_rebound', 'alfheim:quickened_grievebloom']).id(id('crown_rebound_heal'))

    // Crown Quenched — 4 uses: reagent, shortcut, multiplier, edible
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_quenched' }, { item: 'alfheim:quickened_emberwake' }], results: [{ item: 'minecraft:magma_cream', count: 2 }] }).id(id('crown_quenched_reagent'))
    event.custom({ type: 'botania:runic_altar', ingredients: [{ item: 'alfheim:crown_quenched' }, { item: 'alfheim:crown_quenched' }, { item: 'alfheim:crown_quenched' }, { item: 'alfheim:crown_quenched' }, { item: 'botania:mana_powder' }], mana: 3000, output: { item: 'alfheim:crown_layered', count: 1 } }).id(id('crown_quenched_shortcut'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:quickened_sunbloom' }, { item: 'alfheim:crown_quenched' }], results: [{ item: 'minecraft:gold_ingot', count: 2 }] }).id(id('crown_quenched_mult'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:crown_quenched' }, catalyst: { item: 'farmersdelight:pumpkin_slice' }, output: { item: 'minecraft:golden_carrot', count: 2 }, aura: 12000, time: 120 }).id(id('crown_quenched_food'))

    // Crown Layered — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'botania:mana_infusion', input: { item: 'alfheim:crown_layered' }, mana: 1200, output: { item: 'naturesaura:aura_cache', count: 1 } }).id(id('crown_layered_enhance'))
    event.shapeless('1x minecraft:ender_eye', ['alfheim:crown_layered', 'alfheim:quickened_farbloom']).id(id('crown_layered_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:crown_layered' }, catalyst: { item: 'botania:mana_powder' }, output: { item: 'alfheim:crown_proofed', count: 1 }, aura: 30000, time: 200 }).id(id('crown_layered_shortcut'))

    // Crown Proofed — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_proofed' }, { item: 'botania:mana_powder' }], results: [{ item: 'minecraft:golden_carrot', count: 4 }] }).id(id('crown_proofed_heal'))
    event.custom({ type: 'create:crushing', ingredients: [{ item: 'alfheim:crown_proofed' }], results: [{ item: 'botania:white_petal', count: 6 }], processingTime: 150 }).id(id('crown_proofed_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_proofed' }, { item: 'alfheim:emberglass_shard' }], results: [{ item: 'minecraft:blaze_powder', count: 2 }] }).id(id('crown_proofed_reagent'))
    event.shapeless('alfheim:crown_settled', ['4x alfheim:crown_proofed', 'botania:mana_powder']).id(id('crown_proofed_shortcut'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_silverthorn' }, catalyst: { item: 'alfheim:crown_proofed' }, output: { item: 'occultism:silver_ingot', count: 2 }, aura: 12000, time: 120 }).id(id('crown_proofed_mult'))

    // Crown Settled — 3 uses: enhancer, reagent, shortcut
    event.custom({ type: 'create:milling', ingredients: [{ item: 'alfheim:crown_settled' }], results: [{ item: 'alfheim:dawnglass_shard', count: 2 }], processingTime: 150 }).id(id('crown_settled_enhance'))
    event.shapeless('3x minecraft:gunpowder', ['alfheim:crown_settled', 'alfheim:duskglass_shard']).id(id('crown_settled_reagent'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_settled' }, { item: 'alfheim:crown_settled' }, { item: 'alfheim:crown_settled' }, { item: 'alfheim:crown_settled' }, { item: 'botania:mana_powder' }], results: [{ item: 'alfheim:crown_filament', count: 1 }] }).id(id('crown_settled_shortcut'))

    // Crown Filament — 5 uses: restorative, enhancer, reagent, shortcut, multiplier
    event.custom({ type: 'create:deploying', ingredients: [{ item: 'alfheim:crown_filament' }, { item: 'alfheim:quickened_sparkroot' }], results: [{ item: 'minecraft:glistering_melon_slice', count: 2 }] }).id(id('crown_filament_heal'))
    event.custom({ type: 'create:pressing', ingredients: [{ item: 'alfheim:crown_filament' }], results: [{ item: 'alfheim:galeglass_shard', count: 2 }] }).id(id('crown_filament_enhance'))
    event.custom({ type: 'create:mixing', ingredients: [{ item: 'alfheim:crown_filament' }, { item: 'alfheim:tidewake_shard' }], results: [{ item: 'minecraft:redstone', count: 4 }] }).id(id('crown_filament_reagent'))
    event.custom({ type: 'naturesaura:altar', input: { item: 'alfheim:quickened_rimebloom' }, catalyst: { item: 'alfheim:crown_filament' }, output: { item: 'minecraft:diamond', count: 2 }, aura: 12000, time: 120 }).id(id('crown_filament_mult'))

    console.info('[Alfheim Reclaimed] item uses loaded (286 recipes).')
})
