// Alfheim Reclaimed — crystallised mana
//
// GENERATED by tools/gen_crystals.py from tools/crystals_manifest.json — do not hand-edit.
// Design: alfheim_reclaimed_design/ORE_SUPPLEMENTATION.md §9
//
// Where the ley-lines ran hardest the mana separated by alignment and set as gem.
// A geode is never one crystal: it is the boundary between two.

StartupEvents.registry('block', event => {
    event.create('alfheim:emberglass_block').displayName('Emberglass Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/emberglass_block')
    event.create('alfheim:budding_emberglass').displayName('Budding Emberglass').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_emberglass').randomTick(ctx => growCluster(ctx, 'alfheim:emberglass_cluster'))
    event.create('alfheim:emberglass_cluster').displayName('Emberglass Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/emberglass_cluster')
    event.create('alfheim:tidewake_block').displayName('Tidewake Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/tidewake_block')
    event.create('alfheim:budding_tidewake').displayName('Budding Tidewake').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_tidewake').randomTick(ctx => growCluster(ctx, 'alfheim:tidewake_cluster'))
    event.create('alfheim:tidewake_cluster').displayName('Tidewake Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/tidewake_cluster')
    event.create('alfheim:rootglass_block').displayName('Rootglass Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/rootglass_block')
    event.create('alfheim:budding_rootglass').displayName('Budding Rootglass').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_rootglass').randomTick(ctx => growCluster(ctx, 'alfheim:rootglass_cluster'))
    event.create('alfheim:rootglass_cluster').displayName('Rootglass Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/rootglass_cluster')
    event.create('alfheim:galeglass_block').displayName('Galeglass Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/galeglass_block')
    event.create('alfheim:budding_galeglass').displayName('Budding Galeglass').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_galeglass').randomTick(ctx => growCluster(ctx, 'alfheim:galeglass_cluster'))
    event.create('alfheim:galeglass_cluster').displayName('Galeglass Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/galeglass_cluster')
    event.create('alfheim:duskglass_block').displayName('Duskglass Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/duskglass_block')
    event.create('alfheim:budding_duskglass').displayName('Budding Duskglass').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_duskglass').randomTick(ctx => growCluster(ctx, 'alfheim:duskglass_cluster'))
    event.create('alfheim:duskglass_cluster').displayName('Duskglass Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/duskglass_cluster')
    event.create('alfheim:dawnglass_block').displayName('Dawnglass Block').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_blocks').textureAll('alfheim:block/dawnglass_block')
    event.create('alfheim:budding_dawnglass').displayName('Budding Dawnglass').soundType('amethyst').hardness(1.5).resistance(1.5).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:budding_crystals').textureAll('alfheim:block/budding_dawnglass').randomTick(ctx => growCluster(ctx, 'alfheim:dawnglass_cluster'))
    event.create('alfheim:dawnglass_cluster').displayName('Dawnglass Cluster').soundType('amethyst_cluster').hardness(1.5).resistance(1.5).requiresTool(true).defaultCutout().notSolid().lightLevel(0.4).tagBlock('minecraft:mineable/pickaxe').tagBlock('alfheim:crystal_clusters').model('alfheim:block/dawnglass_cluster')
})

StartupEvents.registry('item', event => {
    event.create('alfheim:emberglass_shard').displayName('Emberglass Shard').tooltip('Mana that set while it was still burning.').rarity('uncommon').tag('alfheim:crystal_shards')
    event.create('alfheim:tidewake_shard').displayName('Tidewake Shard').tooltip('Cold, and it rings when struck.').rarity('uncommon').tag('alfheim:crystal_shards')
    event.create('alfheim:rootglass_shard').displayName('Rootglass Shard').tooltip('It grew downward, the way roots do.').rarity('uncommon').tag('alfheim:crystal_shards')
    event.create('alfheim:galeglass_shard').displayName('Galeglass Shard').tooltip('Almost not there. Lighter than it looks.').rarity('uncommon').tag('alfheim:crystal_shards')
    event.create('alfheim:duskglass_shard').displayName('Duskglass Shard').tooltip('It takes light in and does not give it back.').rarity('uncommon').tag('alfheim:crystal_shards')
    event.create('alfheim:dawnglass_shard').displayName('Dawnglass Shard').tooltip('The last of the ley-light, kept whole.').rarity('uncommon').tag('alfheim:crystal_shards')
})

// Vanilla grows amethyst through BuddingAmethystBlock in Java. KubeJS 2001.6.5 has no
// binding for that, but it does expose randomTick with a BlockContainerJS, which is
// enough: pick a face, and if it is air, put a cluster there. Slower than vanilla by
// design — a 1-in-5 roll per random tick per face.
function growCluster(ctx, clusterId) {
    if (ctx.random.nextFloat() > 0.2) return
    const faces = ['up', 'down', 'north', 'south', 'east', 'west']
    const face = faces[ctx.random.nextInt(faces.length)]
    const target = ctx.block.offset(face)
    if (target.id !== 'minecraft:air') return
    target.set(clusterId, { facing: face })
}
