# GENERATED by tools/gen_royal_tileset_wave_a.py
# Run only in a disposable review area: /function alfheim:royal_tileset_wave_a/review
say [Alfheim] placing Royal Tile Set I Wave A review grid
setblock ~0 ~ ~0 alfheim:royal_highback_chair[facing=north]
setblock ~3 ~ ~0 alfheim:royal_wall_sconce[facing=north]
setblock ~6 ~ ~0 alfheim:royal_carpet_runner[facing=north]
setblock ~9 ~ ~0 alfheim:royal_balustrade[facing=north]
setblock ~12 ~ ~0 alfheim:royal_lidded_amphora[facing=north]
setblock ~15 ~ ~0 alfheim:royal_wall_banner[facing=north]
# 2x3 canopy bed
setblock ~0 ~ ~5 alfheim:royal_canopy_bed_head_left[facing=north]
setblock ~1 ~ ~5 alfheim:royal_canopy_bed_head_right[facing=north]
setblock ~0 ~ ~6 alfheim:royal_canopy_bed_middle_left[facing=north]
setblock ~1 ~ ~6 alfheim:royal_canopy_bed_middle_right[facing=north]
setblock ~0 ~ ~7 alfheim:royal_canopy_bed_foot_left[facing=north]
setblock ~1 ~ ~7 alfheim:royal_canopy_bed_foot_right[facing=north]
# 2x2 astrolabe
setblock ~5 ~ ~5 alfheim:royal_astrolabe_nw[facing=north]
setblock ~6 ~ ~5 alfheim:royal_astrolabe_ne[facing=north]
setblock ~5 ~ ~6 alfheim:royal_astrolabe_sw[facing=north]
setblock ~6 ~ ~6 alfheim:royal_astrolabe_se[facing=north]
say [Alfheim] Wave A grid placed; inspect geometry, collision, facing and seams
