
#Feywild General Config
[feywild]
	#The duration in ticks for the levitation effect applied by fey dust. (Minimum: 1)
	#Range: 1 ~ 100
	fey_dust_duration = 30
	#Whether players should spawn with a Feywild Lexicon
	spawn_with_lexicon = true
	#Whether fey should have voice acting on
	voices_active = true
	#Attack damage of Tree Ents
	#Range: 0.0 ~ 30.0
	tree_ent_attack_damage = 12.0
	#Chance for Tree Ent logs to be cracked when grown from a sapling. 1 in N chance
	#Range: 1 ~ 10000
	tree_ent_spawn_sapling = 1200
	#Chance for Tree Ent logs to be cracked when spawned naturally in world. 1 in N chance
	#Range: 1 ~ 10000
	tree_ent_spawn_world = 100
	#Whether Tree Ents should attack players
	tree_ent_attack_players = true

