// Alfheim Reclaimed — the Hollow Court at spawn
//
// GENERATED by tools/gen_hollow_court.py — do not hand-edit.
//
// Places the surviving court around the player's anchored landing spot in Alfheim, and the
// sealed gate face beside it.
//
// ---------------------------------------------------------------------------------------------
// WHY THE SUMMON NBT LOOKS LIKE THIS. Read before simplifying it.
//
// richs_races_wood_elves:wood_elf is not a villager. WoodElfEntity extends Monster, implements
// RangedAttackMob, and its NearestAttackableTargetGoal list includes Player — these are hostile
// archers that happen to be elves. Four flags make one an NPC:
//
//   NoAI:1b               no targeting, no wandering, no despawn — the whole problem in one flag
//   PersistenceRequired:1b belt and braces; a named mob already resists despawn
//   Invulnerable:1b       a quest giver a creeper can delete is a quest line the player loses
//   Silent:1b             they are standing in a ruin, not grunting in one
//
// CustomName is load-bearing, not decoration: quest_giver's QuestLinkManager matches a link by
// entity type AND custom name, so the name in quest_line_links.json and the name summoned here
// must agree exactly. They are generated from one roster so they cannot drift.
//
// NoAI mobs do not walk down onto terrain, so each one gets a livingrock plinth set under its
// feet first. That is cheaper than trusting an 8-block offset to land at the same height, and it
// reads as intentional — a court standing on what is left of its own floor.
// ---------------------------------------------------------------------------------------------

const COURT_DIMENSION = 'mythicbotany:alfheim'
const ELF = 'richs_races_wood_elves:wood_elf'

// World-scoped, not player-scoped. The court belongs to the world; placing it per player would
// give a second player a second Velrous standing in the first one's shoulder.
const COURT_FLAG = 'alfheim_hollow_court_v1'

// Long enough to be after 02_spawn_dimension.js has teleported, spread and verified the player.
// If that has not finished, we do not know where the court belongs yet.
const PLACE_DELAY = 60

const NAMED = [
    { name: 'Magister Velrous', dx: 3, dz: -2, line: 'the_reclaiming' },
    { name: 'Captain Orenvel', dx: -3, dz: -2, line: 'the_royal_guard' }
]

const AMBIENT = [
    { name: 'Sethyr the Quiet', dx: 6, dz: 4 },
    { name: 'Loremistress Anwe', dx: -6, dz: 4 },
    { name: 'Faelan Ashbound', dx: 7, dz: -5 },
    { name: 'Nyre of the Boughs', dx: -7, dz: -5 },
    { name: 'Warden Ilesh', dx: 0, dz: 7 },
    { name: 'Cinder-Sister Vaal', dx: 0, dz: -8 }
]

const NBT = "{NoAI:1b,PersistenceRequired:1b,Invulnerable:1b,Silent:1b," +
            "CustomNameVisible:1b,CustomName:'{\"text\":\"%NAME%\"}'}"

// `@e` is scoped to the execution dimension, so this counts one named elf in Alfheim using
// nothing but vanilla commands — the same idiom 02_spawn_dimension.js uses to test a dimension.
function exists(server, name) {
    try {
        return server.runCommandSilent(
            `execute in ${COURT_DIMENSION} if entity @e[type=${ELF},name="${name}",limit=1]`
        ) > 0
    } catch (e) {
        console.warn(`[Alfheim Reclaimed] could not query for ${name}: ${e}`)
        return false
    }
}

function place(server, name, x, y, z) {
    if (exists(server, name)) return true          // idempotent: never a second Velrous
    server.runCommandSilent(
        `execute in ${COURT_DIMENSION} run setblock ${x} ${y - 1} ${z} botania:livingrock keep`)
    server.runCommandSilent(
        `execute in ${COURT_DIMENSION} run summon ${ELF} ${x} ${y} ${z} ` +
        NBT.replace('%NAME%', name))
    // Ask, do not assume. A summon that silently failed and was recorded as success is exactly
    // the B-44 mistake, and it would leave a quest line with no one to give it.
    if (exists(server, name)) return true
    console.warn(`[Alfheim Reclaimed] summon of "${name}" at ${x} ${y} ${z} did not take.`)
    return false
}

// A 2x3 gate face in a livingrock surround, a few blocks in front of the court. Small enough to
// place with setblock rather than a structure, which the Greatbole does not yet exist to provide.
function placeGate(server, x, y, z) {
    for (let dy = -1; dy <= 3; dy++) {
        for (let dx = -2; dx <= 2; dx++) {
            const edge = (dy === -1 || dy === 3 || dx === -2 || dx === 2)
            const block = edge ? 'botania:livingrock' : 'alfheim:sealed_gate'
            server.runCommandSilent(
                `execute in ${COURT_DIMENSION} run setblock ${x + dx} ${y + dy} ${z} ${block}`)
        }
    }
}

// Audit only, by default. The court is seated INSIDE court/amphitheatre.nbt, so on any world
// where the Greatbole generated, these elves already exist in the right place — on the tiers,
// in front of the gate, where SPAWN_HUB.md puts them.
//
// This function used to summon them at the player's landing spot. That was correct when it was
// written and is wrong now: 02_spawn_dimension.js spreads the player up to 2000 blocks from the
// origin, and the hub generates at the origin, so summoning here would build a SECOND court in
// an empty field — with the same names, which means quest_giver would bind quest lines to
// whichever one the player reached first. A duplicate Velrous is worse than a missing one.
//
// So the fallback is off unless someone deliberately turns it on, and it says where it is
// putting them when they do.
const FALLBACK_SUMMON_AT_PLAYER = false

function auditCourt(server, player) {
    if (server.persistentData.getBoolean(COURT_FLAG)) return

    const roster = NAMED.concat(AMBIENT)
    const missing = roster.filter(n => !exists(server, n.name))

    if (missing.length === 0) {
        server.persistentData.putBoolean(COURT_FLAG, true)
        console.info(`[Alfheim Reclaimed] Hollow Court present — ${roster.length} elves. ` +
                     'Velrous and Orenvel give quests to a player holding a Quest Scroll.')
        return
    }

    if (!FALLBACK_SUMMON_AT_PLAYER) {
        console.warn(
            `[Alfheim Reclaimed] Hollow Court: ${missing.length}/${roster.length} missing ` +
            `(${missing.map(n => n.name).join(', ')}). They are seated inside ` +
            'court/amphitheatre.nbt, so this normally means the Greatbole has not generated ' +
            'or its chunks are not loaded. Walk to the hub, or set FALLBACK_SUMMON_AT_PLAYER ' +
            'to place a stand-in court here — which will NOT be at the amphitheatre.')
        return
    }

    const x = Math.floor(player.x), y = Math.floor(player.y), z = Math.floor(player.z)
    let placed = 0
    NAMED.forEach(n => { if (place(server, n.name, x + n.dx, y, z + n.dz)) placed++ })
    AMBIENT.forEach(n => { if (place(server, n.name, x + n.dx, y, z + n.dz)) placed++ })
    placeGate(server, x, y, z - 9)
    console.warn(`[Alfheim Reclaimed] FALLBACK: ${placed} elves placed at ${x} ${y} ${z}, ` +
                 'away from the amphitheatre. Flag left clear deliberately.')
}

PlayerEvents.loggedIn(event => {
    const server = event.server
    if (server.persistentData.getBoolean(COURT_FLAG)) return
    try {
        server.scheduleInTicks(PLACE_DELAY, () => auditCourt(server, event.player))
    } catch (e) {
        console.warn('[Alfheim Reclaimed] scheduleInTicks unavailable, auditing court now: ' + e)
        auditCourt(server, event.player)
    }
})
