// Alfheim Reclaimed — the expedition gate
//
// GENERATED by tools/gen_hollow_court.py — do not hand-edit.
//
// See BACKLOG B-57. The Map Device was one diamond and one stone; expeditions were the
// cheapest capability in the pack and touched no spine at all.

ServerEvents.recipes(event => {
    const id = s => `alfheim:gate/${s}`

    // Out: diamond over stone at a crafting table.
    event.remove({ id: 'dungeon_realm:map_device' })

    // In: the Runic Altar, which means mana, which means a working spreader and pool. The
    // Guard surveyed with elven instruments; so do you.
    event.custom({
        type: 'botania:runic_altar',
        ingredients: [
            { item: 'minecraft:diamond' },
            { item: 'botania:livingrock' },
            { item: 'botania:dreamwood' },
            { item: 'alfheim:dawnglass_shard' },
            { tag: 'botania:petals/yellow' }
        ],
        mana: 15000,
        output: { item: 'dungeon_realm:map_device', count: 1 }
    }).id(id('map_device'))

    console.info('[Alfheim Reclaimed] expedition gate: Map Device re-laid on the Runic Altar.')
})
