// Alfheim Reclaimed — crystal drops
// GENERATED by tools/gen_crystals.py — do not hand-edit.
ServerEvents.blockLootTables(event => {
    event.addSimpleBlock('alfheim:emberglass_block')
    event.addSimpleBlock('alfheim:emberglass_cluster', Item.of('alfheim:emberglass_shard', 4))
    event.addSimpleBlock('alfheim:tidewake_block')
    event.addSimpleBlock('alfheim:tidewake_cluster', Item.of('alfheim:tidewake_shard', 4))
    event.addSimpleBlock('alfheim:rootglass_block')
    event.addSimpleBlock('alfheim:rootglass_cluster', Item.of('alfheim:rootglass_shard', 4))
    event.addSimpleBlock('alfheim:galeglass_block')
    event.addSimpleBlock('alfheim:galeglass_cluster', Item.of('alfheim:galeglass_shard', 4))
    event.addSimpleBlock('alfheim:duskglass_block')
    event.addSimpleBlock('alfheim:duskglass_cluster', Item.of('alfheim:duskglass_shard', 4))
    event.addSimpleBlock('alfheim:dawnglass_block')
    event.addSimpleBlock('alfheim:dawnglass_cluster', Item.of('alfheim:dawnglass_shard', 4))

    console.info('[Alfheim Reclaimed] 6 crystal loot sets registered.')
})
