// Alfheim Reclaimed — the Mine and Slash bridge
//
// GENERATED by tools/gen_mmo_bridge.py — do not hand-edit.
//
// INSTRUCTIONS.md §2.2: the Wound is not a side system. Until this file, Mine and
// Slash's economy and the material curve were two separate games in one world —
// orbs dropped from mobs, bought gear, and never touched anything a spine produced.
//
// Outward: crystal shards buy adventuring currency. Inward: expedition loot pays out
// in Alfheim materials, so a map run supplies the base instead of interrupting it.
//
// Every conversion runs through a SPINE STATION, never a crafting table. §2.3: a
// shapeless recipe here would let a player turn loot into materials without ever
// building a mana economy, which is the bypass the doctrine exists to prevent.

ServerEvents.recipes(event => {
    const id = s => `alfheim:mmo/${s}`

    // -------------------------------------------------- outward: shards -> currency
    // 4x emberglass shard -> currency/chaos_orb   [Runic Altar]
    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:emberglass_shard' }, { item: 'alfheim:emberglass_shard' }, { item: 'alfheim:emberglass_shard' }, { item: 'alfheim:emberglass_shard' }], mana: 12000,
        output: { item: 'mmorpg:currency/chaos_orb', count: 1 } })
        .id(id('emberglass_to_currency/chaos_orb'))

    // 4x duskglass shard -> currency/orb_of_relief   [Runic Altar]
    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:duskglass_shard' }, { item: 'alfheim:duskglass_shard' }, { item: 'alfheim:duskglass_shard' }, { item: 'alfheim:duskglass_shard' }], mana: 12000,
        output: { item: 'mmorpg:currency/orb_of_relief', count: 1 } })
        .id(id('duskglass_to_currency/orb_of_relief'))

    // 6x tidewake shard -> currency/orb_of_quality   [Runic Altar]
    event.custom({ type: 'botania:runic_altar',
        ingredients: [{ item: 'alfheim:tidewake_shard' }, { item: 'alfheim:tidewake_shard' }, { item: 'alfheim:tidewake_shard' }, { item: 'alfheim:tidewake_shard' }, { item: 'alfheim:tidewake_shard' }, { item: 'alfheim:tidewake_shard' }], mana: 16000,
        output: { item: 'mmorpg:currency/orb_of_quality', count: 1 } })
        .id(id('tidewake_to_currency/orb_of_quality'))

    // 6x galeglass shard -> currency/gear_rarity_upgrade   [Mana Pool]
    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:galeglass_shard' }, mana: 96000,
        output: { item: 'mmorpg:currency/gear_rarity_upgrade', count: 1 } })
        .id(id('galeglass_to_currency/gear_rarity_upgrade'))

    // 8x rootglass shard -> currency/perfected_soul_seed   [Mana Pool]
    event.custom({ type: 'botania:mana_infusion',
        input: { item: 'alfheim:rootglass_shard' }, mana: 160000,
        output: { item: 'mmorpg:currency/perfected_soul_seed', count: 1 } })
        .id(id('rootglass_to_currency/perfected_soul_seed'))

    // 8x dawnglass shard -> currency/level_up_orb   [Mana Infuser]
    event.custom({ type: 'mythicbotany:infuser',
        group: 'alfheim_mmo_bridge',
        ingredients: [{ item: 'alfheim:dawnglass_shard' }, { item: 'alfheim:dawnglass_shard' }, { item: 'alfheim:dawnglass_shard' }, { item: 'alfheim:dawnglass_shard' }], mana: 96000,
        fromColor: 8388736, toColor: 16777130,
        output: { item: 'mmorpg:currency/level_up_orb', count: 1 } })
        .id(id('dawnglass_to_currency/level_up_orb'))

    // -------------------------------------------------- inward: loot -> materials
    // 2x currency/harvest_essence_1 -> 4x quickened_palebloom   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:currency/harvest_essence_1' }],
        pedestalItems: [{ item: 'mmorpg:currency/harvest_essence_1' }, { item: 'mmorpg:currency/harvest_essence_1' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:quickened_palebloom', count: 4 },
        sourceCost: 1500, keepNbtOfReagent: false })
        .id(id('currency/harvest_essence_1_to_quickened_palebloom'))

    // 2x currency/harvest_essence_1 -> 4x quickened_verdigris   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:currency/harvest_essence_1' }],
        pedestalItems: [{ item: 'mmorpg:currency/harvest_essence_1' }, { item: 'mmorpg:currency/harvest_essence_1' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:quickened_verdigris', count: 4 },
        sourceCost: 1500, keepNbtOfReagent: false })
        .id(id('currency/harvest_essence_1_to_quickened_verdigris'))

    // 2x mob_effects/essence_of_frost -> 2x quickened_rimebloom   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:mob_effects/essence_of_frost' }],
        pedestalItems: [{ item: 'mmorpg:mob_effects/essence_of_frost' }, { item: 'mmorpg:mob_effects/essence_of_frost' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:quickened_rimebloom', count: 2 },
        sourceCost: 2000, keepNbtOfReagent: false })
        .id(id('mob_effects/essence_of_frost_to_quickened_rimebloom'))

    // 1x currency/harvest_essence_4 -> 6x quickened_sunbloom   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:currency/harvest_essence_4' }],
        pedestalItems: [{ item: 'mmorpg:currency/harvest_essence_4' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:quickened_sunbloom', count: 6 },
        sourceCost: 4000, keepNbtOfReagent: false })
        .id(id('currency/harvest_essence_4_to_quickened_sunbloom'))

    // 2x stat_soul -> 3x dawnglass_shard   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:stat_soul' }],
        pedestalItems: [{ item: 'mmorpg:stat_soul' }, { item: 'mmorpg:stat_soul' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:dawnglass_shard', count: 3 },
        sourceCost: 2500, keepNbtOfReagent: false })
        .id(id('stat_soul_to_dawnglass_shard'))

    // 1x currency/chaos_orb -> 3x emberglass_shard   [Enchanting Apparatus]
    event.custom({ type: 'ars_nouveau:enchanting_apparatus',
        reagent: [{ item: 'mmorpg:currency/chaos_orb' }],
        pedestalItems: [{ item: 'mmorpg:currency/chaos_orb' }, { item: 'botania:mana_powder' }],
        output: { item: 'alfheim:emberglass_shard', count: 3 },
        sourceCost: 3000, keepNbtOfReagent: false })
        .id(id('currency/chaos_orb_to_emberglass_shard'))

    console.info('[Alfheim Reclaimed] Mine and Slash bridge loaded (12 conversions).')
})
