// Alfheim Reclaimed — reserve two wood elf skins for the named court
//
// GENERATED by tools/gen_court_skins.py — do not hand-edit.
//
// richs_races_wood_elves picks one of six textures from a synched int, persisted to NBT as
// `DataSkinSwap`, and `WoodElfOnInitialEntitySpawnProcedure` rolls it 1..6 at spawn. Slots
// 5 and 6 carry OUR custom art for the Magister and the Captain, so a wild elf that
// rolled one of them would walk around wearing the Captain's plate.
//
// This forces every naturally spawned elf back into [1, 2, 3, 4]. It runs on spawn rather than
// on a tick: the roll happens once, in finalizeSpawn, so once is enough.
//
// The court itself is NOT affected. Its members are placed by the amphitheatre structure with
// their DataSkinSwap already baked in and NoAI set, so they never pass through a spawn event.
// The NoAI test below is the guard for that, and it is deliberately belt-and-braces — hostile
// wood elves now spawn naturally in five biomes (see gen_alfheim_biomes.py), so this fires
// often and must never touch a court member.

const RESERVED = [5, 6]
const WILD = [1, 2, 3, 4]

EntityEvents.spawned('richs_races_wood_elves:wood_elf', event => {
    const e = event.entity
    if (!e) return
    try {
        const nbt = e.nbt
        if (!nbt) return
        // A court member: placed, not spawned. Leave it exactly as the structure wrote it.
        if (nbt.getBoolean('NoAI')) return
        if (!RESERVED.includes(nbt.getInt('DataSkinSwap'))) return
        e.mergeNbt({ DataSkinSwap: WILD[Math.floor(Math.random() * WILD.length)] })
    } catch (err) {
        console.warn('[Alfheim Reclaimed] wood elf skin reservation failed: ' + err)
    }
})

console.info('[Alfheim Reclaimed] wood elf skins ' + RESERVED.join(' and ') +
             ' reserved for the Hollow Court')
