// Alfheim Reclaimed — Liquid Bifrost, Era 3
//
// GENERATED by tools/gen_liquid_bifrost.py — do not hand-edit.
//
// Tiers 3 and 4, and the conversions into every other magic system.
//
// ERA-SCOPED FILENAME, ON PURPOSE. check_coverage.py reads a recipe's era from `_era<N>_` in
// its filename and can check nothing without it — the chain shipped as one un-scoped
// 17_liquid_bifrost.js and the coverage report said so directly: "24 contributive step(s)
// belong to no era ... they cannot be checked until they are era-scoped". Splitting the chain
// at its own era boundary is also honest about what it is: two tiers before the gate, two
// after.

// THE CHAIN, PART TWO — both steps behind the gate.
//
//   condensed + elf glass     --alfheim infuser-->   refined
//   2x refined + mana pearl   --runic altar------>   distilled
//
// THE CONVERSIONS are deliberately a bad rate. Liquid Bifrost is a bridge between the pack's
// thirteen magic systems (MAGIC_SYSTEMS.md), not a way around any of them — a player who
// builds the chain gets a foothold in a new system, never a shortcut past its early game.

ServerEvents.recipes(event => {

    // ---- tier 3: the impurities out ---------------------------------------------------------
    // MythicBotany's own infuser, which sits behind the gate — so this tier is unreachable
    // until Era III on the spine rather than merely expensive.
    //
    // The type is `mythicbotany:infuser`, NOT `mythicbotany:mana_infusion`. The latter does not
    // exist: MythicBotany ships exactly one recipe type for the Alfheim infuser and it takes an
    // ingredient LIST plus fromColor/toColor for the beam, not a single `input`. Caught by E13
    // against the jars before it ever reached a server.
    event.custom({
        type: 'mythicbotany:infuser',
        group: 'infuser',
        ingredients: [
            { item: 'alfheim:condensed_bifrost' },
            { item: 'botania:elf_glass' },
            { item: 'botania:mana_powder' },
        ],
        output: { item: 'alfheim:refined_bifrost', count: 1 },
        mana: 40000,
        fromColor: 11858175,
        toColor: 10185215,
    }).id('alfheim:refined_bifrost')

    // ---- tier 4: the final form -------------------------------------------------------------
    event.custom({
        type: 'botania:runic_altar',
        ingredients: [
            { item: 'alfheim:refined_bifrost' },
            { item: 'alfheim:refined_bifrost' },
            { item: 'botania:mana_pearl' },
            { item: 'botania:elf_glass' },
        ],
        output: { item: 'alfheim:distilled_bifrost' },
        mana: 20000,
    }).id('alfheim:distilled_bifrost')

    // ---- conversions: one material into every system ----------------------------------------
    // Botania: Mana powder is the cheapest thing mana buys, so this is a starter and not a shortcut.
    event.shapeless(Item.of('botania:mana_powder', 6), ['alfheim:distilled_bifrost']).id('alfheim:bifrost_to_botania_mana_powder')
    // Ars Nouveau: Source gems are the whole economy of Ars; three is one spell, not a spellbook.
    event.shapeless(Item.of('ars_nouveau:source_gem', 3), ['alfheim:distilled_bifrost']).id('alfheim:bifrost_to_ars_nouveau_source_gem')
    // Occultism: The otherworld is the one system that should stay expensive.
    event.shapeless(Item.of('occultism:otherworld_essence', 2), ['alfheim:distilled_bifrost']).id('alfheim:bifrost_to_occultism_otherworld_essence')
    // Iron's Spellbooks
    event.shapeless(Item.of('irons_spellbooks:arcane_essence', 4), ['alfheim:distilled_bifrost']).id('alfheim:bifrost_to_irons_spellbooks_arcane_essence')
    // Nature's Aura: Gold leaf is the aura chain's first consumable.
    event.shapeless(Item.of('naturesaura:gold_leaf', 4), ['alfheim:distilled_bifrost']).id('alfheim:bifrost_to_naturesaura_gold_leaf')
    // Botania (advanced): The one advanced conversion, and it costs four distilled rather than one.
    event.shapeless(Item.of('botania:mana_pearl', 1), ['alfheim:distilled_bifrost', 'alfheim:distilled_bifrost', 'alfheim:distilled_bifrost', 'alfheim:distilled_bifrost']).id('alfheim:bifrost_to_botania_mana_pearl')
})
