// Alfheim Reclaimed — Era 10: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 17 steps (2n-3). Chain consumes the Era 9 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era10/${s}`

    // step 1/17 — apothecary
    {
        event.custom({ type: 'botania:petal_apothecary',
            ingredients: [{ item: 'alfheim:gravegilt_thread' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:heartwood_strand', count: 1 },
            reagent: { tag: 'botania:seed_apothecary_reagent' } })
            .id(id('heartwood_strand'))
    }

    // step 2/17 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:heartwood_strand' }, mana: 12000,
            output: { item: 'alfheim:crowned_fibre' } })
            .id(id('crowned_fibre'))
    }

    // step 3/17 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:crowned_fibre' }, { item: 'botania:livingrock' }], mana: 18000,
            output: { item: 'alfheim:yggdrasil_floss', count: 1 } })
            .id(id('yggdrasil_floss'))
    }

    // step 4/17 — infuser
    {
        event.custom({ type: 'mythicbotany:infuser',
            group: 'alfheim_ladder',
            ingredients: [{ item: 'alfheim:yggdrasil_floss' }], mana: 400000,
            fromColor: 7498291, toColor: 16375077,
            output: { item: 'alfheim:branch_cord' } })
            .id(id('branch_cord'))
    }

    // step 5/17 — terra_plate
    {
        event.custom({ type: 'botania:terra_plate',
            ingredients: [{ item: 'alfheim:branch_cord' }, { item: 'botania:livingrock' }], mana: 250000,
            result: { item: 'alfheim:living_crown' } })
            .id(id('living_crown'))
    }

    // step 6/17 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:living_crown' }],
            pedestalItems: [{ item: 'alfheim:living_crown' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:woven_crown' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('woven_crown'))
    }

    // step 7/17 — imbuement
    {
        event.custom({ type: 'ars_nouveau:imbuement',
            input: { item: 'alfheim:woven_crown' }, count: 1,
            output: 'alfheim:ninefold_thread', source: 3000,
            pedestalItems: [] })
            .id(id('ninefold_thread'))
    }

    // step 8/17 — na_tree
    {
        event.custom({ type: 'naturesaura:tree_ritual',
            sapling: { item: 'minecraft:oak_sapling' },
            ingredients: [{ item: 'alfheim:ninefold_thread' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }, { item: 'naturesaura:gold_leaf' }],
            output: { item: 'alfheim:crown_blank' }, time: 400 })
            .id(id('crown_blank'))
    }

    // step 9/17 — fey_altar
    {
        event.custom({ type: 'feywild:fey_altar',
            ingredients: [{ item: 'alfheim:crown_blank' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }, { item: 'minecraft:gold_ingot' }, { item: 'botania:livingrock' }],
            output: { item: 'alfheim:crown_drawn', count: 1 } })
            .id(id('crown_drawn'))
    }

    // step 10/17 — occ_fire
    {
        event.custom({ type: 'occultism:spirit_fire',
            ingredient: { item: 'alfheim:crown_drawn' },
            result: { item: 'alfheim:crown_folded' } })
            .id(id('crown_folded'))
    }

    // step 11/17 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:crown_folded' }],
            output: [{ item: 'alfheim:crown_stilled' }] })
            .id(id('crown_stilled'))
    }

    // step 12/17 — cr_seq
    {
        event.custom({ type: 'create:sequenced_assembly',
            ingredient: { item: 'alfheim:crown_stilled' },
            transitionalItem: { item: 'alfheim:incomplete_crown_rebound' },
            loops: 2,
            results: [{ item: 'alfheim:crown_rebound', count: 1 }],
            sequence: [
                { type: 'create:deploying',
                    ingredients: [{ item: 'alfheim:incomplete_crown_rebound' }, { item: 'botania:dreamwood' }],
                    keepHeldItem: false,
                    results: [{ item: 'alfheim:incomplete_crown_rebound' }] },
                { type: 'create:pressing',
                    ingredients: [{ item: 'alfheim:incomplete_crown_rebound' }],
                    results: [{ item: 'alfheim:incomplete_crown_rebound' }] }
            ] })
            .id(id('crown_rebound'))
    }

    // step 13/17 — cr_mix
    {
        event.custom({ type: 'create:mixing',
            ingredients: [{ item: 'alfheim:crown_rebound' }, { item: 'botania:livingrock' }],
            results: [{ item: 'alfheim:crown_quenched', count: 1 }] })
            .id(id('crown_quenched'))
    }

    // step 14/17 — crush
    {
        event.custom({ type: 'ars_nouveau:crush',
            input: { item: 'alfheim:crown_quenched' },
            output: [{ item: 'alfheim:crown_layered', count: 1, chance: 1.0, maxRange: 1 }],
            skip_block_place: false })
            .id(id('crown_layered'))
    }

    // step 15/17 — brew
    {
        event.shapeless('alfheim:crown_proofed', ['alfheim:crown_layered', 'botania:livingrock'])
            .id(id('crown_proofed'))
    }

    // step 16/17 — na_altar
    {
        event.custom({ type: 'naturesaura:altar',
            input: { item: 'alfheim:crown_proofed' },
            output: { item: 'alfheim:crown_settled' },
            aura: 30000, time: 200 })
            .id(id('crown_settled'))
    }

    // step 17/17 — craft
    {
        event.shaped('alfheim:crown_filament', ['AB', 'BA'], { A: 'alfheim:crown_settled', B: 'botania:livingrock' })
            .id(id('crown_filament'))
    }

    console.info('[Alfheim Reclaimed] Era 10 tier ladder loaded.')
})
