// Alfheim Reclaimed — Era 4: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 5 steps (2n-3). Chain consumes the Era 3 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era4/${s}`

    // step 1/5 — apothecary
    {
        event.custom({ type: 'botania:petal_apothecary',
            ingredients: [{ item: 'alfheim:verdant_filament' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:sunbleached_floss', count: 1 },
            reagent: { tag: 'botania:seed_apothecary_reagent' } })
            .id(id('sunbleached_floss'))
    }

    // step 2/5 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:sunbleached_floss' }, mana: 12000,
            output: { item: 'alfheim:traded_skein' } })
            .id(id('traded_skein'))
    }

    // step 3/5 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:traded_skein' }],
            output: [{ item: 'alfheim:gatewrought_drawn' }] })
            .id(id('gatewrought_drawn'))
    }

    // step 4/5 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:gatewrought_drawn' }],
            pedestalItems: [{ item: 'alfheim:gatewrought_drawn' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:gatewrought_folded' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('gatewrought_folded'))
    }

    // step 5/5 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:gatewrought_folded' }, { item: 'botania:livingrock' }], mana: 18000,
            output: { item: 'alfheim:gatewrought_cord', count: 1 } })
            .id(id('gatewrought_cord'))
    }

    console.info('[Alfheim Reclaimed] Era 4 tier ladder loaded.')
})
