// Alfheim Reclaimed — Era 5: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 7 steps (2n-3). Chain consumes the Era 4 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era5/${s}`

    // step 1/7 — smelt
    {
        event.smelting('alfheim:raw_alloy_grit', 'alfheim:gatewrought_cord')
            .id(id('raw_alloy_grit'))
    }

    // step 2/7 — cr_mill
    {
        event.custom({ type: 'create:milling',
            ingredients: [{ item: 'alfheim:raw_alloy_grit' }],
            processingTime: 200,
            results: [{ item: 'alfheim:annealed_plate', count: 1 }] })
            .id(id('annealed_plate'))
    }

    // step 3/7 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:annealed_plate' }, mana: 12000,
            output: { item: 'alfheim:core_blank' } })
            .id(id('core_blank'))
    }

    // step 4/7 — infuser
    {
        event.custom({ type: 'mythicbotany:infuser',
            group: 'alfheim_ladder',
            ingredients: [{ item: 'alfheim:core_blank' }], mana: 400000,
            fromColor: 3371592, toColor: 2488684,
            output: { item: 'alfheim:elementium_drawn' } })
            .id(id('elementium_drawn'))
    }

    // step 5/7 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:elementium_drawn' }],
            pedestalItems: [{ item: 'alfheim:elementium_drawn' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:elementium_folded' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('elementium_folded'))
    }

    // step 6/7 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:elementium_folded' }, { item: 'botania:dreamwood' }], mana: 18000,
            output: { item: 'alfheim:elementium_stilled', count: 1 } })
            .id(id('elementium_stilled'))
    }

    // step 7/7 — craft
    {
        event.shaped('alfheim:elementium_core', ['AB', 'BA'], { A: 'alfheim:elementium_stilled', B: 'botania:livingrock' })
            .id(id('elementium_core'))
    }

    console.info('[Alfheim Reclaimed] Era 5 tier ladder loaded.')
})
