// Alfheim Reclaimed — Era 7: tier ladder
//
// GENERATED by tools/gen_ladder.py — do not hand-edit.
// 11 steps (2n-3). Chain consumes the Era 6 tier material, so transitive
// depth accumulates. Stations rotate so each step is a different process.

ServerEvents.recipes(event => {
    const id = s => `alfheim:era7/${s}`

    // step 1/11 — occ_fire
    {
        event.custom({ type: 'occultism:spirit_fire',
            ingredient: { item: 'alfheim:wildmarch_sinew' },
            result: { item: 'alfheim:scorched_filament' } })
            .id(id('scorched_filament'))
    }

    // step 2/11 — cr_mix
    {
        event.custom({ type: 'create:mixing',
            ingredients: [{ item: 'alfheim:scorched_filament' }, { item: 'botania:dreamwood' }],
            results: [{ item: 'alfheim:quenched_thread', count: 1 }] })
            .id(id('quenched_thread'))
    }

    // step 3/11 — smelt
    {
        event.smelting('alfheim:ember_lattice', 'alfheim:quenched_thread')
            .id(id('ember_lattice'))
    }

    // step 4/11 — brew
    {
        event.shapeless('alfheim:bound_weave', ['alfheim:ember_lattice', 'botania:dreamwood'])
            .id(id('bound_weave'))
    }

    // step 5/11 — mana_pool
    {
        event.custom({ type: 'botania:mana_infusion',
            input: { item: 'alfheim:bound_weave' }, mana: 12000,
            output: { item: 'alfheim:tempered_weave' } })
            .id(id('tempered_weave'))
    }

    // step 6/11 — apparatus
    {
        event.custom({ type: 'ars_nouveau:enchanting_apparatus',
            reagent: [{ item: 'alfheim:tempered_weave' }],
            pedestalItems: [{ item: 'alfheim:tempered_weave' }, { item: 'botania:dreamwood' }, { item: 'botania:dreamwood' }],
            output: { item: 'alfheim:emberbound_drawn' },
            sourceCost: 2000, keepNbtOfReagent: false })
            .id(id('emberbound_drawn'))
    }

    // step 7/11 — na_tree
    {
        event.custom({ type: 'naturesaura:tree_ritual',
            sapling: { item: 'minecraft:oak_sapling' },
            ingredients: [{ item: 'alfheim:emberbound_drawn' }, { item: 'botania:livingrock' }, { item: 'botania:dreamwood' }, { item: 'naturesaura:gold_leaf' }],
            output: { item: 'alfheim:emberbound_folded' }, time: 400 })
            .id(id('emberbound_folded'))
    }

    // step 8/11 — gate
    {
        event.custom({ type: 'botania:elven_trade',
            ingredients: [{ item: 'alfheim:emberbound_folded' }],
            output: [{ item: 'alfheim:emberbound_stilled' }] })
            .id(id('emberbound_stilled'))
    }

    // step 9/11 — runic_altar
    {
        event.custom({ type: 'botania:runic_altar',
            ingredients: [{ item: 'alfheim:emberbound_stilled' }, { item: 'botania:livingrock' }], mana: 18000,
            output: { item: 'alfheim:emberbound_rebound', count: 1 } })
            .id(id('emberbound_rebound'))
    }

    // step 10/11 — infuser
    {
        event.custom({ type: 'mythicbotany:infuser',
            group: 'alfheim_ladder',
            ingredients: [{ item: 'alfheim:emberbound_rebound' }], mana: 400000,
            fromColor: 7488307, toColor: 16341541,
            output: { item: 'alfheim:emberbound_quenched' } })
            .id(id('emberbound_quenched'))
    }

    // step 11/11 — craft
    {
        event.shaped('alfheim:emberbound_weave', ['AB', 'BA'], { A: 'alfheim:emberbound_quenched', B: 'botania:livingrock' })
            .id(id('emberbound_weave'))
    }

    console.info('[Alfheim Reclaimed] Era 7 tier ladder loaded.')
})
