package com.continuityworks.alfheimgolems.order;

public enum FailureReason {
    NONE,
    WORK_DISABLED,
    INVALID_ORDER,
    SOURCE_MISSING,
    SOURCE_EMPTY,
    DESTINATION_MISSING,
    DESTINATION_FULL,
    ENDPOINT_UNLOADED,
    PATH_BLOCKED,
    PERMISSION_DENIED,
    UNSUPPORTED_MACHINE,
    RECIPE_MISSING,
    INGREDIENTS_MISSING,
    GOLEM_INVENTORY_FULL,
    OWNER_UNAVAILABLE,
    STALE_REQUEST,
    INTERNAL_ERROR
}
