# GENERATED by tools/gen_functional_elven_containers.py
say [Alfheim] placing functional elven container gallery
setblock ~0 ~ ~0 alfheim_leyworks:manna_stone_storage[facing=north]
setblock ~3 ~ ~0 alfheim_leyworks:royal_chest[facing=north]
setblock ~6 ~ ~0 alfheim_leyworks:gemstone_coffer[facing=north]
setblock ~9 ~ ~0 alfheim_leyworks:dreamwood_crate[facing=north]
setblock ~12 ~ ~0 alfheim_leyworks:provision_crate[facing=north]
setblock ~15 ~ ~0 alfheim_leyworks:scroll_crate[facing=north]
setblock ~18 ~ ~0 alfheim_leyworks:tall_vase[facing=north]
setblock ~21 ~ ~0 alfheim_leyworks:memorial_urn[facing=north]
say [Alfheim] container gallery placed; inspect and open every block
