"""Static pre-check for Alfheim, the home dimension: what generates, and what is missing.

Alfheim is `mythicbotany:alfheim` -- the dimension MythicBotany ships -- and the player spawns
there. `minecraft:overworld` is Midgard and is left vanilla. There is no world-preset override
any more; this resolves the chain the game actually walks, dimension -> biome source -> biome
layer -> biomes, plus every Forge biome modifier that adds features to them, across our
datapack, the mod jars and the vanilla client jar. It reports:

  W1  every biome named by the layer has a definition somewhere
  W2  every placed_feature a biome or modifier references actually exists
  W3  every biome tag a modifier targets resolves to at least one biome
  W4  the materials the early eras need are generated by something
  W5  template pool elements name real pieces and real processor lists
  W6  the home dimension exists and is actually backed by the layer we edit

W2 is the check that matters most: an unresolvable placed_feature is what crashed world
generation 625 chunks out (BACKLOG B-33), and it is invisible at spawn.

    python tools/check_worldgen.py
    python tools/check_worldgen.py --verbose
"""
import argparse
import glob
import json
import os
import re
import zipfile

CLIENT_JAR = (r'C:\Users\Admin\curseforge\minecraft\Install\versions'
              r'\1.20.1\1.20.1.jar')
DATA = os.path.join('kubejs', 'data')
LAYER = os.path.join(DATA, 'mythicbotany', 'libx', 'biome_layer', 'alfheim.json')

# The home dimension. Alfheim is the mod's own dimension, not the Overworld slot -- the
# Overworld is Midgard and is left vanilla. WORLD_STRUCTURE.md §1.
HOME_DIMENSION = 'mythicbotany:alfheim'
HOME_NS, HOME_PATH = HOME_DIMENSION.split(':', 1)
LAYER_TAG = '#mythicbotany:alfheim'

# What the opening eras cannot be completed without. Era I's quest chain asks for a Mana
# Spreader (copper), an iron ingot and a Manasteel ingot (iron); torches and smelting need
# coal or a charcoal route. See BACKLOG B-25.
#
# These name the **base ingredient**, not an ore block. Alfheim ships no vanilla ore at all
# since the Twelve Blooms replaced that layer on 2026-09-03 -- checking for
# `minecraft:copper_ore` would now fail on a world that is perfectly playable, and would pass
# on one where the ore generates but nothing can process it. What has to hold is that a
# material is *reachable*, so the check walks the route:
#
#     <bloom>_ore generates  ->  raw_<bloom> (loot)  ->  quickened_<bloom> (a Rite)
#                            ->  renders.item
#
# See alfheim_reclaimed_design/ORE_SUPPLEMENTATION.md §7 step 6.
EARLY_ESSENTIALS = {
    'minecraft:copper_ingot': 'Era I -- botania:mana_spreader needs a copper ingot',
    'minecraft:iron_ingot': 'Era I -- iron ingot quest, and manasteel is infused iron',
    'minecraft:coal': 'Era I -- torches and smelting',
}

BLOOMS_MANIFEST = os.path.join('tools', 'blooms_manifest.json')


def bloom_routes():
    """Base ingredient -> (ore block, bloom id, era). Empty if the manifest is absent."""
    try:
        m = json.load(open(BLOOMS_MANIFEST, encoding='utf-8'))
    except Exception:
        return {}
    return {b['renders']['item']: (f"alfheim:{b['id']}_ore", b['id'], b['era'])
            for b in m.get('blooms', [])}


# --------------------------------------------------------------------------- sources

class Sources:
    """Every place a datapack file can come from, datapack first."""

    def __init__(self):
        self.jars = []
        for p in sorted(glob.glob(os.path.join('mods', '*.jar'))) + [CLIENT_JAR]:
            if not os.path.exists(p):
                continue
            try:
                self.jars.append((os.path.basename(p), zipfile.ZipFile(p)))
            except Exception:
                continue

    def read(self, rel):
        local = os.path.join(DATA, rel.replace('/', os.sep))
        if os.path.exists(local):
            return json.load(open(local, encoding='utf-8')), 'datapack'
        for name, z in self.jars:
            full = 'data/' + rel
            try:
                return json.loads(z.read(full).decode('utf-8', 'replace')), name
            except KeyError:
                continue
            except Exception:
                continue
        return None, None

    def read_all(self, rel):
        """Every source that ships this path -- tags merge rather than override."""
        out = []
        local = os.path.join(DATA, rel.replace('/', os.sep))
        if os.path.exists(local):
            try:
                out.append((json.load(open(local, encoding='utf-8')), 'datapack'))
            except Exception:
                pass
        for name, z in self.jars:
            try:
                out.append((json.loads(z.read('data/' + rel).decode('utf-8', 'replace')), name))
            except KeyError:
                continue
            except Exception:
                continue
        return out

    def list_datapack(self, pattern):
        return sorted(glob.glob(os.path.join(DATA, pattern), recursive=True))

    def exists(self, rel):
        if os.path.exists(os.path.join(DATA, rel.replace('/', os.sep))):
            return True
        full = 'data/' + rel
        return any(full in z.namelist() for _, z in self.jars)


def split(rid):
    return rid.split(':', 1) if ':' in rid else ('minecraft', rid)


def resolve_biome_tag(src, tag, seen=None):
    """Biome ids behind a #tag, merging every source and following nested tags."""
    seen = seen or set()
    if tag in seen:
        return set()
    seen.add(tag)
    ns, path = split(tag)
    out = set()
    for doc, _ in src.read_all(f'{ns}/tags/worldgen/biome/{path}.json'):
        for v in doc.get('values', []):
            v = v['id'] if isinstance(v, dict) else v
            if v.startswith('#'):
                out |= resolve_biome_tag(src, v[1:], seen)
            else:
                out.add(v)
    return out


def biome_features(doc):
    out = []
    for step in doc.get('features', []) or []:
        for f in step:
            if isinstance(f, str):
                out.append(f)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--verbose', action='store_true')
    a = ap.parse_args()

    src = Sources()
    problems = []

    def fail(code, msg):
        problems.append((code, msg))
        print(f'  {code:3} {msg}')

    print('=== Alfheim worldgen ===\n')

    # W6 -- the home dimension must exist and must be backed by the layer this tool checks.
    # Everything below validates that layer; if the dimension does not actually read it, a clean
    # run means nothing. This also catches the old world_preset override coming back.
    dim, dim_src = src.read(f'{HOME_NS}/dimension/{HOME_PATH}.json')
    if dim is None:
        fail('W6', f'home dimension {HOME_DIMENSION} has no definition')
    else:
        source = dim.get('generator', {}).get('biome_source', {})
        layers = source.get('layers')
        if layers != LAYER_TAG:
            fail('W6', f'{HOME_DIMENSION} biome_source layers is {layers!r}, '
                       f'expected {LAYER_TAG!r} -- this tool is checking a layer the '
                       f'dimension does not use')
        else:
            print(f'home dimension: {HOME_DIMENSION} [{dim_src}] -> {LAYER_TAG}')

    stale = os.path.join(DATA, 'minecraft', 'worldgen', 'world_preset', 'normal.json')
    if os.path.exists(stale):
        fail('W6', 'the Overworld world_preset override is back at '
                   f'{stale} -- Alfheim no longer occupies the Overworld slot')

    layer = json.load(open(LAYER, encoding='utf-8'))
    biomes = []
    for e in layer['biomes']:
        if e['biome'] not in biomes:
            biomes.append(e['biome'])
    print(f'biome layer: {len(layer["biomes"])} entries, {len(biomes)} distinct biomes')

    # W1 -- every biome resolves, and collect its own features
    own = {}
    for b in biomes:
        ns, path = split(b)
        doc, where = src.read(f'{ns}/worldgen/biome/{path}.json')
        if doc is None:
            fail('W1', f'biome {b} has no definition in the datapack or any jar')
            continue
        own[b] = (biome_features(doc), where)

    # W9 -- field-review identity contracts. These are intentionally exact enough to catch a
    # generator regression that quietly restores the dense vanilla ocean or an Overworld-looking
    # Scorchfell, while leaving the tuning values easy to change deliberately in one place.
    print('\n--- field-review identity contracts ---')
    ocean, _ = src.read('alfheim/worldgen/biome/alfheim_ocean.json')
    expected_ocean = {
        'alfheim:ocean_coral_sparse', 'alfheim:ocean_seagrass_sparse',
        'alfheim:ocean_pickle_sparse', 'alfheim:ocean_kelp_sparse',
    }
    ocean_vegetation = set((ocean or {}).get('features', [[], [], [], [], [], [], [], [], [], []])[9])
    if ocean_vegetation != expected_ocean:
        fail('W9', f'Alfheim Ocean vegetation is {sorted(ocean_vegetation)!r}, expected the '
                   f'four sparse wrappers {sorted(expected_ocean)!r}')
    else:
        print('  OK   ocean uses four sparse vegetation wrappers')

    sparse_contracts = {
        'ocean_coral_sparse': ('rarity_filter', 5),
        'ocean_kelp_sparse': ('rarity_filter', 3),
        'ocean_pickle_sparse': ('rarity_filter', 32),
        'ocean_seagrass_sparse': ('count', 6),
    }
    for name, (kind, value) in sparse_contracts.items():
        placed, _ = src.read(f'alfheim/worldgen/placed_feature/{name}.json')
        mods = (placed or {}).get('placement', [])
        got = next((m.get('chance' if kind == 'rarity_filter' else 'count') for m in mods
                    if m.get('type') == f'minecraft:{kind}'), None)
        if got != value:
            fail('W9', f'{name} {kind} is {got!r}, expected {value}')

    lang_path = os.path.join('kubejs', 'assets', 'alfheim', 'lang', 'en_us.json')
    try:
        lang = json.load(open(lang_path, encoding='utf-8'))
    except Exception as e:
        lang = {}
        fail('W9', f'Alfheim language file does not parse: {e}')
    if lang.get('biome.alfheim.alfheim_ocean') != 'Alfheim Ocean':
        fail('W9', 'Alfheim Ocean is missing its player-facing English name')
    else:
        print('  OK   ocean player-facing name is Alfheim Ocean')

    scorch, _ = src.read('alfheim/worldgen/biome/scorchfell.json')
    scorch_features = set(biome_features(scorch or {}))
    for needed in ('alfheim:scorchfell_lava_pool', 'alfheim:scorchfell_lava_seep'):
        if needed not in scorch_features:
            fail('W9', f'Scorchfell is missing {needed}')
    surface, _ = src.read('mythicbotany/libx/surface_rule_set/alfheim_surface.json')
    surface_text = json.dumps(surface or {}, sort_keys=True)
    native_scorch = {
        'alfheim:magmatic_livingrock', 'alfheim:embervein_livingrock',
        'alfheim:cinder_livingrock', 'alfheim:obsidian_livingrock',
        'alfheim:cracked_livingrock',
    }
    absent_native = sorted(block for block in native_scorch if block not in surface_text)
    if absent_native:
        fail('W9', f'Scorchfell surface is missing native blocks {absent_native!r}')
    else:
        print('  OK   Scorchfell surface and lava features use the native flame palette')

    # Forge biome modifiers, from our datapack and from every jar.
    modifiers = []
    for p in src.list_datapack(os.path.join('*', 'forge', 'biome_modifier', '*.json')):
        ns = os.path.relpath(p, DATA).split(os.sep)[0]
        modifiers.append((f'{ns}:{os.path.basename(p)[:-5]}', json.load(open(p, encoding='utf-8')),
                          'datapack'))
    for name, z in src.jars:
        for e in z.namelist():
            m = re.match(r'data/([^/]+)/forge/biome_modifier/(.+)\.json$', e)
            if not m:
                continue
            try:
                modifiers.append((f'{m.group(1)}:{m.group(2)}',
                                  json.loads(z.read(e).decode('utf-8', 'replace')), name))
            except Exception:
                continue
    print(f'biome modifiers found: {len(modifiers)}')

    # Which of them add features to our biomes.
    added = {b: [] for b in own}
    for mid, doc, where in modifiers:
        if doc.get('type') not in ('forge:add_features',):
            continue
        target = doc.get('biomes')
        targets = set()
        for t in ([target] if isinstance(target, str) else list(target or [])):
            if t.startswith('#'):
                got = resolve_biome_tag(src, t[1:])
                if not got and where == 'datapack':
                    fail('W3', f'modifier {mid} targets {t}, which resolves to no biome')
                targets |= got
            else:
                targets.add(t)
        feats = doc.get('features')
        feats = [feats] if isinstance(feats, str) else list(feats or [])
        for b in own:
            if b in targets:
                added[b].extend(feats)

    # W2 -- every referenced placed_feature exists.
    checked = {}

    def placed_exists(fid):
        if fid in checked:
            return checked[fid]
        if fid.startswith('#'):
            checked[fid] = True
            return True
        ns, path = split(fid)
        checked[fid] = src.exists(f'{ns}/worldgen/placed_feature/{path}.json')
        return checked[fid]

    for b in sorted(own):
        for fid in own[b][0] + added[b]:
            if not placed_exists(fid):
                fail('W2', f'{b} references placed_feature {fid}, which nothing ships')

    # W5 -- template pools we override must point at real pieces and real processor lists.
    # A pool element naming a missing .nbt or a missing processor list does not crash: the
    # structure just stops generating, which is invisible until someone goes looking.
    for p in src.list_datapack(os.path.join('**', 'worldgen', 'template_pool', '**', '*.json')):
        rel = os.path.relpath(p, DATA).replace(os.sep, '/')
        try:
            doc = json.load(open(p, encoding='utf-8'))
        except Exception as e:
            fail('W5', f'{rel} does not parse: {e}')
            continue
        for el in doc.get('elements', []):
            e = el.get('element', {})
            loc = e.get('location')
            if loc:
                lns, lpath = split(loc)
                if not src.exists(f'{lns}/structures/{lpath}.nbt'):
                    fail('W5', f'{rel} names piece {loc}, which no jar or datapack ships')
            proc = e.get('processors')
            if isinstance(proc, str) and proc != 'minecraft:empty':
                pns, ppath = split(proc)
                if not src.exists(f'{pns}/worldgen/processor_list/{ppath}.json'):
                    fail('W5', f'{rel} uses processor list {proc}, which does not exist')

    # W4 -- what actually generates.
    print('\n--- ore and material coverage ---')
    produced = {}
    for b in sorted(own):
        for fid in own[b][0] + added[b]:
            ns, path = split(fid)
            doc, _ = src.read(f'{ns}/worldgen/placed_feature/{path}.json')
            if not doc:
                continue
            cfid = doc.get('feature')
            if not isinstance(cfid, str):
                continue
            cns, cpath = split(cfid)
            cdoc, _ = src.read(f'{cns}/worldgen/configured_feature/{cpath}.json')
            if not cdoc or cdoc.get('type') != 'minecraft:ore':
                continue
            for t in cdoc.get('config', {}).get('targets', []):
                blk = t.get('state', {}).get('Name')
                if blk:
                    produced.setdefault(blk, set()).add(b)

    for blk in sorted(produced):
        print(f'  {blk:42} {len(produced[blk]):2} biome(s)')

    # W8 -- the climate partition must be disjoint, and every biome must actually get a band.
    #
    # Runtime-proven 2026-09-04: a player explored a fresh world and saw ONLY MythicBotany's
    # biomes. None of our eleven appeared, and the Greatbole never generated because it is
    # restricted to biomes that were never selected.
    #
    # A LibX biome_layer entry is a vanilla Climate.ParameterPoint and selection is NEAREST
    # MATCH. A point inside two boxes is distance 0 from both, and the tie goes to whichever
    # the KD-tree reaches first -- in practice the earlier, larger entry. Our biomes had been
    # declared as strict SUBSETS of MythicBotany's full-span boxes, so they could never win.
    # The void was the worst case: alfheim_lakes claimed cont [-1, 0] and was declared first,
    # void_verge claimed [-1, -0.8] and was declared last, so the void could not exist.
    #
    # Nothing in the file looks wrong when this happens. It parses, every biome is present, and
    # the world silently contains none of them. Hence a check.
    print('\n--- climate partition ---')
    layer_p = os.path.join(DATA, 'mythicbotany', 'libx', 'biome_layer', 'alfheim.json')
    if os.path.exists(layer_p):
        try:
            bands = json.load(open(layer_p, encoding='utf-8'))['biomes']
        except Exception as e:
            bands = []
            fail('W8', f'biome layer does not parse: {e}')
        dims = ('continentalness', 'erosion', 'weirdness', 'temperature', 'humidity')

        def ov(a, b):
            return all(a[d][0] < b[d][1] and b[d][0] < a[d][1] for d in dims)

        clashes = 0
        for i in range(len(bands)):
            for j in range(i + 1, len(bands)):
                if ov(bands[i]['parameters'], bands[j]['parameters']):
                    clashes += 1
                    if clashes <= 5:
                        fail('W8', f'bands overlap: {bands[i]["biome"]} and {bands[j]["biome"]} '
                                   '-- nearest-match makes this a coin flip and the smaller '
                                   'claim loses')
        if clashes > 5:
            fail('W8', f'... and {clashes - 5} further overlapping pair(s)')

        placed = {b['biome'] for b in bands}
        declared = {'alfheim:' + os.path.basename(p)[:-5]
                    for p in glob.glob(os.path.join(DATA, 'alfheim', 'worldgen', 'biome', '*.json'))}
        for missing in sorted(declared - placed):
            fail('W8', f'{missing} has a biome definition but NO band in the layer, so it can '
                       'never generate')
        print(f'  --   {len(bands)} bands, {len(placed)} biomes, {clashes} overlapping pair(s)')

    # W7 -- the void. Two numbers have to stay in the right order or the world grows holes.
    print('\n--- void verge ---')
    df_path = os.path.join(DATA, 'mythicbotany', 'worldgen', 'density_function',
                           'alfheim_final.json')
    layer_path = os.path.join(DATA, 'mythicbotany', 'libx', 'biome_layer', 'alfheim.json')
    if not os.path.exists(df_path):
        print('  --   no alfheim_final override; void verge not installed')
    else:
        try:
            df = json.load(open(df_path, encoding='utf-8'))
            layer = json.load(open(layer_path, encoding='utf-8'))
        except Exception as e:
            fail('W7', f'void files do not parse: {e}')
            df = layer = None
        if df is not None:
            if df.get('type') != 'minecraft:range_choice':
                fail('W7', 'alfheim_final override is not a range_choice; '
                           'the void band cannot be read')
            else:
                terrain_max = df.get('max_exclusive')
                voids = [b for b in layer.get('biomes', [])
                         if b.get('biome', '').endswith(':void_verge')]
                if not voids:
                    fail('W7', 'alfheim_final carves a void band but no void_verge biome '
                               'claims it -- terrain would vanish under an ordinary biome')
                for v in voids:
                    biome_max = v['parameters']['continentalness'][1]
                    # The terrain band MUST be strictly inside the biome band. Reversed, the
                    # floor disappears under a forest, which reads as corruption rather than
                    # as the edge of the world.
                    if terrain_max >= biome_max:
                        fail('W7', f'void terrain band ({terrain_max}) is not strictly '
                                   f'inside the void biome band ({biome_max}) -- holes '
                                   f'would open under non-void biomes')
                    else:
                        print(f'  OK   terrain ends at {terrain_max}, biome runs to '
                              f'{biome_max} (shore width {biome_max - terrain_max:.3f})')
                # The floating-island window must actually admit some Y range.
                win = df.get('when_in_range', {}).get('argument2', {})
                lo = win.get('argument1', {})
                hi = win.get('argument2', {})
                if lo.get('type') == 'minecraft:y_clamped_gradient' and \
                        hi.get('type') == 'minecraft:y_clamped_gradient':
                    if lo.get('to_y', 0) >= hi.get('from_y', 0):
                        fail('W7', f"island window is empty: rises to y{lo.get('to_y')} "
                                   f"but falls from y{hi.get('from_y')} -- no islands "
                                   f"would generate anywhere")
                    else:
                        print(f"  OK   islands float y{lo.get('to_y')}..{hi.get('from_y')}")

    routes = bloom_routes()

    if routes:
        print('\n--- bloom routes to base ingredients ---')
        for item, (ore, bid, era) in sorted(routes.items(), key=lambda kv: kv[1][2]):
            n = len(produced.get(ore, ()))
            mark = 'OK  ' if n else 'GONE'
            print(f'  {mark} era {era:>2}  {ore:<28} {n:>2} biome(s)  -> {item}')
            if not n:
                fail('W4', f'{ore} renders {item} but generates in no Alfheim biome -- '
                           f'the chain has no root in the ground')

    print('\n--- early-era essentials ---')
    for item, why in EARLY_ESSENTIALS.items():
        if item in produced:                       # a raw ore block of that name generates
            print(f'  OK   {item:36} direct, {len(produced[item])} biome(s)')
        elif item in routes and produced.get(routes[item][0]):
            ore, bid, _ = routes[item]
            print(f'  OK   {item:36} via {bid} '
                  f'({len(produced[ore])} biome(s))')
        else:
            fail('W4', f'{item} is unreachable -- no ore block and no bloom route -- {why}')

    if a.verbose:
        print('\n--- per biome ---')
        for b in sorted(own):
            feats, where = own[b]
            print(f'  {b}  [{where}]  own={len(feats)} added={len(added[b])}')
            for f in added[b]:
                print(f'       + {f}')

    print('\n' + '=' * 68)
    print(f'RESULT: {len(problems)} problem(s)')
    return 1 if problems else 0


if __name__ == '__main__':
    raise SystemExit(main())
