"""Verify fey-wildlife generator source reproduces committed shipping artifacts.

This is a deterministic Level-6/source-to-shipping check. It runs the authoritative
``tools/gen_fey_wildlife.py`` in an isolated temporary directory, seeded only with the
committed language file that the generator intentionally preserves/extends, then compares
every generated byte against the repository. It also rejects stale generator-owned fey
biome modifiers left behind in shipping. It does not mutate the authoritative tree and it
does not claim runtime spawning or EntityJS acceptance.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPECTED_CREATURES = 18
EXPECTED_GENERATED_FILES = EXPECTED_CREATURES * 4 + 3  # geo, animation, modifier, loot + 2 rosters + lang
LANG = Path("kubejs/assets/alfheim/lang/en_us.json")
GENERATOR = Path("tools/gen_fey_wildlife.py")
FEY_MODIFIER_DIR = Path("kubejs/data/alfheim/forge/biome_modifier")


def generated_files(root: Path) -> list[Path]:
    """Return every file produced in an isolated generator output tree."""
    return sorted(path.relative_to(root) for path in root.rglob("*") if path.is_file())


def generated_fey_modifiers(root: Path) -> set[Path]:
    """Return generator-owned fey biome modifiers beneath ``root``."""
    directory = root / FEY_MODIFIER_DIR
    if not directory.is_dir():
        return set()
    return {
        path.relative_to(root)
        for path in directory.glob("fey_*.json")
        if path.is_file()
    }


def compare_outputs(reference_root: Path, generated_root: Path) -> list[str]:
    problems: list[str] = []
    paths = generated_files(generated_root)
    if len(paths) != EXPECTED_GENERATED_FILES:
        problems.append(
            f"generator emitted {len(paths)} files; expected {EXPECTED_GENERATED_FILES} "
            f"for {EXPECTED_CREATURES} creatures"
        )

    for rel in paths:
        expected = reference_root / rel
        actual = generated_root / rel
        if not expected.is_file():
            problems.append(f"generated output missing from repository: {rel}")
            continue
        if expected.read_bytes() != actual.read_bytes():
            problems.append(f"generator/source drift: {rel}")

    expected_modifiers = generated_fey_modifiers(generated_root)
    shipping_modifiers = generated_fey_modifiers(reference_root)
    for rel in sorted(shipping_modifiers - expected_modifiers):
        problems.append(f"stale generator-owned fey biome modifier in repository: {rel}")
    return problems


def check(root: Path = ROOT) -> list[str]:
    root = root.resolve()
    generator = root / GENERATOR
    lang = root / LANG
    if not generator.is_file():
        return [f"missing authoritative generator: {GENERATOR}"]
    if not lang.is_file():
        return [f"missing language seed required by generator: {LANG}"]

    with tempfile.TemporaryDirectory(prefix="alfheim-fey-generation-") as tmp:
        generated_root = Path(tmp)
        generated_lang = generated_root / LANG
        generated_lang.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(lang, generated_lang)

        proc = subprocess.run(
            [sys.executable, str(generator)],
            cwd=generated_root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=120,
            check=False,
        )
        if proc.returncode != 0:
            tail = "\n".join(proc.stdout.splitlines()[-20:])
            return [f"authoritative fey generator failed with exit {proc.returncode}:\n{tail}"]

        problems = compare_outputs(root, generated_root)
        manifest = generated_root / "tools/fey_manifest.json"
        if manifest.is_file():
            import json

            try:
                roster = json.loads(manifest.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                problems.append(f"generated manifest is invalid JSON: {exc}")
            else:
                if not isinstance(roster, list) or len(roster) != EXPECTED_CREATURES:
                    problems.append(
                        f"generated manifest contains {len(roster) if isinstance(roster, list) else 'non-list'} "
                        f"entries; expected {EXPECTED_CREATURES}"
                    )
        else:
            problems.append("generator did not emit tools/fey_manifest.json")
        return problems


def self_test() -> int:
    with tempfile.TemporaryDirectory(prefix="alfheim-fey-check-selftest-") as tmp:
        root = Path(tmp) / "reference"
        generated = Path(tmp) / "generated"
        root.mkdir()
        generated.mkdir()
        for index in range(EXPECTED_GENERATED_FILES):
            rel = Path("out") / f"{index:03d}.json"
            (root / rel).parent.mkdir(parents=True, exist_ok=True)
            (generated / rel).parent.mkdir(parents=True, exist_ok=True)
            payload = f"file-{index}\n".encode()
            (root / rel).write_bytes(payload)
            (generated / rel).write_bytes(payload)
        assert compare_outputs(root, generated) == []

        (generated / "out/000.json").write_text("drift\n", encoding="utf-8")
        drift = compare_outputs(root, generated)
        assert drift == ["generator/source drift: out/000.json"]
        (generated / "out/000.json").write_bytes((root / "out/000.json").read_bytes())

        (generated / "out/001.json").unlink()
        count = compare_outputs(root, generated)
        assert any("generator emitted" in item for item in count)
        shutil.copyfile(root / "out/001.json", generated / "out/001.json")

        stale = root / FEY_MODIFIER_DIR / "fey_retired_species.json"
        stale.parent.mkdir(parents=True, exist_ok=True)
        stale.write_text("{}\n", encoding="utf-8")
        orphan = compare_outputs(root, generated)
        assert orphan == [
            "stale generator-owned fey biome modifier in repository: "
            "kubejs/data/alfheim/forge/biome_modifier/fey_retired_species.json"
        ]
    print("self-test: isolated generated-output equality and stale-owned-output contract PASS")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()

    problems = check(args.root)
    if problems:
        for problem in problems:
            print("PROBLEM:", problem)
        print(f"fey generator equality: FAIL ({len(problems)} problem(s))")
        return 1
    print(
        f"fey generator equality: PASS ({EXPECTED_CREATURES} creatures, "
        f"{EXPECTED_GENERATED_FILES} generated files byte-identical, no stale fey modifiers)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
