"""Fauna drops and their modest supply recipes. Imported by gen_fey_wildlife.py.

No rare creature is required to unlock a class, weapon, rune or profession. Mana refinement
uses the Leaf spine. These are alternative supplies, not MMO XP or currency grants.
"""
ITEMS = {
    'raw_venison': ('Raw Venison', 'minecraft:item/beef', 'Cook at a campfire, furnace or smoker.'),
    'cooked_venison': ('Roasted Venison', 'minecraft:item/cooked_beef', 'A hearty Wildward field ration.'),
    'whitetail_hide': ('Whitetail Hide', 'minecraft:item/leather', 'Trim with a dreamwood twig to make leather.'),
    'hart_antler': ('Hart Antler', 'minecraft:item/bone', 'Grind into three bone meal.'),
    'celestial_mote': ('Celestial Mote', 'minecraft:item/glowstone_dust', 'Refine in a Mana Pool: two Fey Dust, 500 mana.'),
    'frog_gel': ('Frog Gel', 'minecraft:item/slime_ball', 'Combine two portions into a slimeball.'),
    'toad_gland': ('Toad Gland', 'minecraft:item/fermented_spider_eye', 'Refine in a Mana Pool: two slimeballs, 500 mana.'),
    'abyssal_eye': ('Abyssal Eye', 'minecraft:item/ender_eye', 'Refine in a Mana Pool: two glow ink sacs, 1000 mana.'),
    'mire_tendril': ('Mire Tendril', 'minecraft:item/kelp', 'Refine in a Mana Pool: three string, 200 mana.'),
    'maw_fang': ('Maw Fang', 'minecraft:item/ghast_tear', 'Grind into four bone meal.'),
    'barkcloth_scrap': ('Barkcloth Scrap', 'minecraft:item/paper', 'Three scraps unravel into two string.'),
    'bone_fetish': ('Savage Bone Fetish', 'minecraft:item/bone', 'Refine in a Mana Pool: four bone meal, 300 mana.'),
    'scorched_sigil': ('Scorched Elven Sigil', 'minecraft:item/fire_charge', 'Refine in a Mana Pool: one Fey Dust, 1500 mana.'),
}

RECIPES = {
    'whitetail_hide': dict(method='shapeless', ingredients=['alfheim:whitetail_hide','botania:dreamwood_twig'], output='minecraft:leather', count=1),
    'hart_antler': dict(method='shapeless', ingredients=['alfheim:hart_antler'], output='minecraft:bone_meal', count=3),
    'frog_gel': dict(method='shapeless', ingredients=['alfheim:frog_gel']*2, output='minecraft:slime_ball', count=1),
    'maw_fang': dict(method='shapeless', ingredients=['alfheim:maw_fang'], output='minecraft:bone_meal', count=4),
    'barkcloth_scrap': dict(method='shapeless', ingredients=['alfheim:barkcloth_scrap']*3, output='minecraft:string', count=2),
    'celestial_mote': dict(method='mana_infusion', output='feywild:fey_dust', count=2, mana=500),
    'toad_gland': dict(method='mana_infusion', output='minecraft:slime_ball', count=2, mana=500),
    'abyssal_eye': dict(method='mana_infusion', output='minecraft:glow_ink_sac', count=2, mana=1000),
    'mire_tendril': dict(method='mana_infusion', output='minecraft:string', count=3, mana=200),
    'bone_fetish': dict(method='mana_infusion', output='minecraft:bone_meal', count=4, mana=300),
    'scorched_sigil': dict(method='mana_infusion', output='feywild:fey_dust', count=1, mana=1500),
}


def drops(name, family, celestial):
    """(item, minimum, maximum, chance, requires player kill). Looting deliberately adds none."""
    if family == 'deer':
        if celestial:
            result=[('celestial_mote',1,1,1,True)]
        else:
            result=[('raw_venison',1,2,1,False),('whitetail_hide',1,1,.8,False)]
        if name.endswith('buck'):
            result.append(('hart_antler',1,1,.5,True))
        return result
    if family == 'frog':
        return [('frog_gel',1,2 if 'large' in name else 1,.75,False)]
    if family == 'toad':
        return [('frog_gel',1,2,1,False),('toad_gland',1,1,.5,True)]
    return {
        'abyssal_watcher':[('abyssal_eye',1,1,.5,True),('minecraft:ink_sac',1,2,1,False)],
        'mire_tentacle':[('mire_tendril',1,2,1,False),('minecraft:ink_sac',1,1,.5,False)],
        'drowned_maw':[('maw_fang',1,2,1,True),('minecraft:ink_sac',1,2,1,False)],
        'wild_elf':[('barkcloth_scrap',1,3,1,True),('botania:dreamwood_twig',1,2,.35,True)],
        'savage_elf':[('bone_fetish',1,1,1,True),('minecraft:leather',1,2,.5,True)],
        'demonic_elf':[('scorched_sigil',1,1,1,True),('minecraft:charcoal',1,2,.5,True)],
    }[name]


def loot_table(rows):
    pools=[]
    for item,low,high,chance,player in rows:
        conditions=[]
        if player:
            conditions.append({'condition':'minecraft:killed_by_player'})
        if chance < 1:
            conditions.append({'condition':'minecraft:random_chance','chance':chance})
        pools.append({'rolls':1,'conditions':conditions,'entries':[{
            'type':'minecraft:item','name':item if ':' in item else 'alfheim:'+item,
            'functions':[{'function':'minecraft:set_count','count':{'type':'minecraft:uniform','min':low,'max':high}}]}]})
    return {'type':'minecraft:entity','pools':pools}


def generate(root, assets, data, roster, write):
    startup=['// GENERATED by tools/gen_fey_wildlife.py and tools/fey_drops.py.', "StartupEvents.registry('item', event => {"]
    for name,(label,texture,tip) in ITEMS.items():
        line=f"    event.create('alfheim:{name}').displayName('{label}').tooltip('{tip}')"
        if name in ('raw_venison','cooked_venison'):
            nutrition,saturation=(3,.3) if name=='raw_venison' else (8,.8)
            line+=f'.food(f => f.hunger({nutrition}).saturation({saturation}).meat())'
        startup.append(line)
        write(assets/f'models/item/{name}.json',{'parent':'minecraft:item/generated','textures':{'layer0':texture}})
    startup+=['})','']
    (root/'kubejs/startup_scripts/19_fey_drops.js').write_text('\n'.join(startup),encoding='utf-8')
    for name,r in RECIPES.items():
        result={'item':r['output'],'count':r['count']}
        if r['method']=='shapeless':
            recipe={'type':'minecraft:crafting_shapeless','ingredients':[{'item':i} for i in r['ingredients']],'result':result}
        else:
            recipe={'type':'botania:mana_infusion','input':{'item':'alfheim:'+name},'output':result,'mana':r['mana']}
        write(data/f'alfheim/recipes/fey/{name}.json',recipe)
    for method,time in [('smelting',200),('smoking',100),('campfire_cooking',600)]:
        write(data/f'alfheim/recipes/fey/venison_{method}.json',{'type':'minecraft:'+method,
              'ingredient':{'item':'alfheim:raw_venison'},'result':'alfheim:cooked_venison','experience':.35,'cookingtime':time})
    write(data/'forge/tags/items/raw_meats.json',{'replace':False,'values':['alfheim:raw_venison']})
    write(data/'forge/tags/items/cooked_meats.json',{'replace':False,'values':['alfheim:cooked_venison']})
    manifest={'items':{k:dict(name=v[0],texture=v[1],use=v[2]) for k,v in ITEMS.items()},'recipes':RECIPES,
              'creatures':{r['id']:drops(r['id'].split(':')[1],r['family'],r['celestial']) for r in roster},
              'looting_bonus':False}
    write(root/'tools/fey_drops_manifest.json',manifest)
    # Existing compendium group, one optional chapter; no campaign milestones or rewards.
    from gen_compendium import entry,chapter
    pages=[]
    for i,r in enumerate(roster):
        name=r['id'].split(':')[1]
        descriptions=['Habitat: '+', '.join(b.split(':')[1].replace('_',' ').title() for b in r['biomes'])+'.',
                      'Health: '+str(r['health'])+'. '+('Attack: '+str(r['damage'])+'.' if r['damage'] else 'Passive wildlife.')]
        if r['family']=='elf':
            descriptions.append({'wild_elf':'A swift woodland fighter in barkcloth.',
                'savage_elf':'An armored bruiser with a short leaping attack and stronger knockback.',
                'demonic_elf':'A heavily armored, fire-immune corrupted elf. No fire-spreading attack.'}[name])
        if r['celestial']:
            descriptions.append('Rare: weight 1, solitary, with an additional 1-in-32 natural-spawn roll. Celestial deer yield no meat or hide.')
        for item,low,high,chance,player in manifest['creatures'][r['id']]:
            label=ITEMS[item][0] if item in ITEMS else item.split(':')[1].replace('_',' ').title()
            descriptions.append(f'{label}: {low}' + (f'-{high}' if high!=low else '') +
                f', {round(chance*100)}% per kill.'+(' Requires a player kill.' if player else ''))
            if item in ITEMS:
                descriptions.append(ITEMS[item][2])
        descriptions.append('Looting adds no extra trophies. Hunting grants no custom profession XP. These supplies never replace an era milestone.')
        pages.append(entry('ref_fey_wildlife',name,r['name'],'Wildlife and field supplies',descriptions,
                           r['id']+'_spawn_egg',(i%6)*3,(i//6)*3))
    path=root/'config/ftbquests/quests/chapters/ref_fey_wildlife.snbt'
    path.write_text(chapter('ref_fey_wildlife',20,'The Fey Bestiary','Habitats, hostile elves and creature drops',
                           'alfheim:hart_antler',pages),encoding='utf-8')
