"""Generate host-matched Elementium, Dragonstone and Fey Gem ores.

The terrain library contains 42 authored natural stones. A single Livingrock- or
vanilla-stone-backed ore square is conspicuous in those walls, so every ore in this
compatibility family gets a block/texture/loot variant for every host. Exact block-match
targets precede the broad Alfheim-stone fallback.

This also owns the measured field-review density increase for MythicBotany's native ores.
It is build-time generation plus a StartupEvents registration list; nothing runs per tick.

    python tools/gen_native_ores.py
    python tools/gen_native_ores.py --dry-run
"""
import argparse
import copy
import json
import os
import sys
import zipfile

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_blooms import ore_hosts, speckle  # noqa: E402
from item_textures import CLIENT_JAR, load_base  # noqa: E402


NS = 'alfheim'
MANIFEST = os.path.join('tools', 'native_ores_manifest.json')
TEXTURES = os.path.join('kubejs', 'assets', NS, 'textures', 'block')
STARTUP = os.path.join('kubejs', 'startup_scripts', '22_native_ore_variants.js')
DATA = os.path.join('kubejs', 'data')


def variant_id(ore, host):
    stem = host['id'].removesuffix('_livingrock')
    return f'{ore["id"]}_{stem}_ore'


def write(path, content, dry_run):
    if dry_run:
        print(f'  [dry] {path}')
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mode = 'wb' if isinstance(content, bytes) else 'w'
    kwargs = {} if mode == 'wb' else {'encoding': 'utf-8'}
    with open(path, mode, **kwargs) as f:
        f.write(content)


def write_json(path, obj, dry_run):
    write(path, json.dumps(obj, indent=2) + '\n', dry_run)


def repeat_host(host, size):
    """Tile a static host through every vertical animation frame."""
    frame = host.convert('RGBA').resize((size[0], size[0]))
    out = Image.new('RGBA', size)
    for y in range(0, size[1], size[0]):
        out.alpha_composite(frame, (0, y))
    return out


def texture_and_animation(client_jar, ore, hosts, dry_run):
    source = load_base(client_jar, ore['source_texture'])
    source_host = load_base(client_jar, ore['source_host'])
    blobs = speckle(source, source_host, 30)

    # MythicBotany's ore art is a six-frame vertical animation. Copy its animation
    # metadata to every hosted variant; a tall PNG without mcmeta would render as an
    # invalid stretched tile.
    namespace, rest = ore['source_texture'].split(':', 1)
    mcmeta_member = f'assets/{namespace}/textures/{rest}.mcmeta'
    mcmeta = None
    for jar_path in sorted(os.path.join('mods', name) for name in os.listdir('mods')
                           if name.endswith('.jar')):
        try:
            with zipfile.ZipFile(jar_path) as jar:
                if mcmeta_member in jar.namelist():
                    mcmeta = jar.read(mcmeta_member)
                    break
        except (OSError, zipfile.BadZipFile):
            continue

    for host in hosts:
        host_path = os.path.join(TEXTURES, host['id'] + '.png')
        if not os.path.exists(host_path):
            raise FileNotFoundError(f'{host_path}: generate Deep/Void stone assets first')
        host_image = Image.open(host_path).convert('RGBA')
        canvas = repeat_host(host_image, source.size)
        result = Image.alpha_composite(canvas, blobs)
        out = os.path.join(TEXTURES, variant_id(ore, host) + '.png')
        if dry_run:
            print(f'  [dry] {out}')
        else:
            result.save(out)
        if mcmeta is not None:
            write(out + '.mcmeta', mcmeta, dry_run)


def loot_table(source, block_id, ore_id):
    """Retain source count/Fortune/explosion behavior, changing only Silk Touch."""
    table = copy.deepcopy(source)
    children = table['pools'][0]['entries'][0]['children']
    children[0]['name'] = block_id
    if 'random_sequence' in table:
        table['random_sequence'] = f'{NS}:blocks/{ore_id}'
    return table


def source_loot(client_jar, ore):
    namespace, block = ore['base_block'].split(':', 1)
    rel = f'data/{namespace}/loot_tables/blocks/{block}.json'
    for jar_path in sorted(os.path.join('mods', name) for name in os.listdir('mods')
                           if name.endswith('.jar')):
        try:
            with zipfile.ZipFile(jar_path) as jar:
                if rel in jar.namelist():
                    return json.loads(jar.read(rel))
        except (OSError, zipfile.BadZipFile, ValueError):
            continue
    raise FileNotFoundError(f'loot table for {ore["base_block"]} is not installed')


def build_registration(ores, hosts, dry_run):
    lines = [
        '// Alfheim Reclaimed — host-matched native and compatibility ores',
        '//',
        '// GENERATED by tools/gen_native_ores.py — do not hand-edit.',
        '// Registration occurs once at startup. No tick/event polling is used.',
        '',
        "StartupEvents.registry('block', event => {",
    ]
    for ore in ores:
        for host in hosts:
            vid = variant_id(ore, host)
            lines.append(
                f"    event.create('{NS}:{vid}')"
                f".displayName('{host['name']} {ore['name']} Ore')"
                ".soundType('stone').hardness(3.0).resistance(3.0).requiresTool(true)"
                ".tagBlock('minecraft:mineable/pickaxe')"
                f".tagBlock('{ore['tier']}').tagBoth('forge:ores')"
                f".textureAll('{NS}:block/{vid}')")
    lines += ['})', '']
    write(STARTUP, '\n'.join(lines), dry_run)


def configured_feature(ore, hosts):
    targets = [
        {
            'target': {'predicate_type': 'minecraft:block_match',
                       'block': f'{NS}:{host["id"]}'},
            'state': {'Name': f'{NS}:{variant_id(ore, host)}'},
        }
        for host in hosts
    ]
    targets.append({
        'target': {'predicate_type': 'minecraft:tag_match',
                   'tag': 'mythicbotany:base_stone_alfheim'},
        'state': {'Name': ore['base_block']},
    })
    return {
        'type': 'minecraft:ore',
        'config': {
            'discard_chance_on_air_exposure': 0.0,
            'size': ore['size'],
            'targets': targets,
        },
    }


def placed_feature(namespace, ore):
    return {
        'feature': f'{namespace}:{ore["id"]}_ore',
        'placement': [
            {'type': 'minecraft:count', 'count': ore['count']},
            {'type': 'minecraft:in_square'},
            {'type': 'minecraft:height_range', 'height': ore['height']},
            {'type': 'minecraft:biome'},
        ],
    }


def build_data(manifest, hosts, dry_run):
    for ore in manifest['ores']:
        loot = source_loot(None, ore)
        for host in hosts:
            vid = variant_id(ore, host)
            write_json(os.path.join(DATA, NS, 'loot_tables', 'blocks', vid + '.json'),
                       loot_table(loot, f'{NS}:{vid}', vid), dry_run)

        namespace = 'mythicbotany' if ore['id'] in ('elementium', 'dragonstone') else NS
        write_json(os.path.join(DATA, namespace, 'worldgen', 'configured_feature',
                                ore['id'] + '_ore.json'),
                   configured_feature(ore, hosts), dry_run)
        write_json(os.path.join(DATA, namespace, 'worldgen', 'placed_feature',
                                ore['id'] + '_ore.json'),
                   placed_feature(namespace, ore), dry_run)

    write_json(os.path.join(DATA, NS, 'forge', 'biome_modifier',
                            'zz_native_fey_gem.json'), {
        'type': 'forge:add_features',
        'biomes': manifest['fey_gem_biomes'],
        'features': f'{NS}:fey_gem_ore',
        'step': 'underground_ores',
    }, dry_run)

    write_json(os.path.join(DATA, NS, 'tags', 'blocks', 'native_ore_variants.json'), {
        'replace': False,
        'values': [f'{NS}:{variant_id(ore, host)}'
                   for ore in manifest['ores'] for host in hosts],
    }, dry_run)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()
    manifest = json.load(open(MANIFEST, encoding='utf-8'))
    hosts = ore_hosts()

    print('Alfheim host-matched native ores')
    with zipfile.ZipFile(CLIENT_JAR) as client_jar:
        for ore in manifest['ores']:
            texture_and_animation(client_jar, ore, hosts, args.dry_run)
            print(f"  {ore['name']:<12} size {ore['size']}, count {ore['count']}, "
                  f'{len(hosts)} host variants')
    build_registration(manifest['ores'], hosts, args.dry_run)
    build_data(manifest, hosts, args.dry_run)
    print(f'\n  {len(manifest["ores"]) * len(hosts)} blocks/textures/loot tables')
    print('  startup-only registration; no recurring script')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
