"""Generate statue, crystal-plinth, and gemstone-detail blocks for elven environments."""
from __future__ import annotations
from pathlib import Path
import argparse,json
ROOT=Path(__file__).resolve().parents[1]
ASSET=ROOT/"kubejs"/"assets"/"alfheim"
DATA=ROOT/"kubejs"/"data"/"alfheim"
SCRIPT=ROOT/"kubejs"/"startup_scripts"/"25_elven_sculptural_details.js"
T={"stone":"minecraft:block/quartz_block_side","dark":"minecraft:block/polished_blackstone","gold":"minecraft:block/gold_block","gem":"minecraft:block/amethyst_block","wood":"botania:block/dreamwood_planks","glass":"botania:block/elf_glass_0","particle":"minecraft:block/quartz_block_side"}

def box(a,b,tex):return {"from":a,"to":b,"faces":{f:{"texture":"#"+tex} for f in ("north","south","east","west","up","down")}}
def model(e,ambient=True):return {"parent":"minecraft:block/block","ambientocclusion":ambient,"textures":T,"elements":e}
def statue(part,kind):
    if part=="lower":
        e=[box([3,0,3],[13,3,13],"stone"),box([6,3,6],[10,15,10],"stone"),box([4,4,5],[7,14,9],"stone"),box([9,4,5],[12,14,9],"stone")]
        if kind=="mourning":e += [box([3,3,8],[13,10,13],"dark")]
    else:
        e=[box([5,0,5],[11,10,11],"stone"),box([4,9,4],[12,16,12],"stone")]
        if kind=="ancestor":e += [box([3,4,7],[13,7,10],"gold"),box([6,12,3],[10,15,5],"gem")]
        elif kind=="oathkeeper":e += [box([2,1,7],[5,14,9],"gold"),box([11,1,7],[14,14,9],"gold")]
        else:e += [box([2,5,8],[14,12,13],"dark")]
    return model(e)
def plinth(part):
    if part=="base":return model([box([1,0,1],[15,3,15],"stone"),box([3,3,3],[13,12,13],"dark"),box([2,12,2],[14,16,14],"gold")])
    return model([box([5,0,5],[11,14,11],"gem"),box([3,3,6],[13,11,10],"glass"),box([6,14,6],[10,16,10],"gold")],False)
def prism():return model([box([2,0,2],[14,3,14],"stone"),box([4,3,4],[12,6,12],"gold"),box([6,6,6],[10,16,10],"glass"),box([7,8,7],[9,14,9],"gem")],False)
def wall_jewel():return model([box([2,2,14],[14,14,16],"gold"),box([5,5,12],[11,11,15],"gem")],False)
def floor_inlay():return model([box([1,0,1],[15,1,15],"stone"),box([4,1.01,4],[12,1.5,12],"gold"),box([6,1.5,6],[10,2.5,10],"gem")],False)
def finial_gem():return model([box([5,0,5],[11,3,11],"gold"),box([6,3,6],[10,13,10],"gem"),box([7,13,7],[9,16,9],"gold")],False)

BLOCKS=[]
for kind in ("ancestor","oathkeeper","mourning"):
    for part in ("lower","upper"):BLOCKS.append((f"{kind}_statue_{part}",f"{kind}_statue",False,statue(part,kind),[[3,0,3,13,16,13]]))
for part in ("base","crystal"):BLOCKS.append((f"large_crystal_plinth_{part}","large_crystal_plinth",False,plinth(part),[[1,0,1,15,16,15]]))
BLOCKS += [
    ("observatory_prism_stand","observatory_prism_stand",True,prism(),[[2,0,2,14,16,14]]),
    ("gemstone_wall_jewel","gemstone_wall_jewel",True,wall_jewel(),[[2,2,12,14,14,16]]),
    ("gemstone_floor_inlay","gemstone_floor_inlay",True,floor_inlay(),[[1,0,1,15,2,15]]),
    ("gemstone_finial","gemstone_finial",True,finial_gem(),[[5,0,5,11,16,11]]),
]

def build():
    out={}
    for name,semantic,item,obj,boxes in BLOCKS:out[f"models/block/sculptural/{name}.json"]=obj
    lines=["// GENERATED by tools/gen_elven_sculptural_details.py — do not hand-edit.","const SCULPT_FACING = BlockProperties.HORIZONTAL_FACING","StartupEvents.registry('block', event => {"]
    for name,semantic,item,obj,boxes in BLOCKS:
        lines += [f"  let sculpt_{name} = event.create('alfheim:{name}', 'cardinal')",f"    .displayName({json.dumps(name.replace('_',' ').title())})",f"    .model('alfheim:block/sculptural/{name}')","    .hardness(2.0).resistance(6.0).fullBlock(false).notSolid().noValidSpawns(true)"]
        if "gemstone" in name or "crystal" in name or "prism" in name:lines += ["    .renderType('cutout')"]
        if boxes:
            for b in boxes:lines += ["    .box("+", ".join(map(str,b))+")"]
        lines += ["    .tagBlock('alfheim:elven_sculptural_details')"]
        if item:lines += ["    .tagItem('alfheim:elven_sculptural_details')"]
        else:lines += ["    .noItem()"]
        lines += [f"  sculpt_{name}.rotateState(s => s.setValue(SCULPT_FACING, s.rotate(s.getValue(SCULPT_FACING))))",f"  sculpt_{name}.mirrorState(s => s.setValue(SCULPT_FACING, s.mirror(s.getValue(SCULPT_FACING))))",""]
    lines += ["})",""]
    out["startup"]="\n".join(lines)
    ids=["alfheim:"+b[0] for b in BLOCKS]
    out["tags/blocks/elven_sculptural_details.json"]={"replace":False,"values":ids}
    out["tags/items/elven_sculptural_details.json"]={"replace":False,"values":["alfheim:"+b[0] for b in BLOCKS if b[2]]}
    review=["# GENERATED by tools/gen_elven_sculptural_details.py","say [Alfheim] placing sculptural detail gallery"]
    x=0
    for kind in ("ancestor","oathkeeper","mourning"):
        review += [f"setblock ~{x} ~ ~0 alfheim:{kind}_statue_lower[facing=north]",f"setblock ~{x} ~1 ~0 alfheim:{kind}_statue_upper[facing=north]"];x+=3
    review += ["setblock ~10 ~ ~0 alfheim:large_crystal_plinth_base[facing=north]","setblock ~10 ~1 ~0 alfheim:large_crystal_plinth_crystal[facing=north]","setblock ~13 ~ ~0 alfheim:observatory_prism_stand[facing=north]","setblock ~16 ~ ~0 alfheim:gemstone_wall_jewel[facing=north]","setblock ~19 ~ ~0 alfheim:gemstone_floor_inlay[facing=north]","setblock ~22 ~ ~0 alfheim:gemstone_finial[facing=north]","say [Alfheim] sculptural gallery placed",""]
    out["review"]="\n".join(review)
    return out

def paths(key):
    if key=="startup":return SCRIPT
    if key=="review":return DATA/"functions"/"elven_sculptural_details"/"review.mcfunction"
    if key.startswith("models/"):return ASSET/key
    return DATA/key
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--check",action="store_true");args=ap.parse_args();bad=[]
    for key,value in build().items():
        data=(value if isinstance(value,str) else json.dumps(value,separators=(",",":"))+"\n").encode();path=paths(key)
        if args.check:
            if not path.exists() or path.read_bytes()!=data:bad.append(str(path.relative_to(ROOT)))
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
    if bad:raise SystemExit("Generated output mismatch:\n"+"\n".join(bad))
    print(f"{len(build())} sculptural detail resources "+("byte-identical" if args.check else "generated"))
if __name__=="__main__":main()
