"""Generate intermediate items: textures, models, and KubeJS registration.

The tier ladder needs roughly 80 intermediates across Eras III-X. Hand-drawing 80 icons is not
realistic, so each is derived from a **vanilla** base texture by hue rotation, saturation and
brightness. Vanilla bases only: deriving from third-party mod art would be redistributing a
derivative work. Mod bases are supported too — the pack owner has accepted that call — but any
public release should audit the licences of whatever mods end up sourced.

The recolour/composite primitives live in `tools/item_textures.py`, shared with
`tools/gen_curios.py` so there is one implementation of what a generated icon looks like.

The manifest is the source of truth. Regenerating from it reproduces every asset, so the roster
stays reproducible rather than hand-maintained.

    python tools/gen_items.py
    python tools/gen_items.py --list
"""
import argparse
import json
import os
import sys
import zipfile

from item_textures import CLIENT_JAR, load_base, overlay, tint

NS = 'alfheim'
TEX_OUT = os.path.join('kubejs', 'assets', NS, 'textures', 'item')
MODEL_OUT = os.path.join('kubejs', 'assets', NS, 'models', 'item')
SCRIPT_OUT = os.path.join('kubejs', 'startup_scripts', '10_items.js')
MANIFEST = os.path.join('tools', 'items_manifest.json')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--list', action='store_true')
    a = ap.parse_args()

    manifest = json.load(open(MANIFEST, encoding='utf-8'))
    items = manifest['items']

    if a.list:
        for it in items:
            print(f"  era {it['era']:>2}  {NS}:{it['id']:24} {it['name']}")
        print(f'\n{len(items)} items')
        return 0

    if not os.path.exists(CLIENT_JAR):
        print(f'client jar not found: {CLIENT_JAR}')
        return 2

    os.makedirs(TEX_OUT, exist_ok=True)
    os.makedirs(MODEL_OUT, exist_ok=True)

    jar = zipfile.ZipFile(CLIENT_JAR)
    lines = [
        '// Alfheim Reclaimed — tier ladder intermediates',
        '//',
        '// GENERATED by tools/gen_items.py from tools/items_manifest.json — do not hand-edit.',
        '// Textures are derived from vanilla and mod bases by recolouring.',
        '',
        "StartupEvents.registry('item', event => {",
    ]

    for it in items:
        base = load_base(jar, it['base'])
        img = tint(base, it.get('hue', 0), it.get('sat', 1.0), it.get('val', 1.0),
                   it.get('sat_floor', 0.45))
        if it.get('overlay'):
            top = load_base(jar, it['overlay'])
            top = tint(top, it.get('overlay_hue', 0), it.get('overlay_sat', 1.0),
                       it.get('overlay_val', 1.0), it.get('overlay_sat_floor', 0.45))
            img = overlay(img, top, it.get('overlay_alpha', 0.55))

        tex = os.path.join(TEX_OUT, it['id'] + '.png')
        img.save(tex)

        model = {'parent': 'minecraft:item/generated',
                 'textures': {'layer0': f'{NS}:item/{it["id"]}'}}
        with open(os.path.join(MODEL_OUT, it['id'] + '.json'), 'w', encoding='utf-8') as f:
            json.dump(model, f, indent=2)

        tip = it.get('tooltip')
        reg = f"    event.create('{NS}:{it['id']}').displayName('{it['name']}')"
        if tip:
            reg += f".tooltip('{tip}')"
        if it.get('rarity'):
            reg += f".rarity('{it['rarity']}')"
        lines.append(reg)
        print(f"  era {it['era']:>2}  {it['id']:24} <- {it['base']}")

    lines += ['})', '']
    os.makedirs(os.path.dirname(SCRIPT_OUT), exist_ok=True)
    with open(SCRIPT_OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    jar.close()
    print(f'\n{len(items)} items -> {TEX_OUT}, {MODEL_OUT}, {SCRIPT_OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
