"""Generate the operator-facing world-hub functions.

The problem, named by the user 2026-09-04:

    "We should have server side commands for a server operator to create the world spawn and
    set player world spawning to the correct place, so that server operators can start a
    server and open a world and have players be able to join, spawn in the right dimension in
    the pre-made server spawn. So our correct world hub generation should not depend on a
    player logging in."

It did depend on that. `02_spawn_dimension.js` teleported each player on `PlayerEvents.loggedIn`
and `spreadplayers`-ed them up to 2000 blocks; `03_hollow_court.js` audited the court on login
too. A server nobody had joined had no hub at all, and two players could land a kilometre apart.

WHY DATAPACK FUNCTIONS RATHER THAN KUBEJS
-----------------------------------------
`ServerEvents.commandRegistry` hands you a raw Brigadier dispatcher, and this project has
already been bitten by KubeJS APIs whose shape moved between builds -- `02_spawn_dimension.js`
carries a comment refusing level accessors for exactly that reason, and `.tagItem()` cost a boot
this session.

Vanilla function files have none of that risk, and they are a better fit for the ask:

  * `#minecraft:load` runs them on every world load and every `/reload`, on the server, with
    NO PLAYER. That single tag is the whole answer to "must not depend on a player logging in".
  * an operator gets real, tab-completable commands: `/function alfheim:hub/create`.
  * they work from a headless console, which is how a server is actually administered.

THE ANCHOR
----------
Finding a safe Y from a command is the hard part, and it is solved by not trying to compute one:
a `minecraft:marker` is summoned high over the hub and `spreadplayers` drops it onto a legal
surface. The marker IS the anchor from then on. Nothing has to parse coordinates back out of a
command, which `runCommandSilent` cannot do anyway -- it returns a result count.

    python tools/gen_world_hub.py
"""
import argparse
import json
import os

NS = 'alfheim'
HOME = 'mythicbotany:alfheim'
FUNC = os.path.join('kubejs', 'data', NS, 'functions', 'hub')
TAGS = os.path.join('kubejs', 'data', 'minecraft', 'tags', 'functions')

MARKER = 'minecraft:marker'
TAG = 'alfheim_hub'
OBJ = 'alfheim.hub'          # scoreboard flag; functions have no persistent storage otherwise
# TWO-STAGE FORCE-LOAD. Runtime-reported 2026-09-04: a player joined 31 seconds after world
# load and the hub had still not resolved 2.5 minutes later, because 441 chunks have to
# GENERATE before the anchor exists and a client is rendering at the same time.
#
# But 441 chunks is the worst case, not the normal one. The Greatbole pins to chunk 0,0 whenever
# the origin is buildable (see gen_spawn_hub's has_greatbole note); only when the origin is void
# or lake does the biome search push it out as far as 112 blocks. So: load the small disc first
# and answer the common case in a fraction of the time, and widen only if the tree really is not
# there.
NEAR = 4                     # 81 chunks, +-64 blocks -- covers a tree pinned at chunk 0,0
RADIUS = 10                  # 441 chunks, +-160 blocks -- covers the 112-block relocation
                             # plus half the 96-block structure. It was 32 when the tree could
                             # be anywhere.
KEEP = 6                     # chunks kept loaded after the hub resolves, so the court and
                             # the gate stay ticking for arriving players
RETRY_TICKS = 100            # 5s between resolve attempts
# TWO deadlines, not one. Runtime-proven 2026-09-04: a single 2-minute deadline fired the
# fallback at 125s and the baked anchor turned up at ~145s, so the world ended up permanently
# anchored to the origin with a perfectly good Greatbole 135 blocks away.
#
# So the fallback is now PROVISIONAL -- it gives the world a usable spawn on time, and the
# resolve loop keeps going. If the anchor appears later the hub re-anchors to it, in the same
# session, with no restart.
WIDEN_AT = 6                 # resolve attempts (~30s) before widening the force-load to RADIUS
PROVISIONAL = 24             # ~2 min: give the world SOME spawn rather than none
RETRIES = 240                # ~20 min hard stop, but the loop ends the moment it anchors

AWAIT = 'alfheim_awaiting_hub'  # a player placed provisionally, owed a move to the hub
BAKED = 'alfheim_hub_baked'  # carried inside greatbole/base.nbt by gen_spawn_hub.hub_anchor
SELECT = f'@e[type={MARKER},tag={TAG},limit=1]'
SELECT_BAKED = f'@e[type={MARKER},tag={BAKED},limit=1]'


def header(title, *notes):
    out = [f'# Alfheim Reclaimed -- {title}',
           '#',
           '# GENERATED by tools/gen_world_hub.py -- do not hand-edit.']
    for n in notes:
        out += ['#', '# ' + n]
    return out + ['']


FILES = {}

# ---------------------------------------------------------------------------- create
FILES['create'] = header(
    'create the world hub',
    'Idempotent. Safe to run repeatedly and safe to run from #minecraft:load, which fires on '
    'every world load AND every /reload.',
    'This function CANNOT finish the job on its own, and that is deliberate. `forceload add` '
    'only marks chunks -- the server generates them over the following ticks -- so the anchor '
    'baked into greatbole/base.nbt does not exist yet on the tick this runs. Anything reading '
    'the anchor here would read nothing. So create only starts the work and hands off to '
    'hub/resolve, which retries until the chunks are actually there.',
) + [
    f'scoreboard objectives add {OBJ} dummy',
    f'scoreboard players set #attempts {OBJ} 0',
    '',
    '# Generate the ground the hub stands on -- and, with it, the Greatbole and the anchor',
    '# marker baked into its base piece. NEAR first: this is the disc the tree occupies when it',
    '# pins to chunk 0,0, which is the normal case, and it is a fifth of the chunks.',
    f'execute in {HOME} run forceload add -{NEAR} -{NEAR} {NEAR} {NEAR}',
    '',
    f'function {NS}:hub/resolve',
]

# ---------------------------------------------------------------------------- resolve
FILES['resolve'] = header(
    'wait for the Greatbole to generate, then anchor to it',
    'The retry half of create. Reschedules itself every 5s until the baked anchor appears, then '
    'hands to hub/anchor. After ~2 minutes it gives up and takes the fallback.',
    'Bounded on purpose: an unbounded self-schedule, in a world where the structure genuinely '
    'cannot generate, would reschedule for the life of the server.',
) + [
    f'scoreboard players add #attempts {OBJ} 1',
    '',
    '# Widen once if the near disc did not contain the tree -- the origin was void or lake and',
    '# the biome search relocated it. Costs the bigger generation pass only when it is needed.',
    f'execute unless score #final {OBJ} matches 1 if score #attempts {OBJ} matches {WIDEN_AT} '
    f'in {HOME} run forceload add -{RADIUS} -{RADIUS} {RADIUS} {RADIUS}',
    f'execute unless score #final {OBJ} matches 1 if score #attempts {OBJ} matches {WIDEN_AT} '
    f'run say [Alfheim] no Greatbole within {NEAR * 16} blocks of the origin; widening the '
    f'search to {RADIUS * 16}.',
    '',
    '# Success, and the only thing that ends the loop: the structure generated and brought its',
    '# anchor with it. Runs even after a provisional fallback, which is the point -- the hub',
    '# upgrades itself to the real tree the moment the chunk finishes.',
    f'execute in {HOME} unless score #final {OBJ} matches 1 if entity {SELECT_BAKED} '
    f'run function {NS}:hub/anchor',
    '',
    '# Provisional spawn at ~2 minutes so the world is never left without one. Does NOT stop',
    '# the loop.',
    f'execute unless score #created {OBJ} matches 1 '
    f'if score #attempts {OBJ} matches {PROVISIONAL}.. run function {NS}:hub/fallback',
    '',
    '# Keep waiting for the real thing.',
    f'execute unless score #final {OBJ} matches 1 if score #attempts {OBJ} matches ..{RETRIES} '
    f'run schedule function {NS}:hub/resolve {RETRY_TICKS}t',
    '',
    f'execute unless score #final {OBJ} matches 1 if score #attempts {OBJ} matches {RETRIES + 1}.. '
    f'run say [Alfheim] gave up waiting for the Greatbole after {RETRIES * RETRY_TICKS // 20}s; '
    f'the provisional origin spawn stands. Run /function {NS}:hub/reset then '
    f'/function {NS}:hub/create to retry.',
]

# ---------------------------------------------------------------------------- anchor
FILES['anchor'] = header(
    'bind the world spawn to the baked anchor',
    'The success path. The anchor is a marker standing on the gate-chamber floor inside '
    'greatbole/base.nbt, so it lands wherever the structure lands and cannot drift from the '
    'tree the way a summoned marker at the origin did.',
    'One block up: the marker sits ON the floor, so ~ ~ ~ would spawn a player inside it.',
) + [
    '# A summoned fallback anchor from an earlier attempt would make @e[limit=1] pick between',
    '# two markers arbitrarily. The baked one is authoritative, so the other goes.',
    f'execute in {HOME} run kill @e[type={MARKER},tag={TAG},tag=!{BAKED}]',
    '',
    f'execute in {HOME} at {SELECT_BAKED} run setworldspawn ~ ~1 ~',
    '',
    '# Release the generation force-load and keep only the hub itself loaded. Without this the',
    f'# server pays for {(2 * RADIUS + 1) ** 2} permanently loaded chunks for the life of the '
    'world.',
    f'execute in {HOME} run forceload remove all',
    f'execute in {HOME} run forceload add -{KEEP} -{KEEP} {KEEP} {KEEP}',
    '',
    '',
    '# COLLECT THE PLAYERS WHO ARRIVED FIRST. Anyone placed provisionally while the Greatbole',
    '# was still generating carries the await tag; now that the anchor exists, bring them in.',
    '# This is what makes a fast join self-healing instead of permanent -- the player joined at',
    '# 31 seconds and the hub resolved minutes later, and nothing moved them.',
    f'execute in {HOME} as @a[tag={AWAIT}] at {SELECT_BAKED} run tp @s ~ ~1 ~',
    f'execute in {HOME} as @a[tag={AWAIT}] at {SELECT_BAKED} run spawnpoint @s ~ ~1 ~',
    f'execute as @a[tag={AWAIT}] run tellraw @s {{"text":"[Alfheim] The Greatbole has finished '
    'generating. Welcome to the Hollow Court.","color":"green"}',
    f'tag @a[tag={AWAIT}] remove {AWAIT}',
    '',
    f'scoreboard players set #created {OBJ} 1',
    '# #final is what stops hub/resolve. Only a real, structure-carried anchor sets it, so a',
    '# provisional fallback never ends the search for the tree.',
    f'scoreboard players set #final {OBJ} 1',
    'tellraw @a[tag=!alfheim_quiet] {"text":"[Alfheim] World hub anchored to the Greatbole.",'
    '"color":"green"}',
    'say [Alfheim] world hub anchored to the Greatbole gate chamber.',
]

# ---------------------------------------------------------------------------- fallback
FILES['fallback'] = header(
    'a PROVISIONAL spawn while the Greatbole is still generating',
    'Reached when hub/resolve has waited ~2 minutes. This does not end the search: it gives '
    'the world a spawn a player can stand on, and hub/resolve keeps looking for the real '
    'anchor and re-anchors to it when it appears.',
    'spreadplayers drops a summoned marker onto a legal surface, which still gives the world a '
    'spawn a player can stand on.',
) + [
    f'execute in {HOME} run kill @e[type={MARKER},tag={TAG},tag=!{BAKED}]',
    f'execute in {HOME} run summon {MARKER} 0 250 0 {{Tags:["{TAG}"]}}',
    f'execute in {HOME} run spreadplayers 0 0 1 24 false @e[type={MARKER},tag={TAG}]',
    f'execute in {HOME} at {SELECT} run setworldspawn ~ ~1 ~',
    '',
    f'execute in {HOME} run forceload remove all',
    f'execute in {HOME} run forceload add -{KEEP} -{KEEP} {KEEP} {KEEP}',
    '',
    f'scoreboard players set #created {OBJ} 1',
    'tellraw @a[tag=!alfheim_quiet] {"text":"[Alfheim] The Greatbole has not generated yet; '
    'using a provisional spawn at the origin. It will move to the tree automatically once the '
    'chunks finish.","color":"yellow"}',
    'say [Alfheim] provisional origin spawn set; still waiting for the Greatbole.',
]

# ---------------------------------------------------------------------------- autoload
FILES['autoload'] = header(
    'run on every world load',
    'Wired to #minecraft:load. This is the line that makes hub creation independent of any '
    'player: the tag fires on server start with nobody connected.',
    'Creates the hub only once per world; #created survives in the scoreboard.',
) + [
    f'scoreboard objectives add {OBJ} dummy',
    f'execute unless score #created {OBJ} matches 1 run function {NS}:hub/create',
    '',
    '# Re-assert the force-load every load: forceload state is per-world and an operator may',
    '# legitimately have cleared it.',
    f'execute if score #created {OBJ} matches 1 in {HOME} run forceload add -{KEEP} -{KEEP} {KEEP} {KEEP}',
]

# ---------------------------------------------------------------------------- status
FILES['status'] = header(
    'report hub state to the operator',
    "READ-ONLY. An earlier draft set the caller's spawnpoint here, which is a surprising "
    'mutation in a command called status; a status command must be safe to run at any time.',
    'Written for the CONSOLE as much as for a player: the server has no @s, so this reports '
    'through `say` and `data get`, both of which print to the console log. That matters -- an '
    'operator setting up a headless server is exactly who needs this.',
) + [
    'say [Alfheim] --- world hub status ---',
    f'execute unless score #created {OBJ} matches 1 run say [Alfheim] hub: NOT CREATED -- '
    f'run /function {NS}:hub/create',
    f'execute if score #created {OBJ} matches 1 run say [Alfheim] hub: created',
    '',
    '# Prints the anchor position straight into the console log.',
    f'execute in {HOME} run data get entity {SELECT} Pos',
    '',
    f'execute in {HOME} unless entity @e[type={MARKER},tag={TAG}] run say '
    f'[Alfheim] WARNING: no anchor entity in {HOME} -- the hub flag is set but the anchor is gone',
]

# ---------------------------------------------------------------------------- send
FILES['send'] = header(
    'put the running player in Alfheim, at the hub if there is one',
    'The delivery half. Vanilla has no cross-dimension world spawn, so SOMETHING has to move a '
    'player into Alfheim; this is that something.',
    'CROSSING INTO ALFHEIM DOES NOT DEPEND ON THE HUB. Runtime-reported 2026-09-04: a player '
    'joined 31 seconds after world load, the Greatbole had not finished generating, and they '
    'were left standing in Midgard for the whole session. The old body was two commands, both '
    'anchored on `at @e[...marker...]` -- with no marker, both did nothing and the player never '
    'moved at all. Getting into the right WORLD is the part that must always work; landing on '
    'the tree is a refinement on top of it.',
    'So: cross first, unconditionally, then refine. A player is in Alfheim from the first '
    'second either way.',
    'Sets the respawn point too, so dying bedless returns them here rather than to Midgard.',
) + [
    '# 1. CROSS. Unconditional, and safe to run on a player already in Alfheim. y=320 is above',
    '#    any terrain, so this never suffocates; the next lines put them on the ground.',
    f'execute in {HOME} run tp @s 0 320 0',
    '',
    '# 2. REFINE, if the hub has resolved: stand them in the gate chamber.',
    f'execute in {HOME} at {SELECT} run tp @s ~ ~1 ~',
    f'execute in {HOME} at {SELECT} run spawnpoint @s ~ ~1 ~',
    f'execute in {HOME} if entity {SELECT} run tag @s remove {AWAIT}',
    '',
    '# 3. NO HUB YET: land them on legal ground near the origin and mark them as owed a hub.',
    '#    The range is deliberately small -- this is the hub neighbourhood, not the 2000-block',
    '#    scatter the pre-2026-09-04 script used, which put every player somewhere different.',
    f'execute in {HOME} unless entity {SELECT} run spreadplayers 0 0 1 160 false @s',
    f'execute in {HOME} unless entity {SELECT} run spawnpoint @s ~ ~ ~',
    f'execute in {HOME} unless entity {SELECT} run tag @s add {AWAIT}',
    f'execute in {HOME} unless entity {SELECT} run tellraw @s {{"text":"[Alfheim] The Greatbole '
    'is still generating. You have been placed nearby and will be moved to the gate chamber '
    'as soon as it finishes.","color":"yellow"}',
]

# ---------------------------------------------------------------------------- reset
FILES['reset'] = header(
    'tear the hub down so it can be rebuilt',
    'For an operator who has moved the structure or wants a fresh anchor. Does not touch the '
    'world, only the anchor and the flag.',
    'Kills only the SUMMONED fallback anchor. The baked anchor is part of greatbole/base.nbt '
    'and is written into the world exactly once, when its chunk first generates -- killing it '
    'would be unrecoverable without deleting the region file, so reset must leave it alone.',
) + [
    f'execute in {HOME} run kill @e[type={MARKER},tag={TAG},tag=!{BAKED}]',
    f'scoreboard players reset #created {OBJ}',
    f'scoreboard players set #attempts {OBJ} 0',
    f'scoreboard players reset #final {OBJ}',
    'tellraw @s {"text":"[Alfheim] Hub reset. Run /function alfheim:hub/create.","color":"yellow"}',
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dry-run', action='store_true')
    a = ap.parse_args()

    if not a.dry_run:
        os.makedirs(FUNC, exist_ok=True)
        os.makedirs(TAGS, exist_ok=True)

    for name, lines in FILES.items():
        p = os.path.join(FUNC, name + '.mcfunction')
        if not a.dry_run:
            with open(p, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines) + '\n')
        print(f'  {name + ".mcfunction":22} {len([l for l in lines if l and not l.startswith("#")])} commands')

    # #minecraft:load is the vanilla hook that runs on world load with no player present.
    tag = {'replace': False, 'values': [f'{NS}:hub/autoload']}
    if not a.dry_run:
        with open(os.path.join(TAGS, 'load.json'), 'w', encoding='utf-8') as f:
            json.dump(tag, f, indent=2)
            f.write('\n')
    print(f'  load.json              -> {NS}:hub/autoload')
    print(f'\n  operator commands: /function {NS}:hub/'
          + ', /function {}:hub/'.format(NS).join(sorted(FILES)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
