"""Generate text resources for Alfheim Leyworks' fixed-capacity elven containers."""
from __future__ import annotations
from pathlib import Path
import argparse,json

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/"first_party_mods"/"alfheim_leyworks"/"src"/"main"/"resources"
NS="alfheim_leyworks"
TEXTURES={
    "wood":"botania:block/dreamwood_planks","log":"botania:block/dreamwood_log",
    "gold":"minecraft:block/gold_block","gem":"minecraft:block/amethyst_block",
    "quartz":"minecraft:block/quartz_block_side","paper":"minecraft:block/birch_planks",
    "green":"minecraft:block/green_wool","dark":"minecraft:block/polished_blackstone",
}

def cube(frm,to,tex):
    return {"from":frm,"to":to,"faces":{face:{"texture":"#"+tex} for face in ("north","south","east","west","up","down")}}

def model(elements):
    return {"parent":"minecraft:block/block","textures":dict(TEXTURES,particle=TEXTURES["wood"]),"elements":elements}

def royal_chest():
    return model([cube([1,0,2],[15,11,14],"wood"),cube([1,11,2],[15,14,14],"quartz"),
                  cube([1,2,1.5],[15,4,2.5],"gold"),cube([1,9,1.5],[15,11,2.5],"gold"),
                  cube([7,6,1],[9,10,3],"gem"),cube([0.5,0,1.5],[2.5,14,3.5],"gold"),cube([13.5,0,1.5],[15.5,14,3.5],"gold")])

def coffer():
    return model([cube([2,0,3],[14,7,13],"dark"),cube([2,7,3],[14,9,13],"gold"),
                  cube([3,1,2.5],[13,7,3.5],"wood"),cube([6,3,2],[10,7,4],"gem"),cube([1.5,0,2.5],[3,9,4],"gold"),cube([13,0,2.5],[14.5,9,4],"gold")])

def crate(accent):
    e=[cube([1,0,1],[15,15,15],"log"),cube([2,2,0.5],[14,13,1.5],"wood"),
       cube([1,0,0],[15,2,2],"gold"),cube([1,13,0],[15,15,2],"gold"),
       cube([1,1,0],[3,14,2],"gold"),cube([13,1,0],[15,14,2],"gold")]
    if accent: e += [cube([5,5,0],[11,10,2],accent)]
    return model(e)

def scroll_crate():
    e=crate(None)["elements"]
    for x in (3,7,11): e += [cube([x,5,0],[x+2,11,2],"paper"),cube([x-.5,4.5,0],[x+2.5,6,2],"gold")]
    return model(e)

def vase(urn=False):
    e=[cube([6,0,6],[10,2,10],"gold"),cube([4,2,4],[12,7,12],"quartz"),
       cube([5,7,5],[11,12 if urn else 14,11],"quartz"),cube([6,12 if urn else 14,6],[10,14 if urn else 16,10],"gold")]
    if urn: e += [cube([5,14,5],[11,15,11],"gold"),cube([7,15,7],[9,16,9],"gem"),cube([2,6,6],[5,10,10],"gold"),cube([11,6,6],[14,10,10],"gold")]
    return model(e)

MODELS={
    "royal_chest":royal_chest(),"gemstone_coffer":coffer(),
    "dreamwood_crate":crate(None),"provision_crate":crate("green"),
    "scroll_crate":scroll_crate(),"tall_vase":vase(False),"memorial_urn":vase(True),
}

RECIPES={
    "royal_chest":("EDE","DCD","EDE",{"E":{"item":"botania:elementium_ingot"},"D":{"item":"botania:dreamwood"},"C":{"item":"minecraft:chest"}}),
    "gemstone_coffer":("EGE","DCD","EEE",{"E":{"item":"botania:elementium_ingot"},"G":{"item":"botania:mana_diamond"},"D":{"item":"botania:dreamwood"},"C":{"item":"minecraft:chest"}}),
    "dreamwood_crate":("DDD","DCD","DDD",{"D":{"item":"botania:dreamwood"},"C":{"item":"minecraft:chest"}}),
    "provision_crate":("DDD","WCW","DDD",{"D":{"item":"botania:dreamwood"},"W":{"item":"minecraft:wheat"},"C":{"item":"minecraft:chest"}}),
    "scroll_crate":("DDD","PCP","DDD",{"D":{"item":"botania:dreamwood"},"P":{"item":"minecraft:paper"},"C":{"item":"minecraft:chest"}}),
    "tall_vase":(" Q ","Q Q","EQE",{"Q":{"item":"botania:elf_quartz"},"E":{"item":"botania:elementium_ingot"}}),
    "memorial_urn":(" E ","QGQ","QQQ",{"Q":{"item":"botania:elf_quartz"},"E":{"item":"botania:elementium_ingot"},"G":{"item":"botania:mana_diamond"}}),
}

def build():
    out={}
    for name,obj in MODELS.items():
        out[f"assets/{NS}/models/block/{name}.json"]=obj
        out[f"assets/{NS}/models/item/{name}.json"]={"parent":f"{NS}:block/{name}"}
        variants={}
        for facing,y in (("north",0),("east",90),("south",180),("west",270)):
            variants[f"facing={facing}"]={"model":f"{NS}:block/{name}","y":y}
        out[f"assets/{NS}/blockstates/{name}.json"]={"variants":variants}
        out[f"data/{NS}/loot_tables/blocks/{name}.json"]={"type":"minecraft:block","pools":[{"rolls":1,"entries":[{"type":"minecraft:item","name":f"{NS}:{name}"}],"conditions":[{"condition":"minecraft:survives_explosion"}]}]}
        a,b,c,key=RECIPES[name]
        out[f"data/{NS}/recipes/{name}.json"]={"type":"minecraft:crafting_shaped","pattern":[a,b,c],"key":key,"result":{"item":f"{NS}:{name}"}}
    out[f"data/{NS}/tags/blocks/functional_elven_containers.json"]={"replace":False,"values":[f"{NS}:{name}" for name in MODELS]}
    out[f"data/{NS}/tags/items/functional_elven_containers.json"]={"replace":False,"values":[f"{NS}:{name}" for name in MODELS]}
    review=["# GENERATED by tools/gen_functional_elven_containers.py","say [Alfheim] placing functional elven container gallery"]
    for index,name in enumerate(["manna_stone_storage",*MODELS.keys()]):
        review.append(f"setblock ~{index*3} ~ ~0 {NS}:{name}[facing=north]")
    review += ["say [Alfheim] container gallery placed; inspect and open every block",""]
    out[f"data/{NS}/functions/functional_elven_containers/review.mcfunction"]="\n".join(review)
    return out

def main():
    ap=argparse.ArgumentParser();ap.add_argument("--check",action="store_true");args=ap.parse_args()
    mismatches=[]
    for rel,obj in build().items():
        path=BASE/rel;data=(obj if isinstance(obj,str) else json.dumps(obj,separators=(",",":"))+"\n").encode()
        if args.check:
            if not path.exists() or path.read_bytes()!=data:mismatches.append(rel)
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
    if mismatches:raise SystemExit("Generated output mismatch:\n"+"\n".join(mismatches))
    print(f"{len(build())} functional container resources "+("byte-identical" if args.check else "generated"))

if __name__=="__main__":main()
