"""Generate the eighteen Void stone families with material-specific pixel geology.

The stone IDs and decorative Livingrock stonecutting route are retained, but the textures are
not derived from Botania Livingrock.  tools/material_texture.py owns the geological grammar.
"""
import argparse
import io
import json
from PIL import Image, ImageDraw, ImageFont
from material_texture import VARIANT_COUNT, ROTATIONS, render_texture
from gen_deepworks import ROOT, png, _variant_name, _model_variant_name

CATALOG = ROOT/'alfheim_reclaimed_design/void/void_catalog.json'

def _font(size, bold=False):
    candidates = [
        ROOT/'tools'/'_font_missing_',
        __import__('pathlib').Path('C:/Windows/Fonts') / ('segoeuib.ttf' if bold else 'segoeui.ttf'),
        __import__('pathlib').Path('/usr/share/fonts/truetype/dejavu') / ('DejaVuSans-Bold.ttf' if bold else 'DejaVuSans.ttf'),
    ]
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()

def build():
    catalog=json.loads(CATALOG.read_text())
    out={}; blocks=[]; recipes=[]; natural=[]; textures={}
    def emit(path,value):
        out[path]=value if isinstance(value,bytes) else (json.dumps(value,indent=2)+'\n').encode()

    script=[
        "// Generated by tools/gen_void_materials.py. Requires a full restart.",
        "StartupEvents.registry('block', event => {"
    ]
    families=[(biome,stone) for biome in catalog['biomes'] for stone in biome['stones']]
    for biome,family in families:
        stem=family['id'].split(':')[1]
        natural.append(family['id'])
        f=dict(family,id=stem)
        for form in catalog['forms']:
            name=stem+('' if form=='raw' else '_'+form)
            id='alfheim:'+name
            tf='bricks' if form in ('slab','stairs','wall') else form
            tex=stem+('' if tf=='raw' else '_'+tf)
            tid='alfheim:block/'+tex
            if tex not in textures:
                textures[tex]=[]
                for variant in range(VARIANT_COUNT):
                    vname=_variant_name(tex,variant)
                    image=render_texture(f,tf,variant)
                    textures[tex].append(image)
                    emit('kubejs/assets/alfheim/textures/block/'+vname+'.png',png(image))
            shaped=form in ('slab','stairs','wall')
            if not shaped:
                alternatives=[]
                for variant in range(VARIANT_COUNT):
                    vtex=_variant_name(tex,variant)
                    model_name=_model_variant_name(name,variant)
                    emit('kubejs/assets/alfheim/models/block/'+model_name+'.json',
                         {'parent':'minecraft:block/cube_all','textures':{'all':'alfheim:block/'+vtex}})
                    for rotation in ROTATIONS:
                        entry={'model':'alfheim:block/'+model_name}
                        if rotation: entry['y']=rotation
                        alternatives.append(entry)
                emit('kubejs/assets/alfheim/blockstates/'+name+'.json',
                     {'variants':{'':alternatives}})
            emit('kubejs/assets/alfheim/models/item/'+name+'.json',
                 {'parent':'minecraft:block/wall_inventory','textures':{'wall':tid}}
                 if form=='wall' else {'parent':'alfheim:block/'+name})
            entry={'type':'minecraft:item','name':id}
            if form=='slab':
                entry['functions']=[{
                    'function':'minecraft:set_count',
                    'count':2,
                    'conditions':[{
                        'condition':'minecraft:block_state_property',
                        'block':id,
                        'properties':{'type':'double'}
                    }]
                }]
            emit('kubejs/data/alfheim/loot_tables/blocks/'+name+'.json',{
                'type':'minecraft:block',
                'pools':[{
                    'rolls':1,
                    'conditions':[{'condition':'minecraft:survives_explosion'}],
                    'entries':[entry]
                }]
            })
            source='botania:livingrock' if form=='raw' else family['id']
            count=2 if form=='slab' else 1
            emit('kubejs/data/alfheim/recipes/void/'+name+'.json',{
                'type':'minecraft:stonecutting',
                'ingredient':{'item':source},
                'result':id,
                'count':count
            })
            recipes.append({'id':'alfheim:void/'+name,'input':source,'output':id,'count':count})
            display=family['name']+(
                ' Livingrock' if not family['name'].endswith(('Marble','Slate')) else ''
            )+('' if form=='raw' else ' '+form.title())
            extra=", '"+form+"'" if shaped else ''
            light=(family['light']+0.01)/15 if family['light'] else 0
            line=(
                f"  event.create('{id}'{extra}).displayName('{display}')"
                ".soundType('stone').hardness(2.0).resistance(6.0).requiresTool(true)"
                ".tagBlock('minecraft:mineable/pickaxe').tagBoth('alfheim:livingrock_library')"
                f".tagBoth('alfheim:void_stone').textureAll('{tid}').lightLevel({light:.8f})"
            )
            if shaped:
                line+=f".tagBlock('minecraft:{'walls' if form=='wall' else 'slabs' if form=='slab' else 'stairs'}')"
            script.append(line)
            blocks.append(dict(
                id=id,name=display,form=form,texture=tex,
                texture_variants=[_variant_name(tex,v) for v in range(VARIANT_COUNT)],
                rotations=list(ROTATIONS),light=family['light'],glass=False,slag=False
            ))
    script.append('})\n')
    emit('kubejs/startup_scripts/21_void_stones.js','\n'.join(script).encode())
    for kind in ('items','blocks'):
        emit('kubejs/data/alfheim/tags/'+kind+'/void_natural.json',
             {'replace':False,'values':natural})
    emit('kubejs/void_stones_catalog.json',{'blocks':blocks,'recipes':recipes})

    # Dedicated visual review sheet: every source texture is shown nearest-neighbour at 4×.
    width=780
    height=88+len(families)*76
    sheet=Image.new('RGB',(width,height),'#181e26')
    draw=ImageDraw.Draw(sheet)
    font=_font(14); bold=_font(15,True); title=_font(24,True)
    draw.text((18,14),'ALFHEIM / VOID STONE LIBRARY',font=title,fill='#f2e3c8')
    for col,label in enumerate(('Natural','Polished','Bricks','Carved')):
        draw.text((260+col*104,56),label,font=font,fill='#cbd9da')
    for i,(biome,family) in enumerate(families):
        y=84+i*76
        stem=family['id'].split(':')[1]
        draw.text((18,y+8),family['name'],font=bold,fill='#eee3d2')
        draw.text((18,y+30),biome['name'],font=font,fill='#889da8')
        draw.text((18,y+49),family['fabric'][:29],font=_font(11),fill='#80939d')
        for col,form in enumerate(('raw','polished','bricks','carved')):
            key=stem+('' if form=='raw' else '_'+form)
            sheet.paste(textures[key][0].convert('RGB').resize((64,64),Image.Resampling.NEAREST),
                        (260+col*104,y))
    emit('tools/void_stones_review.png',png(sheet))

    vsheet=Image.new('RGB',(760,92+len(families)*76),'#181e26')
    vd=ImageDraw.Draw(vsheet)
    title=_font(24,True); font=_font(14)
    vd.text((18,14),'VOID MATERIAL VARIANTS / 32px',font=title,fill='#f2e3c8')
    for col,label in enumerate(['V0','V1','V2','V3','V1 · 90°']):
        vd.text((220+col*104,58),label,font=font,fill='#cbd9da')
    for i,(biome,family) in enumerate(families):
        y=88+i*76; stem=family['id'].split(':')[1]
        vd.text((18,y+18),family['name'],font=font,fill='#eee3d2')
        for v in range(VARIANT_COUNT):
            tile=textures[stem][v].convert('RGB').resize((64,64),Image.Resampling.NEAREST)
            vsheet.paste(tile,(220+v*104,y))
        rot=textures[stem][1].rotate(-90,expand=False).convert('RGB').resize((64,64),Image.Resampling.NEAREST)
        vsheet.paste(rot,(220+4*104,y))
    emit('tools/void_stones_variants_review.png',png(vsheet))
    return out

if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    output=build()
    mismatches=[]
    for name,data in output.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=data:
                mismatches.append(name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(data)
    if mismatches:
        raise SystemExit('Generated output mismatch:\n'+'\n'.join(mismatches))
    print(len(output),'Void material files', 'verified' if args.check else 'generated')
