"""Generate the eighteen Void stone families using the established Livingrock pipeline."""
import argparse
import io
import json
import zipfile
from PIL import Image
from gen_deepworks import ROOT, texture, png

CATALOG = ROOT/'alfheim_reclaimed_design/void/void_catalog.json'

def build():
    catalog=json.loads(CATALOG.read_text())
    with zipfile.ZipFile(next((ROOT/'mods').glob('Botania-*.jar'))) as jar:
        base=Image.open(io.BytesIO(jar.read('assets/botania/textures/block/livingrock.png'))).convert('RGBA').crop((0,0,16,16))
    out={}; blocks=[]; recipes=[]; natural=[]
    def emit(path,value): out[path]=value if isinstance(value,bytes) else (json.dumps(value,indent=2)+'\n').encode()
    script=["// Generated by tools/gen_void_materials.py. Requires a full restart.","StartupEvents.registry('block', event => {"]
    patterns=['flecks','bands','veins','patches','bands','fissures','veins','patches','flecks','roots','bands','rings','veins','bands','patches','fissures','patches','flecks']
    for i,family in enumerate(s for b in catalog['biomes'] for s in b['stones']):
        stem=family['id'].split(':')[1]; natural.append(family['id'])
        f=dict(family,id=stem,pattern=patterns[i])
        for form in catalog['forms']:
            name=stem+('' if form=='raw' else '_'+form); id='alfheim:'+name
            tf='bricks' if form in ('slab','stairs','wall') else form
            tex=stem+('' if tf=='raw' else '_'+tf); tid='alfheim:block/'+tex
            emit('kubejs/assets/alfheim/textures/block/'+tex+'.png',png(texture(base,f,tf)))
            shaped=form in ('slab','stairs','wall')
            if not shaped: emit('kubejs/assets/alfheim/models/block/'+name+'.json',{'parent':'minecraft:block/cube_all','textures':{'all':tid}})
            emit('kubejs/assets/alfheim/models/item/'+name+'.json',{'parent':'minecraft:block/wall_inventory','textures':{'wall':tid}} if form=='wall' else {'parent':'alfheim:block/'+name})
            entry={'type':'minecraft:item','name':id}
            if form=='slab': entry['functions']=[{'function':'minecraft:set_count','count':2,'conditions':[{'condition':'minecraft:block_state_property','block':id,'properties':{'type':'double'}}]}]
            emit('kubejs/data/alfheim/loot_tables/blocks/'+name+'.json',{'type':'minecraft:block','pools':[{'rolls':1,'conditions':[{'condition':'minecraft:survives_explosion'}],'entries':[entry]}]})
            source='botania:livingrock' if form=='raw' else family['id']; count=2 if form=='slab' else 1
            emit('kubejs/data/alfheim/recipes/void/'+name+'.json',{'type':'minecraft:stonecutting','ingredient':{'item':source},'result':id,'count':count})
            recipes.append({'id':'alfheim:void/'+name,'input':source,'output':id,'count':count})
            display=family['name']+(' Livingrock' if not family['name'].endswith(('Marble','Slate')) else '')+('' if form=='raw' else ' '+form.title())
            extra=", '"+form+"'" if shaped else ''
            light=(family['light']+0.01)/15 if family['light'] else 0
            line=f"  event.create('{id}'{extra}).displayName('{display}').soundType('stone').hardness(2.0).resistance(6.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBoth('alfheim:livingrock_library').tagBoth('alfheim:void_stone').textureAll('{tid}').lightLevel({light:.8f})"
            if shaped: line+=f".tagBlock('minecraft:{'walls' if form=='wall' else 'slabs' if form=='slab' else 'stairs'}')"
            script.append(line)
            blocks.append(dict(id=id,name=display,form=form,texture=tex,light=family['light'],glass=False,slag=False))
    script.append('})\n')
    emit('kubejs/startup_scripts/21_void_stones.js','\n'.join(script).encode())
    for kind in ('items','blocks'): emit('kubejs/data/alfheim/tags/'+kind+'/void_natural.json',{'replace':False,'values':natural})
    emit('kubejs/void_stones_catalog.json',{'blocks':blocks,'recipes':recipes})
    return out

if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    output=build()
    for name,data in output.items():
        path=ROOT/name
        if args.check: assert path.read_bytes()==data,name
        else: path.parent.mkdir(parents=True,exist_ok=True); path.write_bytes(data)
    print(len(output),'Void material files', 'verified' if args.check else 'generated')
