"""Generate the first exotic elven home-detail pilot."""
from pathlib import Path
import argparse,json
ROOT=Path(__file__).resolve().parents[1];A=ROOT/"kubejs"/"assets"/"alfheim";D=ROOT/"kubejs"/"data"/"alfheim";S=ROOT/"kubejs"/"startup_scripts"/"27_exotic_elven_home.js"
T={"wood":"botania:block/dreamwood_planks","metal":"botania:block/elementium_block","glass":"botania:block/elf_glass_0","stone":"minecraft:block/quartz_block_side","gem":"minecraft:block/amethyst_block","glow":"minecraft:block/sea_lantern","leaf":"minecraft:block/azalea_leaves","water":"minecraft:block/light_blue_stained_glass","dark":"minecraft:block/polished_blackstone","particle":"botania:block/dreamwood_planks"}
def b(a,z,t):return {"from":a,"to":z,"faces":{f:{"texture":"#"+t} for f in ("north","south","east","west","up","down")}}
def m(e):return {"parent":"minecraft:block/block","ambientocclusion":False,"textures":T,"elements":e}
MODELS={
"starbell_chandelier":m([b([7,13,7],[9,16,9],"metal"),b([3,11,7],[13,13,9],"metal"),b([3,6,6],[6,11,10],"glass"),b([7,4,6],[10,11,10],"glass"),b([11,6,6],[14,11,10],"glass"),b([4,7,7],[5,10,9],"glow"),b([8,5,7],[9,10,9],"glow"),b([12,7,7],[13,10,9],"glow")]),
"moonpool_lamp":m([b([4,0,4],[12,2,12],"stone"),b([6,2,6],[10,10,10],"metal"),b([3,9,3],[13,12,13],"water"),b([5,10,5],[11,15,11],"glow")]),
"whisper_harp":m([b([3,0,3],[13,2,13],"stone"),b([3,2,7],[6,16,10],"wood"),b([10,2,7],[13,14,10],"wood"),b([5,13,7],[12,16,10],"metal"),b([6,3,7],[7,14,9],"glass"),b([8,3,7],[9,14,9],"glass"),b([10,3,7],[11,14,9],"glass")]),
"moonmirror":m([b([2,1,14],[14,16,16],"wood"),b([3,2,13],[13,15,15],"metal"),b([4,3,12],[12,14,14],"glass"),b([6,6,11.5],[10,12,13],"water")]),
"levitating_planter":m([b([5,0,5],[11,2,11],"stone"),b([7,2,7],[9,6,9],"glow"),b([3,7,3],[13,10,13],"metal"),b([4,10,4],[12,13,12],"dark"),b([5,12,5],[11,16,11],"leaf")]),
"nectar_fountain":m([b([2,0,2],[14,3,14],"stone"),b([5,3,5],[11,8,11],"metal"),b([3,8,3],[13,11,13],"glass"),b([6,9,6],[10,15,10],"water"),b([7,14,7],[9,16,9],"gem")]),
"bottled_aurora":m([b([4,0,4],[12,2,12],"metal"),b([3,2,3],[13,14,13],"glass"),b([5,4,5],[8,12,8],"glow"),b([8,6,8],[11,13,11],"gem"),b([5,14,5],[11,16,11],"wood")]),
"miniature_ley_garden":m([b([1,0,1],[15,3,15],"wood"),b([2,3,2],[14,5,14],"dark"),b([4,5,4],[6,8,6],"gem"),b([10,5,9],[12,9,11],"glow"),b([6,5,10],[9,7,13],"leaf"),b([7,5,3],[9,6,11],"water")])}
def build():
 out={f"models/block/exotic_home/{k}.json":v for k,v in MODELS.items()};lines=["// GENERATED by tools/gen_exotic_elven_home_pilot.py","const EXOTIC_FACING=BlockProperties.HORIZONTAL_FACING","StartupEvents.registry('block',event=>{"]
 for name in MODELS:
  lines += [f"  let exotic_{name}=event.create('alfheim:{name}','cardinal')",f"    .displayName({json.dumps(name.replace('_',' ').title())})",f"    .model('alfheim:block/exotic_home/{name}')","    .hardness(1.0).resistance(3.0).fullBlock(false).notSolid().noValidSpawns(true)","    .renderType('cutout')","    .box(2, 0, 2, 14, 16, 14)","    .tagBoth('alfheim:exotic_elven_home')",f"  exotic_{name}.rotateState(s=>s.setValue(EXOTIC_FACING,s.rotate(s.getValue(EXOTIC_FACING))))",f"  exotic_{name}.mirrorState(s=>s.setValue(EXOTIC_FACING,s.mirror(s.getValue(EXOTIC_FACING))))",""]
 lines += ["})",""];out["startup"]="\n".join(lines);ids=["alfheim:"+x for x in MODELS];out["tags/blocks/exotic_elven_home.json"]={"replace":False,"values":ids};out["tags/items/exotic_elven_home.json"]={"replace":False,"values":ids}
 review=["# GENERATED by tools/gen_exotic_elven_home_pilot.py","say [Alfheim] placing exotic home pilot"]+[f"setblock ~{i*3} ~ ~0 alfheim:{name}[facing=north]" for i,name in enumerate(MODELS)]+["say [Alfheim] exotic home pilot placed",""];out["review"]="\n".join(review);return out
def path(k):
 if k=="startup":return S
 if k=="review":return D/"functions"/"exotic_elven_home"/"review.mcfunction"
 if k.startswith("models/"):return A/k
 return D/k
def main():
 p=argparse.ArgumentParser();p.add_argument("--check",action="store_true");q=p.parse_args();bad=[]
 for k,v in build().items():
  raw=(v if isinstance(v,str) else json.dumps(v,separators=(",",":"))+"\n").encode();dest=path(k)
  if q.check:
   if not dest.exists() or dest.read_bytes()!=raw:bad.append(str(dest.relative_to(ROOT)))
  else:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(raw)
 if bad:raise SystemExit("Generated output mismatch:\n"+"\n".join(bad))
 print(f"{len(build())} exotic home resources; blocks={len(MODELS)} "+("byte-identical" if q.check else "generated"))
if __name__=="__main__":main()
