"""Deterministic Livingrock library, extending the existing local texture pipeline.

Run from the instance root. --check compares every generated byte without writing.
Blockstates for shaped blocks are generated by the installed KubeJS shape builders.
No terrain, broad replacement tags, progression recipes or existing assets are edited.
"""
from pathlib import Path
import argparse
import colorsys
import hashlib
import io
import json
import math
import random
import zipfile
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = 'kubejs/assets/alfheim'
DATA = 'kubejs/data/alfheim'


def png(image):
    stream = io.BytesIO()
    image.save(stream, format='PNG')
    return stream.getvalue()


def rgb(value):
    return tuple(bytes.fromhex(value))


def texture(base, family, form):
    """Tileable pixel motifs keep the original livingrock relief beneath the geology."""
    rng = random.Random(family['id'])
    color, accent = rgb(family['color']), rgb(family['accent'])
    image = Image.new('RGBA', (16, 16))
    for y in range(16):
        for x in range(16):
            relief = sum(base.getpixel((x, y))[:3]) / (3 * 210)
            if form == 'polished':
                relief = 0.85 + relief * 0.15
            image.putpixel((x, y), tuple(min(255, int(c * relief)) for c in color) + (255,))
    draw = ImageDraw.Draw(image)
    motif = family['pattern']
    if form in ('raw', 'polished'):
        if motif in ('fissures', 'veins', 'roots'):
            x = rng.randrange(16)
            for y in range(16):
                x = (x + rng.choice([-1, 0, 0, 1])) % 16
                image.putpixel((x, y), accent + (255,))
                if motif == 'fissures':
                    image.putpixel(((x+1) % 16, y), tuple(c//2 for c in color) + (255,))
                if y % 5 == 0:
                    for k in range(1, 4):
                        image.putpixel(((x+k) % 16, (y+k) % 16), accent + (255,))
        elif motif == 'bands':
            for x in range(16):
                for offset in (0, 8):
                    y = (int(2 * math.sin(x * math.pi/8)) + offset) % 16
                    image.putpixel((x, y), accent + (255,))
        elif motif == 'rings':
            for x in range(16):
                for y in range(16):
                    if int(math.hypot(x-7.5, y-7.5)) % 4 == 0:
                        image.putpixel((x, y), accent + (255,))
        else:
            for _ in range(18 if motif == 'flecks' else 7):
                x, y = rng.randrange(16), rng.randrange(16)
                for dx, dy in ([(0, 0)] if motif == 'flecks' else [(0,0),(1,0),(0,1),(1,1)]):
                    image.putpixel(((x+dx)%16, (y+dy)%16), accent + (255,))
    if form == 'bricks':
        dark = tuple(c//2 for c in color)
        for y in (0, 8):
            draw.line((0, y, 15, y), fill=dark)
            draw.line((0, y+1, 15, y+1), fill=accent)
        draw.line((0,0,0,7), fill=dark)
        draw.line((8,8,8,15), fill=dark)
    elif form == 'carved':
        draw.rectangle((1,1,14,14), outline=tuple(c//2 for c in color))
        draw.line([(8,3),(12,8),(8,12),(4,8),(8,3)], fill=accent, width=1)
        draw.line((8,5,8,10), fill=accent)
        draw.point((6,8), fill=accent)
    return image


def build():
    manifest = json.loads((ROOT/'tools/deepworks_manifest.json').read_text())
    crystals = json.loads((ROOT/'tools/crystals_manifest.json').read_text())['crystals']
    jar = next((ROOT/'mods').glob('Botania-*.jar'))
    with zipfile.ZipFile(jar) as archive:
        source = archive.read(manifest['source'])
    # Livingrock is a vertical animation strip; derive from its first complete frame.
    base = Image.open(io.BytesIO(source)).convert('RGBA').crop((0,0,16,16))
    out, blocks, recipes, textures = {}, [], [], {}
    def write(path, value):
        out[path] = (json.dumps(value, indent=2)+'\n').encode() if not isinstance(value, bytes) else value
    def tag(kind, name, values):
        write(f'{DATA}/tags/{kind}/{name}.json', {'replace':False,'values':values})
    def recipe(name, ingredient, result, count=1):
        rid = 'deepworks/'+name
        write(f'{DATA}/recipes/{rid}.json', {'type':'minecraft:stonecutting',
              'ingredient':{'item':ingredient},'result':result,'count':count})
        recipes.append({'id':'alfheim:'+rid, 'input':ingredient, 'output':result, 'count':count})
    def block(id, name, tex, form='raw', light=0, glass=False, slag=False):
        row = dict(id='alfheim:'+id, name=name, texture=tex, form=form, light=light,
                   glass=glass, slag=slag)
        blocks.append(row)
        texture_id = 'alfheim:block/'+tex
        if form not in ('slab','stairs','wall'):
            write(f'{ASSETS}/models/block/{id}.json', {'parent':'minecraft:block/cube_all','textures':{'all':texture_id}})
        # Shaped models/blockstates are owned by the actual KubeJS builders.
        write(f'{ASSETS}/models/item/{id}.json',
              {'parent':'minecraft:block/wall_inventory','textures':{'wall':texture_id}} if form=='wall'
              else {'parent':'alfheim:block/'+id})
        conditions = [{'condition':'minecraft:survives_explosion'}]
        if glass:
            conditions.append({'condition':'minecraft:match_tool','predicate':{'enchantments':[
                {'enchantment':'minecraft:silk_touch','levels':{'min':1}}]}})
        entry = {'type':'minecraft:item','name':'alfheim:'+id}
        if form == 'slab':
            entry['functions'] = [{'function':'minecraft:set_count','count':2,'conditions':[
                {'condition':'minecraft:block_state_property','block':'alfheim:'+id,'properties':{'type':'double'}}]}]
        write(f'{DATA}/loot_tables/blocks/{id}.json', {'type':'minecraft:block','pools':[] if slag else [
            {'rolls':1,'conditions':conditions,'entries':[entry]}]})
    natural, hot = [], []
    for family in manifest['families']:
        stem = family['id']
        natural.append('alfheim:'+stem)
        if family['group']=='Furnace': hot.append('alfheim:'+stem)
        for form in manifest['forms']:
            id = stem if form=='raw' else stem+'_'+form
            texture_form = 'bricks' if form in ('slab','stairs','wall') else form
            tex = stem if texture_form=='raw' else stem+'_'+texture_form
            if tex not in textures:
                textures[tex] = texture(base, family, texture_form)
                write(f'{ASSETS}/textures/block/{tex}.png', png(textures[tex]))
            name = family['name'] + ('' if form=='raw' else ' '+form.title())
            block(id, name, tex, form, family['light'])
            recipe(id, 'botania:livingrock' if form=='raw' else 'alfheim:'+stem,
                   'alfheim:'+id, 2 if form=='slab' else 1)
        tag('items', 'livingrock_family/'+stem, ['alfheim:'+stem]+['alfheim:'+stem+'_'+s for s in manifest['forms'] if s!='raw'])
    slag = dict(id='livingrock_slag',color='56525b',accent='857b80',pattern='patches')
    textures['livingrock_slag'] = texture(base, slag, 'raw')
    write(f'{ASSETS}/textures/block/livingrock_slag.png', png(textures['livingrock_slag']))
    block('livingrock_slag','Livingrock Slag','livingrock_slag',slag=True)
    for crystal in crystals:
        element = crystal['element'].lower()
        id = 'mana_glass_'+element
        col = tuple(int(c*255) for c in colorsys.hsv_to_rgb(crystal['hue']/360,
                    min(0.8, crystal['sat']*0.5), min(1,crystal['val']*0.8)))
        glass = Image.new('RGBA',(16,16),col+(65,))
        draw = ImageDraw.Draw(glass)
        draw.rectangle((0,0,15,15),outline=col+(205,))
        draw.line((3,6,6,3),fill=(230,245,245,130))
        draw.line((9,12,12,9),fill=(230,245,245,130))
        textures[id]=glass
        write(f'{ASSETS}/textures/block/{id}.png',png(glass))
        block(id, crystal['element']+' Mana-glass',id,light=manifest['glass_light'][element],glass=True)
        # Decorative glass does not consume or produce scarce progression crystals.
        recipe(id,'minecraft:glass','alfheim:'+id)
    script = ["// Generated by tools/gen_deepworks.py; restart the client after regeneration.",
              "StartupEvents.registry('block', event => {"]
    for b in blocks:
        shaped = b['form'] in ('slab','stairs','wall')
        extra = ", '"+b['form']+"'" if shaped else ''
        line = f"  event.create('{b['id']}'{extra}).displayName('{b['name']}')"
        line += f".soundType('{('glass' if b['glass'] else 'stone')}').hardness({0.3 if b['glass'] else 0.6 if b['slag'] else 2.0}).resistance(6.0)"
        line += ".requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBoth('alfheim:livingrock_library')"
        # KubeJS multiplies this float by 15 then truncates. Bias within the intended
        # integer bucket so 2/15's decimal rounding cannot turn light level 2 into 1.
        normalized_light = (b['light']+0.01)/15 if b['light'] else 0
        line += f".textureAll('alfheim:block/{b['texture']}').lightLevel({normalized_light:.8f})"
        if b['glass']: line += ".defaultTranslucent()"
        if shaped: line += f".tagBlock('minecraft:{'walls' if b['form']=='wall' else 'slabs' if b['form']=='slab' else 'stairs'}')"
        script.append(line)
    script.append('})\n')
    write('kubejs/startup_scripts/20_deepworks.js','\n'.join(script).encode())
    tag('blocks','livingrock_natural', natural)
    tag('items','livingrock_natural', natural)
    tag('blocks','deepworks_stone', natural+['alfheim:livingrock_slag'])
    tag('blocks','deepworks_hot_stone',['alfheim:magmatic_livingrock','alfheim:embervein_livingrock'])
    tag('blocks','deepworks_replaceable',['botania:livingrock']+natural)
    tag('blocks','mana_glass',['alfheim:mana_glass_'+c['element'].lower() for c in crystals])
    write('kubejs/deepworks_catalog.json',{'blocks':blocks,'recipes':recipes})
    write('tools/deepworks_source.json',{'jar':jar.name,'asset':manifest['source'],'sha256':hashlib.sha256(source).hexdigest()})
    # Labelled nearest-neighbour atlas: every original texture appears at an integer scale.
    sheet = Image.new('RGB',(1060,150+len(manifest['families'])*76+112),'#181e26')
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',16)
    title = ImageFont.truetype('C:/Windows/Fonts/segoeuib.ttf',26)
    draw.text((24,18),'ALFHEIM / THE LIVINGROCK LIBRARY',font=title,fill='#f2e3c8')
    draw.text((24,57),'24 stone families | 7 forms each | six aligned mana-glasses | cooled slag',font=font,fill='#b4c7cb')
    for col,label in enumerate(['Natural','Polished','Bricks','Carved']):
        draw.text((300+col*104,105),label,font=font,fill='#cbd9da')
    draw.text((728,105),'Structure palette',font=font,fill='#cbd9da')
    for i,f in enumerate(manifest['families']):
        y=145+i*76
        draw.text((24,y+10),f['name'],font=font,fill='#eee3d2')
        draw.text((24,y+34),f['group'],font=font,fill='#889da8')
        for col,form in enumerate(['raw','polished','bricks','carved']):
            key=f['id']+('' if form=='raw' else '_'+form)
            sheet.paste(textures[key].convert('RGB').resize((64,64),Image.Resampling.NEAREST),(300+col*104,y))
        words=f['use'].split(); lines=['']
        for word in words:
            if len(lines[-1])+len(word)>34: lines.append('')
            lines[-1]+=(' ' if lines[-1] else '')+word
        draw.multiline_text((728,y+8),'\n'.join(lines),font=font,fill='#b9c7c8',spacing=5)
    y=150+len(manifest['families'])*76
    for i,key in enumerate(['mana_glass_'+c['element'].lower() for c in crystals]+['livingrock_slag']):
        x=24+i*146
        tile=Image.new('RGBA',(16,16),'#768088'); tile.alpha_composite(textures[key])
        sheet.paste(tile.convert('RGB').resize((64,64),Image.Resampling.NEAREST),(x,y))
        draw.text((x,y+68),key.replace('mana_glass_','').replace('livingrock_','').title(),font=font,fill='#d3dddc')
    write('tools/deepworks_review.png',png(sheet))
    return out


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    output=build()
    mismatches=[]
    for name,data in output.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=data: mismatches.append(name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(data)
    if mismatches:
        raise SystemExit('Generated output mismatch:\n'+'\n'.join(mismatches))
    print(f'{len(output)} files '+('byte-identical' if args.check else 'generated'))


if __name__=='__main__': main()
