"""Generate Alfheim's Deep stone library from material-specific pixel geology.

Run from the instance root. --check compares every generated byte without writing.
Blockstates for shaped blocks are generated by the installed KubeJS shape builders.
The 24 stone families are procedurally authored by tools/material_texture.py and do not
sample or recolor Botania Livingrock. Mana-glass remains alignment-driven.
"""
from pathlib import Path
import argparse
import hashlib
import io
import json
from PIL import Image, ImageDraw, ImageFont
from material_texture import (
    ENGINE_VERSION, OUTPUT_SIZE, VARIANT_COUNT, ROTATIONS,
    render_texture, render_slag, render_mana_glass
)

ROOT = Path(__file__).resolve().parents[1]
ASSETS = 'kubejs/assets/alfheim'
DATA = 'kubejs/data/alfheim'

def png(image):
    stream = io.BytesIO()
    image.save(stream, format='PNG')
    return stream.getvalue()

def _font(size, bold=False):
    candidates = [
        Path('C:/Windows/Fonts') / ('segoeuib.ttf' if bold else 'segoeui.ttf'),
        Path('/usr/share/fonts/truetype/dejavu') / ('DejaVuSans-Bold.ttf' if bold else 'DejaVuSans.ttf'),
    ]
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()

def _variant_name(texture, variant):
    return texture if variant == 0 else f"{texture}_v{variant}"

def _model_variant_name(block_id, variant):
    return block_id if variant == 0 else f"{block_id}__v{variant}"

def build():
    manifest = json.loads((ROOT/'tools/deepworks_manifest.json').read_text())
    crystals = json.loads((ROOT/'tools/crystals_manifest.json').read_text())['crystals']
    out, blocks, recipes, textures = {}, [], [], {}

    def write(path, value):
        out[path] = (json.dumps(value, indent=2)+'\n').encode() if not isinstance(value, bytes) else value

    def tag(kind, name, values):
        write(f'{DATA}/tags/{kind}/{name}.json', {'replace':False,'values':values})

    def recipe(name, ingredient, result, count=1):
        rid = 'deepworks/'+name
        write(f'{DATA}/recipes/{rid}.json', {
            'type':'minecraft:stonecutting',
            'ingredient':{'item':ingredient},
            'result':result,
            'count':count
        })
        recipes.append({'id':'alfheim:'+rid, 'input':ingredient, 'output':result, 'count':count})

    def block(id, name, tex, form='raw', light=0, glass=False, slag=False, variant_textures=None):
        variant_textures = variant_textures or [tex]
        row = dict(
            id='alfheim:'+id, name=name, texture=tex, texture_variants=variant_textures,
            rotations=list(ROTATIONS), form=form, light=light, glass=glass, slag=slag
        )
        blocks.append(row)
        if form not in ('slab','stairs','wall'):
            alternatives=[]
            for variant, vtex in enumerate(variant_textures):
                model_name=_model_variant_name(id, variant)
                texture_id='alfheim:block/'+vtex
                write(f'{ASSETS}/models/block/{model_name}.json', {
                    'parent':'minecraft:block/cube_all',
                    'textures':{'all':texture_id}
                })
                for rotation in ROTATIONS:
                    entry={'model':'alfheim:block/'+model_name}
                    if rotation:
                        entry['y']=rotation
                    alternatives.append(entry)
            write(f'{ASSETS}/blockstates/{id}.json', {'variants':{'':alternatives}})
        texture_id = 'alfheim:block/'+tex
        write(
            f'{ASSETS}/models/item/{id}.json',
            {'parent':'minecraft:block/wall_inventory','textures':{'wall':texture_id}}
            if form=='wall' else {'parent':'alfheim:block/'+id}
        )
        conditions = [{'condition':'minecraft:survives_explosion'}]
        if glass:
            conditions.append({
                'condition':'minecraft:match_tool',
                'predicate':{'enchantments':[{
                    'enchantment':'minecraft:silk_touch',
                    'levels':{'min':1}
                }]}
            })
        entry = {'type':'minecraft:item','name':'alfheim:'+id}
        if form == 'slab':
            entry['functions'] = [{
                'function':'minecraft:set_count',
                'count':2,
                'conditions':[{
                    'condition':'minecraft:block_state_property',
                    'block':'alfheim:'+id,
                    'properties':{'type':'double'}
                }]
            }]
        write(f'{DATA}/loot_tables/blocks/{id}.json', {
            'type':'minecraft:block',
            'pools':[] if slag else [{
                'rolls':1,
                'conditions':conditions,
                'entries':[entry]
            }]
        })

    natural, hot = [], []
    for family in manifest['families']:
        stem = family['id']
        natural.append('alfheim:'+stem)
        if family['group']=='Furnace':
            hot.append('alfheim:'+stem)
        for form in manifest['forms']:
            id = stem if form=='raw' else stem+'_'+form
            texture_form = 'bricks' if form in ('slab','stairs','wall') else form
            tex = stem if texture_form=='raw' else stem+'_'+texture_form
            if tex not in textures:
                textures[tex] = []
                for variant in range(VARIANT_COUNT):
                    vname=_variant_name(tex,variant)
                    image=render_texture(family, texture_form, variant)
                    textures[tex].append(image)
                    write(f'{ASSETS}/textures/block/{vname}.png', png(image))
            names=[_variant_name(tex,v) for v in range(VARIANT_COUNT)]
            name = family['name'] + ('' if form=='raw' else ' '+form.title())
            block(id, name, tex, form, family['light'], variant_textures=names)
            recipe(
                id,
                'botania:livingrock' if form=='raw' else 'alfheim:'+stem,
                'alfheim:'+id,
                2 if form=='slab' else 1
            )
        tag('items', 'livingrock_family/'+stem, ['alfheim:'+stem]+[
            'alfheim:'+stem+'_'+s for s in manifest['forms'] if s!='raw'
        ])

    textures['livingrock_slag'] = []
    for variant in range(VARIANT_COUNT):
        vname=_variant_name('livingrock_slag',variant)
        image=render_slag(variant)
        textures['livingrock_slag'].append(image)
        write(f'{ASSETS}/textures/block/{vname}.png', png(image))
    block(
        'livingrock_slag','Livingrock Slag','livingrock_slag',slag=True,
        variant_textures=[_variant_name('livingrock_slag',v) for v in range(VARIANT_COUNT)]
    )

    for crystal in crystals:
        element = crystal['element'].lower()
        id = 'mana_glass_'+element
        textures[id]=[]
        for variant in range(VARIANT_COUNT):
            vname=_variant_name(id,variant)
            image=render_mana_glass(crystal,variant)
            textures[id].append(image)
            write(f'{ASSETS}/textures/block/{vname}.png',png(image))
        block(
            id, crystal['element']+' Mana-glass',id,
            light=manifest['glass_light'][element],glass=True,
            variant_textures=[_variant_name(id,v) for v in range(VARIANT_COUNT)]
        )
        recipe(id,'minecraft:glass','alfheim:'+id)

    script = [
        "// Generated by tools/gen_deepworks.py; restart the client after regeneration.",
        "StartupEvents.registry('block', event => {"
    ]
    for b in blocks:
        shaped = b['form'] in ('slab','stairs','wall')
        extra = ", '"+b['form']+"'" if shaped else ''
        line = f"  event.create('{b['id']}'{extra}).displayName('{b['name']}')"
        line += f".soundType('{('glass' if b['glass'] else 'stone')}').hardness({0.3 if b['glass'] else 0.6 if b['slag'] else 2.0}).resistance(6.0)"
        line += ".requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBoth('alfheim:livingrock_library')"
        normalized_light = (b['light']+0.01)/15 if b['light'] else 0
        line += f".textureAll('alfheim:block/{b['texture']}').lightLevel({normalized_light:.8f})"
        if b['glass']:
            line += ".defaultTranslucent()"
        if shaped:
            line += f".tagBlock('minecraft:{'walls' if b['form']=='wall' else 'slabs' if b['form']=='slab' else 'stairs'}')"
        script.append(line)
    script.append('})\n')
    write('kubejs/startup_scripts/20_deepworks.js','\n'.join(script).encode())

    tag('blocks','livingrock_natural', natural)
    tag('items','livingrock_natural', natural)
    tag('blocks','deepworks_stone', natural+['alfheim:livingrock_slag'])
    tag('blocks','deepworks_hot_stone',['alfheim:magmatic_livingrock','alfheim:embervein_livingrock'])
    tag('blocks','deepworks_replaceable',['botania:livingrock']+natural)
    tag('blocks','mana_glass',['alfheim:mana_glass_'+c['element'].lower() for c in crystals])
    write('kubejs/deepworks_catalog.json',{'blocks':blocks,'recipes':recipes})

    engine_path = ROOT/'tools/material_texture.py'
    write('tools/deepworks_source.json',{
        'engine':'tools/material_texture.py',
        'engine_version':ENGINE_VERSION,
        'sha256':hashlib.sha256(engine_path.read_bytes()).hexdigest(),
        'livingrock_relief':False,
        'note':'The 24 stone families are material-specific procedural pixel art; Botania Livingrock is acquisition only.'
    })

    sheet = Image.new('RGB',(1060,150+len(manifest['families'])*76+112),'#181e26')
    draw = ImageDraw.Draw(sheet)
    font = _font(16)
    title = _font(26, True)
    draw.text((24,18),'ALFHEIM / THE LIVINGROCK LIBRARY',font=title,fill='#f2e3c8')
    draw.text((24,57),'24 material-specific stone families | 7 forms each | six aligned mana-glasses | cooled slag',
              font=font,fill='#b4c7cb')
    for col,label in enumerate(['Natural','Polished','Bricks','Carved']):
        draw.text((300+col*104,105),label,font=font,fill='#cbd9da')
    draw.text((728,105),'Structure palette',font=font,fill='#cbd9da')
    for i,f in enumerate(manifest['families']):
        y=145+i*76
        draw.text((24,y+10),f['name'],font=font,fill='#eee3d2')
        draw.text((24,y+34),f['group'],font=font,fill='#889da8')
        for col,form in enumerate(['raw','polished','bricks','carved']):
            key=f['id']+('' if form=='raw' else '_'+form)
            sheet.paste(textures[key][0].convert('RGB').resize((64,64),Image.Resampling.NEAREST),
                        (300+col*104,y))
        words=f['use'].split()
        lines=['']
        for word in words:
            if len(lines[-1])+len(word)>34:
                lines.append('')
            lines[-1]+=(' ' if lines[-1] else '')+word
        draw.multiline_text((728,y+8),'\n'.join(lines),font=font,fill='#b9c7c8',spacing=5)
    y=150+len(manifest['families'])*76
    for i,key in enumerate(['mana_glass_'+c['element'].lower() for c in crystals]+['livingrock_slag']):
        x=24+i*146
        tile=Image.new('RGBA',(OUTPUT_SIZE,OUTPUT_SIZE),'#768088')
        tile.alpha_composite(textures[key][0])
        sheet.paste(tile.convert('RGB').resize((64,64),Image.Resampling.NEAREST),(x,y))
        draw.text((x,y+68),key.replace('mana_glass_','').replace('livingrock_','').title(),
                  font=font,fill='#d3dddc')
    write('tools/deepworks_review.png',png(sheet))

    # Variant/rotation acceptance board: four natural tiles plus a rotated sample per family.
    vsheet=Image.new('RGB',(760,92+len(manifest['families'])*76),'#181e26')
    vd=ImageDraw.Draw(vsheet)
    vd.text((18,14),'DEEP MATERIAL VARIANTS / 32px',font=title,fill='#f2e3c8')
    for col,label in enumerate(['V0','V1','V2','V3','V1 · 90°']):
        vd.text((220+col*104,58),label,font=font,fill='#cbd9da')
    for i,f in enumerate(manifest['families']):
        y=88+i*76; key=f['id']
        vd.text((18,y+18),f['name'],font=font,fill='#eee3d2')
        for v in range(VARIANT_COUNT):
            tile=textures[key][v].convert('RGB').resize((64,64),Image.Resampling.NEAREST)
            vsheet.paste(tile,(220+v*104,y))
        rot=textures[key][1].rotate(-90,expand=False).convert('RGB').resize((64,64),Image.Resampling.NEAREST)
        vsheet.paste(rot,(220+4*104,y))
    write('tools/deepworks_variants_review.png',png(vsheet))
    return out

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    output=build()
    mismatches=[]
    for name,data in output.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=data:
                mismatches.append(name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(data)
    if mismatches:
        raise SystemExit('Generated output mismatch:\n'+'\n'.join(mismatches))
    print(f'{len(output)} files '+('byte-identical' if args.check else 'generated'))

if __name__=='__main__':
    main()
