# GENERATED by tools/gen_elven_sculptural_details.py
say [Alfheim] placing sculptural detail gallery
setblock ~0 ~ ~0 alfheim:ancestor_statue_lower[facing=north]
setblock ~0 ~1 ~0 alfheim:ancestor_statue_upper[facing=north]
setblock ~3 ~ ~0 alfheim:oathkeeper_statue_lower[facing=north]
setblock ~3 ~1 ~0 alfheim:oathkeeper_statue_upper[facing=north]
setblock ~6 ~ ~0 alfheim:mourning_statue_lower[facing=north]
setblock ~6 ~1 ~0 alfheim:mourning_statue_upper[facing=north]
setblock ~10 ~ ~0 alfheim:large_crystal_plinth_base[facing=north]
setblock ~10 ~1 ~0 alfheim:large_crystal_plinth_crystal[facing=north]
setblock ~13 ~ ~0 alfheim:observatory_prism_stand[facing=north]
setblock ~16 ~ ~0 alfheim:gemstone_wall_jewel[facing=north]
setblock ~19 ~ ~0 alfheim:gemstone_floor_inlay[facing=north]
setblock ~22 ~ ~0 alfheim:gemstone_finial[facing=north]
say [Alfheim] sculptural gallery placed
