# GENERATED by tools/gen_royal_tileset_wave_a.py
# Run only in a disposable review area: /function alfheim:royal_tileset_wave_a/review
say [Alfheim] placing complete Royal Tile Set I Wave A review gallery
setblock ~0 ~ ~0 alfheim:royal_highback_chair[facing=north]
setblock ~3 ~ ~0 alfheim:royal_wall_sconce[facing=north]
setblock ~6 ~ ~0 alfheim:royal_carpet_runner[facing=north]
setblock ~9 ~ ~0 alfheim:royal_balustrade[facing=north]
setblock ~12 ~ ~0 alfheim:royal_lidded_amphora[facing=north]
setblock ~15 ~ ~0 alfheim:royal_wall_banner[facing=north]
# 2x3 canopy bed
setblock ~0 ~ ~5 alfheim:royal_canopy_bed_head_left[facing=north]
setblock ~1 ~ ~5 alfheim:royal_canopy_bed_head_right[facing=north]
setblock ~0 ~ ~6 alfheim:royal_canopy_bed_middle_left[facing=north]
setblock ~1 ~ ~6 alfheim:royal_canopy_bed_middle_right[facing=north]
setblock ~0 ~ ~7 alfheim:royal_canopy_bed_foot_left[facing=north]
setblock ~1 ~ ~7 alfheim:royal_canopy_bed_foot_right[facing=north]
# 2x2 astrolabe
setblock ~5 ~ ~5 alfheim:royal_astrolabe_nw[facing=north]
setblock ~6 ~ ~5 alfheim:royal_astrolabe_ne[facing=north]
setblock ~5 ~ ~6 alfheim:royal_astrolabe_sw[facing=north]
setblock ~6 ~ ~6 alfheim:royal_astrolabe_se[facing=north]
# Remaining Wave A identity primitives
setblock ~10 ~ ~5 alfheim:royal_tall_cabinet[facing=north]
setblock ~13 ~ ~5 alfheim:royal_mana_brazier[facing=north]
setblock ~16 ~ ~5 alfheim:royal_goblet_service[facing=north]
setblock ~19 ~ ~5 alfheim:royal_finial[facing=north]
setblock ~22 ~ ~5 alfheim:royal_pedestal_planter[facing=north]
# Three-block vertical lineage stele
setblock ~0 ~ ~10 alfheim:royal_lineage_stele_base[facing=north]
setblock ~0 ~1 ~10 alfheim:royal_lineage_stele_mid[facing=north]
setblock ~0 ~2 ~10 alfheim:royal_lineage_stele_crown[facing=north]
# Two-block audience bench, writing desk and weapon rack
setblock ~4 ~ ~10 alfheim:royal_audience_bench_left[facing=north]
setblock ~5 ~ ~10 alfheim:royal_audience_bench_right[facing=north]
setblock ~8 ~ ~10 alfheim:royal_writing_desk_left[facing=north]
setblock ~9 ~ ~10 alfheim:royal_writing_desk_right[facing=north]
setblock ~12 ~ ~10 alfheim:royal_weapon_rack_left[facing=north]
setblock ~13 ~ ~10 alfheim:royal_weapon_rack_right[facing=north]
say [Alfheim] complete Wave A gallery placed; inspect geometry, collision, facing and seams
